# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CapFloorLet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CapFloorLet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCapFloorLet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CapFloorLet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CapFloorLet
    def PaymentDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CapFloorLet
    def AccrualStartDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CapFloorLet
    def AccrualEndDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CapFloorLet
    def FixingDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CapFloorLet
    def Strike(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CapFloorLet
    def ForwardRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CapFloorLet
    def Discount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CapFloorLet
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CapFloorLetStart(builder):
    builder.StartObject(8)

def Start(builder):
    CapFloorLetStart(builder)

def CapFloorLetAddPaymentDate(builder, paymentDate):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(paymentDate), 0)

def AddPaymentDate(builder, paymentDate):
    CapFloorLetAddPaymentDate(builder, paymentDate)

def CapFloorLetAddAccrualStartDate(builder, accrualStartDate):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(accrualStartDate), 0)

def AddAccrualStartDate(builder, accrualStartDate):
    CapFloorLetAddAccrualStartDate(builder, accrualStartDate)

def CapFloorLetAddAccrualEndDate(builder, accrualEndDate):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(accrualEndDate), 0)

def AddAccrualEndDate(builder, accrualEndDate):
    CapFloorLetAddAccrualEndDate(builder, accrualEndDate)

def CapFloorLetAddFixingDate(builder, fixingDate):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(fixingDate), 0)

def AddFixingDate(builder, fixingDate):
    CapFloorLetAddFixingDate(builder, fixingDate)

def CapFloorLetAddStrike(builder, strike):
    builder.PrependFloat64Slot(4, strike, 0.0)

def AddStrike(builder, strike):
    CapFloorLetAddStrike(builder, strike)

def CapFloorLetAddForwardRate(builder, forwardRate):
    builder.PrependFloat64Slot(5, forwardRate, 0.0)

def AddForwardRate(builder, forwardRate):
    CapFloorLetAddForwardRate(builder, forwardRate)

def CapFloorLetAddDiscount(builder, discount):
    builder.PrependFloat64Slot(6, discount, 0.0)

def AddDiscount(builder, discount):
    CapFloorLetAddDiscount(builder, discount)

def CapFloorLetAddPrice(builder, price):
    builder.PrependFloat64Slot(7, price, 0.0)

def AddPrice(builder, price):
    CapFloorLetAddPrice(builder, price)

def CapFloorLetEnd(builder):
    return builder.EndObject()

def End(builder):
    return CapFloorLetEnd(builder)


class CapFloorLetT(object):

    # CapFloorLetT
    def __init__(self):
        self.paymentDate = None  # type: str
        self.accrualStartDate = None  # type: str
        self.accrualEndDate = None  # type: str
        self.fixingDate = None  # type: str
        self.strike = 0.0  # type: float
        self.forwardRate = 0.0  # type: float
        self.discount = 0.0  # type: float
        self.price = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        capFloorLet = CapFloorLet()
        capFloorLet.Init(buf, pos)
        return cls.InitFromObj(capFloorLet)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, capFloorLet):
        x = CapFloorLetT()
        x._UnPack(capFloorLet)
        return x

    # CapFloorLetT
    def _UnPack(self, capFloorLet):
        if capFloorLet is None:
            return
        self.paymentDate = capFloorLet.PaymentDate()
        self.accrualStartDate = capFloorLet.AccrualStartDate()
        self.accrualEndDate = capFloorLet.AccrualEndDate()
        self.fixingDate = capFloorLet.FixingDate()
        self.strike = capFloorLet.Strike()
        self.forwardRate = capFloorLet.ForwardRate()
        self.discount = capFloorLet.Discount()
        self.price = capFloorLet.Price()

    # CapFloorLetT
    def Pack(self, builder):
        if self.paymentDate is not None:
            paymentDate = builder.CreateString(self.paymentDate)
        if self.accrualStartDate is not None:
            accrualStartDate = builder.CreateString(self.accrualStartDate)
        if self.accrualEndDate is not None:
            accrualEndDate = builder.CreateString(self.accrualEndDate)
        if self.fixingDate is not None:
            fixingDate = builder.CreateString(self.fixingDate)
        CapFloorLetStart(builder)
        if self.paymentDate is not None:
            CapFloorLetAddPaymentDate(builder, paymentDate)
        if self.accrualStartDate is not None:
            CapFloorLetAddAccrualStartDate(builder, accrualStartDate)
        if self.accrualEndDate is not None:
            CapFloorLetAddAccrualEndDate(builder, accrualEndDate)
        if self.fixingDate is not None:
            CapFloorLetAddFixingDate(builder, fixingDate)
        CapFloorLetAddStrike(builder, self.strike)
        CapFloorLetAddForwardRate(builder, self.forwardRate)
        CapFloorLetAddDiscount(builder, self.discount)
        CapFloorLetAddPrice(builder, self.price)
        capFloorLet = CapFloorLetEnd(builder)
        return capFloorLet
