# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Credit Default Swap instrument.
class CDS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CDS()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCDS(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CDS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CDS
    def Side(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return None

    # Notional. Presence-required and must be > 0.
    # CDS
    def Notional(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return None

    # Running coupon in decimal (0.01 = 100bps). Required; presence-driven
    # (a genuine 0 is a valid zero-coupon CDS, an absent value is rejected).
    # CDS
    def RunningCoupon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return None

    # CDS
    def Schedule(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Schedule import Schedule
            obj = Schedule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Upfront payment. Optional: presence selects the upfront-bearing
    # CreditDefaultSwap constructor (a genuine 0 upfront is representable);
    # absent selects the plain no-upfront constructor.
    # CDS
    def Upfront(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return None

    # CDS
    def DayCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return None

    # CDS
    def BusinessDayConvention(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return None

    # CDS
    def SettlesAccrual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # CDS
    def PaysAtDefaultTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # CDS
    def RebatesAccrual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # CDS
    def ProtectionStart(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CDS
    def UpfrontDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CDS
    def LastPeriodDayCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CDS
    def TradeDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CDS
    def CashSettlementDays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 3

def CDSStart(builder):
    builder.StartObject(15)

def Start(builder):
    CDSStart(builder)

def CDSAddSide(builder, side):
    builder.PrependInt8Slot(0, side, None)

def AddSide(builder, side):
    CDSAddSide(builder, side)

def CDSAddNotional(builder, notional):
    builder.PrependFloat64Slot(1, notional, None)

def AddNotional(builder, notional):
    CDSAddNotional(builder, notional)

def CDSAddRunningCoupon(builder, runningCoupon):
    builder.PrependFloat64Slot(2, runningCoupon, None)

def AddRunningCoupon(builder, runningCoupon):
    CDSAddRunningCoupon(builder, runningCoupon)

def CDSAddSchedule(builder, schedule):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(schedule), 0)

def AddSchedule(builder, schedule):
    CDSAddSchedule(builder, schedule)

def CDSAddUpfront(builder, upfront):
    builder.PrependFloat64Slot(4, upfront, None)

def AddUpfront(builder, upfront):
    CDSAddUpfront(builder, upfront)

def CDSAddDayCounter(builder, dayCounter):
    builder.PrependInt8Slot(5, dayCounter, None)

def AddDayCounter(builder, dayCounter):
    CDSAddDayCounter(builder, dayCounter)

def CDSAddBusinessDayConvention(builder, businessDayConvention):
    builder.PrependInt8Slot(6, businessDayConvention, None)

def AddBusinessDayConvention(builder, businessDayConvention):
    CDSAddBusinessDayConvention(builder, businessDayConvention)

def CDSAddSettlesAccrual(builder, settlesAccrual):
    builder.PrependBoolSlot(7, settlesAccrual, 1)

def AddSettlesAccrual(builder, settlesAccrual):
    CDSAddSettlesAccrual(builder, settlesAccrual)

def CDSAddPaysAtDefaultTime(builder, paysAtDefaultTime):
    builder.PrependBoolSlot(8, paysAtDefaultTime, 1)

def AddPaysAtDefaultTime(builder, paysAtDefaultTime):
    CDSAddPaysAtDefaultTime(builder, paysAtDefaultTime)

def CDSAddRebatesAccrual(builder, rebatesAccrual):
    builder.PrependBoolSlot(9, rebatesAccrual, 1)

def AddRebatesAccrual(builder, rebatesAccrual):
    CDSAddRebatesAccrual(builder, rebatesAccrual)

def CDSAddProtectionStart(builder, protectionStart):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(protectionStart), 0)

def AddProtectionStart(builder, protectionStart):
    CDSAddProtectionStart(builder, protectionStart)

def CDSAddUpfrontDate(builder, upfrontDate):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(upfrontDate), 0)

def AddUpfrontDate(builder, upfrontDate):
    CDSAddUpfrontDate(builder, upfrontDate)

def CDSAddLastPeriodDayCounter(builder, lastPeriodDayCounter):
    builder.PrependInt8Slot(12, lastPeriodDayCounter, 0)

def AddLastPeriodDayCounter(builder, lastPeriodDayCounter):
    CDSAddLastPeriodDayCounter(builder, lastPeriodDayCounter)

def CDSAddTradeDate(builder, tradeDate):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(tradeDate), 0)

def AddTradeDate(builder, tradeDate):
    CDSAddTradeDate(builder, tradeDate)

def CDSAddCashSettlementDays(builder, cashSettlementDays):
    builder.PrependInt32Slot(14, cashSettlementDays, 3)

def AddCashSettlementDays(builder, cashSettlementDays):
    CDSAddCashSettlementDays(builder, cashSettlementDays)

def CDSEnd(builder):
    return builder.EndObject()

def End(builder):
    return CDSEnd(builder)

try:
    from typing import Optional
except:
    pass

class CDST(object):

    # CDST
    def __init__(self):
        self.side = None  # type: Optional[int]
        self.notional = None  # type: Optional[float]
        self.runningCoupon = None  # type: Optional[float]
        self.schedule = None  # type: Optional[ScheduleT]
        self.upfront = None  # type: Optional[float]
        self.dayCounter = None  # type: Optional[int]
        self.businessDayConvention = None  # type: Optional[int]
        self.settlesAccrual = True  # type: bool
        self.paysAtDefaultTime = True  # type: bool
        self.rebatesAccrual = True  # type: bool
        self.protectionStart = None  # type: str
        self.upfrontDate = None  # type: str
        self.lastPeriodDayCounter = 0  # type: int
        self.tradeDate = None  # type: str
        self.cashSettlementDays = 3  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cds = CDS()
        cds.Init(buf, pos)
        return cls.InitFromObj(cds)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cds):
        x = CDST()
        x._UnPack(cds)
        return x

    # CDST
    def _UnPack(self, cds):
        if cds is None:
            return
        self.side = cds.Side()
        self.notional = cds.Notional()
        self.runningCoupon = cds.RunningCoupon()
        if cds.Schedule() is not None:
            self.schedule = ScheduleT.InitFromObj(cds.Schedule())
        self.upfront = cds.Upfront()
        self.dayCounter = cds.DayCounter()
        self.businessDayConvention = cds.BusinessDayConvention()
        self.settlesAccrual = cds.SettlesAccrual()
        self.paysAtDefaultTime = cds.PaysAtDefaultTime()
        self.rebatesAccrual = cds.RebatesAccrual()
        self.protectionStart = cds.ProtectionStart()
        self.upfrontDate = cds.UpfrontDate()
        self.lastPeriodDayCounter = cds.LastPeriodDayCounter()
        self.tradeDate = cds.TradeDate()
        self.cashSettlementDays = cds.CashSettlementDays()

    # CDST
    def Pack(self, builder):
        if self.schedule is not None:
            schedule = self.schedule.Pack(builder)
        if self.protectionStart is not None:
            protectionStart = builder.CreateString(self.protectionStart)
        if self.upfrontDate is not None:
            upfrontDate = builder.CreateString(self.upfrontDate)
        if self.tradeDate is not None:
            tradeDate = builder.CreateString(self.tradeDate)
        CDSStart(builder)
        CDSAddSide(builder, self.side)
        CDSAddNotional(builder, self.notional)
        CDSAddRunningCoupon(builder, self.runningCoupon)
        if self.schedule is not None:
            CDSAddSchedule(builder, schedule)
        CDSAddUpfront(builder, self.upfront)
        CDSAddDayCounter(builder, self.dayCounter)
        CDSAddBusinessDayConvention(builder, self.businessDayConvention)
        CDSAddSettlesAccrual(builder, self.settlesAccrual)
        CDSAddPaysAtDefaultTime(builder, self.paysAtDefaultTime)
        CDSAddRebatesAccrual(builder, self.rebatesAccrual)
        if self.protectionStart is not None:
            CDSAddProtectionStart(builder, protectionStart)
        if self.upfrontDate is not None:
            CDSAddUpfrontDate(builder, upfrontDate)
        CDSAddLastPeriodDayCounter(builder, self.lastPeriodDayCounter)
        if self.tradeDate is not None:
            CDSAddTradeDate(builder, tradeDate)
        CDSAddCashSettlementDays(builder, self.cashSettlementDays)
        cds = CDSEnd(builder)
        return cds
