# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CdsQuote(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CdsQuote()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCdsQuote(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CdsQuote
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CdsQuote
    def Tenor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Period import Period
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CdsQuote
    def QuoteType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CdsQuote
    def QuoteId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CdsQuote
    def QuotedParSpread(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CdsQuote
    def QuotedUpfront(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CdsQuote
    def RunningCoupon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CdsQuoteStart(builder):
    builder.StartObject(6)

def Start(builder):
    CdsQuoteStart(builder)

def CdsQuoteAddTenor(builder, tenor):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tenor), 0)

def AddTenor(builder, tenor):
    CdsQuoteAddTenor(builder, tenor)

def CdsQuoteAddQuoteType(builder, quoteType):
    builder.PrependInt8Slot(1, quoteType, 0)

def AddQuoteType(builder, quoteType):
    CdsQuoteAddQuoteType(builder, quoteType)

def CdsQuoteAddQuoteId(builder, quoteId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(quoteId), 0)

def AddQuoteId(builder, quoteId):
    CdsQuoteAddQuoteId(builder, quoteId)

def CdsQuoteAddQuotedParSpread(builder, quotedParSpread):
    builder.PrependFloat64Slot(3, quotedParSpread, 0.0)

def AddQuotedParSpread(builder, quotedParSpread):
    CdsQuoteAddQuotedParSpread(builder, quotedParSpread)

def CdsQuoteAddQuotedUpfront(builder, quotedUpfront):
    builder.PrependFloat64Slot(4, quotedUpfront, 0.0)

def AddQuotedUpfront(builder, quotedUpfront):
    CdsQuoteAddQuotedUpfront(builder, quotedUpfront)

def CdsQuoteAddRunningCoupon(builder, runningCoupon):
    builder.PrependFloat64Slot(5, runningCoupon, 0.0)

def AddRunningCoupon(builder, runningCoupon):
    CdsQuoteAddRunningCoupon(builder, runningCoupon)

def CdsQuoteEnd(builder):
    return builder.EndObject()

def End(builder):
    return CdsQuoteEnd(builder)

try:
    from typing import Optional
except:
    pass

class CdsQuoteT(object):

    # CdsQuoteT
    def __init__(self):
        self.tenor = None  # type: Optional[PeriodT]
        self.quoteType = 0  # type: int
        self.quoteId = None  # type: str
        self.quotedParSpread = 0.0  # type: float
        self.quotedUpfront = 0.0  # type: float
        self.runningCoupon = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cdsQuote = CdsQuote()
        cdsQuote.Init(buf, pos)
        return cls.InitFromObj(cdsQuote)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cdsQuote):
        x = CdsQuoteT()
        x._UnPack(cdsQuote)
        return x

    # CdsQuoteT
    def _UnPack(self, cdsQuote):
        if cdsQuote is None:
            return
        if cdsQuote.Tenor() is not None:
            self.tenor = PeriodT.InitFromObj(cdsQuote.Tenor())
        self.quoteType = cdsQuote.QuoteType()
        self.quoteId = cdsQuote.QuoteId()
        self.quotedParSpread = cdsQuote.QuotedParSpread()
        self.quotedUpfront = cdsQuote.QuotedUpfront()
        self.runningCoupon = cdsQuote.RunningCoupon()

    # CdsQuoteT
    def Pack(self, builder):
        if self.tenor is not None:
            tenor = self.tenor.Pack(builder)
        if self.quoteId is not None:
            quoteId = builder.CreateString(self.quoteId)
        CdsQuoteStart(builder)
        if self.tenor is not None:
            CdsQuoteAddTenor(builder, tenor)
        CdsQuoteAddQuoteType(builder, self.quoteType)
        if self.quoteId is not None:
            CdsQuoteAddQuoteId(builder, quoteId)
        CdsQuoteAddQuotedParSpread(builder, self.quotedParSpread)
        CdsQuoteAddQuotedUpfront(builder, self.quotedUpfront)
        CdsQuoteAddRunningCoupon(builder, self.runningCoupon)
        cdsQuote = CdsQuoteEnd(builder)
        return cdsQuote
