# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CurveRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CurveRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCurveRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CurveRef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CurveRef
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CurveRefStart(builder):
    builder.StartObject(1)

def Start(builder):
    CurveRefStart(builder)

def CurveRefAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    CurveRefAddId(builder, id)

def CurveRefEnd(builder):
    return builder.EndObject()

def End(builder):
    return CurveRefEnd(builder)


class CurveRefT(object):

    # CurveRefT
    def __init__(self):
        self.id = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        curveRef = CurveRef()
        curveRef.Init(buf, pos)
        return cls.InitFromObj(curveRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, curveRef):
        x = CurveRefT()
        x._UnPack(curveRef)
        return x

    # CurveRefT
    def _UnPack(self, curveRef):
        if curveRef is None:
            return
        self.id = curveRef.Id()

    # CurveRefT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        CurveRefStart(builder)
        if self.id is not None:
            CurveRefAddId(builder, id)
        curveRef = CurveRefEnd(builder)
        return curveRef
