# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Discrete cash dividend for equity underlyings.
class DiscreteDividend(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DiscreteDividend()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDiscreteDividend(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DiscreteDividend
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DiscreteDividend
    def ExDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DiscreteDividend
    def Amount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def DiscreteDividendStart(builder):
    builder.StartObject(2)

def Start(builder):
    DiscreteDividendStart(builder)

def DiscreteDividendAddExDate(builder, exDate):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(exDate), 0)

def AddExDate(builder, exDate):
    DiscreteDividendAddExDate(builder, exDate)

def DiscreteDividendAddAmount(builder, amount):
    builder.PrependFloat64Slot(1, amount, 0.0)

def AddAmount(builder, amount):
    DiscreteDividendAddAmount(builder, amount)

def DiscreteDividendEnd(builder):
    return builder.EndObject()

def End(builder):
    return DiscreteDividendEnd(builder)


class DiscreteDividendT(object):

    # DiscreteDividendT
    def __init__(self):
        self.exDate = None  # type: str
        self.amount = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        discreteDividend = DiscreteDividend()
        discreteDividend.Init(buf, pos)
        return cls.InitFromObj(discreteDividend)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, discreteDividend):
        x = DiscreteDividendT()
        x._UnPack(discreteDividend)
        return x

    # DiscreteDividendT
    def _UnPack(self, discreteDividend):
        if discreteDividend is None:
            return
        self.exDate = discreteDividend.ExDate()
        self.amount = discreteDividend.Amount()

    # DiscreteDividendT
    def Pack(self, builder):
        if self.exDate is not None:
            exDate = builder.CreateString(self.exDate)
        DiscreteDividendStart(builder)
        if self.exDate is not None:
            DiscreteDividendAddExDate(builder, exDate)
        DiscreteDividendAddAmount(builder, self.amount)
        discreteDividend = DiscreteDividendEnd(builder)
        return discreteDividend
