# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Optional barrier feature.
class EquityBarrierFeature(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EquityBarrierFeature()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEquityBarrierFeature(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EquityBarrierFeature
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EquityBarrierFeature
    def BarrierType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

    # EquityBarrierFeature
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EquityBarrierFeature
    def Rebate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EquityBarrierFeature
    def Monitoring(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # EquityBarrierFeature
    def MonitoringDates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # EquityBarrierFeature
    def MonitoringDatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EquityBarrierFeature
    def MonitoringDatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def EquityBarrierFeatureStart(builder):
    builder.StartObject(5)

def Start(builder):
    EquityBarrierFeatureStart(builder)

def EquityBarrierFeatureAddBarrierType(builder, barrierType):
    builder.PrependInt8Slot(0, barrierType, 2)

def AddBarrierType(builder, barrierType):
    EquityBarrierFeatureAddBarrierType(builder, barrierType)

def EquityBarrierFeatureAddLevel(builder, level):
    builder.PrependFloat64Slot(1, level, 0.0)

def AddLevel(builder, level):
    EquityBarrierFeatureAddLevel(builder, level)

def EquityBarrierFeatureAddRebate(builder, rebate):
    builder.PrependFloat64Slot(2, rebate, 0.0)

def AddRebate(builder, rebate):
    EquityBarrierFeatureAddRebate(builder, rebate)

def EquityBarrierFeatureAddMonitoring(builder, monitoring):
    builder.PrependInt8Slot(3, monitoring, 0)

def AddMonitoring(builder, monitoring):
    EquityBarrierFeatureAddMonitoring(builder, monitoring)

def EquityBarrierFeatureAddMonitoringDates(builder, monitoringDates):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(monitoringDates), 0)

def AddMonitoringDates(builder, monitoringDates):
    EquityBarrierFeatureAddMonitoringDates(builder, monitoringDates)

def EquityBarrierFeatureStartMonitoringDatesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMonitoringDatesVector(builder, numElems):
    return EquityBarrierFeatureStartMonitoringDatesVector(builder, numElems)

def EquityBarrierFeatureEnd(builder):
    return builder.EndObject()

def End(builder):
    return EquityBarrierFeatureEnd(builder)

try:
    from typing import List
except:
    pass

class EquityBarrierFeatureT(object):

    # EquityBarrierFeatureT
    def __init__(self):
        self.barrierType = 2  # type: int
        self.level = 0.0  # type: float
        self.rebate = 0.0  # type: float
        self.monitoring = 0  # type: int
        self.monitoringDates = None  # type: List[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        equityBarrierFeature = EquityBarrierFeature()
        equityBarrierFeature.Init(buf, pos)
        return cls.InitFromObj(equityBarrierFeature)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, equityBarrierFeature):
        x = EquityBarrierFeatureT()
        x._UnPack(equityBarrierFeature)
        return x

    # EquityBarrierFeatureT
    def _UnPack(self, equityBarrierFeature):
        if equityBarrierFeature is None:
            return
        self.barrierType = equityBarrierFeature.BarrierType()
        self.level = equityBarrierFeature.Level()
        self.rebate = equityBarrierFeature.Rebate()
        self.monitoring = equityBarrierFeature.Monitoring()
        if not equityBarrierFeature.MonitoringDatesIsNone():
            self.monitoringDates = []
            for i in range(equityBarrierFeature.MonitoringDatesLength()):
                self.monitoringDates.append(equityBarrierFeature.MonitoringDates(i))

    # EquityBarrierFeatureT
    def Pack(self, builder):
        if self.monitoringDates is not None:
            monitoringDateslist = []
            for i in range(len(self.monitoringDates)):
                monitoringDateslist.append(builder.CreateString(self.monitoringDates[i]))
            EquityBarrierFeatureStartMonitoringDatesVector(builder, len(self.monitoringDates))
            for i in reversed(range(len(self.monitoringDates))):
                builder.PrependUOffsetTRelative(monitoringDateslist[i])
            monitoringDates = builder.EndVector()
        EquityBarrierFeatureStart(builder)
        EquityBarrierFeatureAddBarrierType(builder, self.barrierType)
        EquityBarrierFeatureAddLevel(builder, self.level)
        EquityBarrierFeatureAddRebate(builder, self.rebate)
        EquityBarrierFeatureAddMonitoring(builder, self.monitoring)
        if self.monitoringDates is not None:
            EquityBarrierFeatureAddMonitoringDates(builder, monitoringDates)
        equityBarrierFeature = EquityBarrierFeatureEnd(builder)
        return equityBarrierFeature
