# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IndexFixings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IndexFixings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIndexFixings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IndexFixings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IndexFixings
    def IndexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IndexFixings
    def Fixings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.Fixing import Fixing
            obj = Fixing()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndexFixings
    def FixingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFixings
    def FixingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def IndexFixingsStart(builder):
    builder.StartObject(2)

def Start(builder):
    IndexFixingsStart(builder)

def IndexFixingsAddIndexId(builder, indexId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(indexId), 0)

def AddIndexId(builder, indexId):
    IndexFixingsAddIndexId(builder, indexId)

def IndexFixingsAddFixings(builder, fixings):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fixings), 0)

def AddFixings(builder, fixings):
    IndexFixingsAddFixings(builder, fixings)

def IndexFixingsStartFixingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFixingsVector(builder, numElems):
    return IndexFixingsStartFixingsVector(builder, numElems)

def IndexFixingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return IndexFixingsEnd(builder)

try:
    from typing import List
except:
    pass

class IndexFixingsT(object):

    # IndexFixingsT
    def __init__(self):
        self.indexId = None  # type: str
        self.fixings = None  # type: List[FixingT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        indexFixings = IndexFixings()
        indexFixings.Init(buf, pos)
        return cls.InitFromObj(indexFixings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, indexFixings):
        x = IndexFixingsT()
        x._UnPack(indexFixings)
        return x

    # IndexFixingsT
    def _UnPack(self, indexFixings):
        if indexFixings is None:
            return
        self.indexId = indexFixings.IndexId()
        if not indexFixings.FixingsIsNone():
            self.fixings = []
            for i in range(indexFixings.FixingsLength()):
                if indexFixings.Fixings(i) is None:
                    self.fixings.append(None)
                else:
                    fixing_ = FixingT.InitFromObj(indexFixings.Fixings(i))
                    self.fixings.append(fixing_)

    # IndexFixingsT
    def Pack(self, builder):
        if self.indexId is not None:
            indexId = builder.CreateString(self.indexId)
        if self.fixings is not None:
            fixingslist = []
            for i in range(len(self.fixings)):
                fixingslist.append(self.fixings[i].Pack(builder))
            IndexFixingsStartFixingsVector(builder, len(self.fixings))
            for i in reversed(range(len(self.fixings))):
                builder.PrependUOffsetTRelative(fixingslist[i])
            fixings = builder.EndVector()
        IndexFixingsStart(builder)
        if self.indexId is not None:
            IndexFixingsAddIndexId(builder, indexId)
        if self.fixings is not None:
            IndexFixingsAddFixings(builder, fixings)
        indexFixings = IndexFixingsEnd(builder)
        return indexFixings
