# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Inflation index specification. Registered once per request, referenced by id.
class InflationIndexSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InflationIndexSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInflationIndexSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InflationIndexSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Unique identifier (e.g., "UKRPI", "EUHICP", "USCPI").
    # InflationIndexSpec
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Human-readable family name.
    # InflationIndexSpec
    def FamilyName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ISO currency code (e.g., "GBP", "EUR", "USD").
    # InflationIndexSpec
    def Currency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InflationIndexSpec
    def Calendar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 32

    # InflationIndexSpec
    def DayCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

    # InflationIndexSpec
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 6

    # Publication availability lag (e.g., 2 Months).
    # InflationIndexSpec
    def AvailabilityLag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Period import Period
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Observation lag used for swaps (e.g., 3 Months).
    # InflationIndexSpec
    def ObservationLag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Whether the index is interpolated between fixings.
    # InflationIndexSpec
    def Interpolated(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # Whether index values can be revised (rare; defaults to false).
    # InflationIndexSpec
    def Revised(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InflationIndexSpec
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # For ratio-based YoY indices, link to the underlying zero inflation index id.
    # InflationIndexSpec
    def UnderlyingZeroIndexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Historical CPI/YoY fixings needed for helper-based bootstrap and forecasting.
    # InflationIndexSpec
    def Fixings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.Fixing import Fixing
            obj = Fixing()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InflationIndexSpec
    def FixingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InflationIndexSpec
    def FixingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

def InflationIndexSpecStart(builder):
    builder.StartObject(13)

def Start(builder):
    InflationIndexSpecStart(builder)

def InflationIndexSpecAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    InflationIndexSpecAddId(builder, id)

def InflationIndexSpecAddFamilyName(builder, familyName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(familyName), 0)

def AddFamilyName(builder, familyName):
    InflationIndexSpecAddFamilyName(builder, familyName)

def InflationIndexSpecAddCurrency(builder, currency):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(currency), 0)

def AddCurrency(builder, currency):
    InflationIndexSpecAddCurrency(builder, currency)

def InflationIndexSpecAddCalendar(builder, calendar):
    builder.PrependInt8Slot(3, calendar, 32)

def AddCalendar(builder, calendar):
    InflationIndexSpecAddCalendar(builder, calendar)

def InflationIndexSpecAddDayCounter(builder, dayCounter):
    builder.PrependInt8Slot(4, dayCounter, 1)

def AddDayCounter(builder, dayCounter):
    InflationIndexSpecAddDayCounter(builder, dayCounter)

def InflationIndexSpecAddFrequency(builder, frequency):
    builder.PrependInt8Slot(5, frequency, 6)

def AddFrequency(builder, frequency):
    InflationIndexSpecAddFrequency(builder, frequency)

def InflationIndexSpecAddAvailabilityLag(builder, availabilityLag):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(availabilityLag), 0)

def AddAvailabilityLag(builder, availabilityLag):
    InflationIndexSpecAddAvailabilityLag(builder, availabilityLag)

def InflationIndexSpecAddObservationLag(builder, observationLag):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(observationLag), 0)

def AddObservationLag(builder, observationLag):
    InflationIndexSpecAddObservationLag(builder, observationLag)

def InflationIndexSpecAddInterpolated(builder, interpolated):
    builder.PrependBoolSlot(8, interpolated, 1)

def AddInterpolated(builder, interpolated):
    InflationIndexSpecAddInterpolated(builder, interpolated)

def InflationIndexSpecAddRevised(builder, revised):
    builder.PrependBoolSlot(9, revised, 0)

def AddRevised(builder, revised):
    InflationIndexSpecAddRevised(builder, revised)

def InflationIndexSpecAddKind(builder, kind):
    builder.PrependInt8Slot(10, kind, 0)

def AddKind(builder, kind):
    InflationIndexSpecAddKind(builder, kind)

def InflationIndexSpecAddUnderlyingZeroIndexId(builder, underlyingZeroIndexId):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(underlyingZeroIndexId), 0)

def AddUnderlyingZeroIndexId(builder, underlyingZeroIndexId):
    InflationIndexSpecAddUnderlyingZeroIndexId(builder, underlyingZeroIndexId)

def InflationIndexSpecAddFixings(builder, fixings):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(fixings), 0)

def AddFixings(builder, fixings):
    InflationIndexSpecAddFixings(builder, fixings)

def InflationIndexSpecStartFixingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFixingsVector(builder, numElems):
    return InflationIndexSpecStartFixingsVector(builder, numElems)

def InflationIndexSpecEnd(builder):
    return builder.EndObject()

def End(builder):
    return InflationIndexSpecEnd(builder)

try:
    from typing import List, Optional
except:
    pass

class InflationIndexSpecT(object):

    # InflationIndexSpecT
    def __init__(self):
        self.id = None  # type: str
        self.familyName = None  # type: str
        self.currency = None  # type: str
        self.calendar = 32  # type: int
        self.dayCounter = 1  # type: int
        self.frequency = 6  # type: int
        self.availabilityLag = None  # type: Optional[PeriodT]
        self.observationLag = None  # type: Optional[PeriodT]
        self.interpolated = True  # type: bool
        self.revised = False  # type: bool
        self.kind = 0  # type: int
        self.underlyingZeroIndexId = None  # type: str
        self.fixings = None  # type: List[FixingT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        inflationIndexSpec = InflationIndexSpec()
        inflationIndexSpec.Init(buf, pos)
        return cls.InitFromObj(inflationIndexSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, inflationIndexSpec):
        x = InflationIndexSpecT()
        x._UnPack(inflationIndexSpec)
        return x

    # InflationIndexSpecT
    def _UnPack(self, inflationIndexSpec):
        if inflationIndexSpec is None:
            return
        self.id = inflationIndexSpec.Id()
        self.familyName = inflationIndexSpec.FamilyName()
        self.currency = inflationIndexSpec.Currency()
        self.calendar = inflationIndexSpec.Calendar()
        self.dayCounter = inflationIndexSpec.DayCounter()
        self.frequency = inflationIndexSpec.Frequency()
        if inflationIndexSpec.AvailabilityLag() is not None:
            self.availabilityLag = PeriodT.InitFromObj(inflationIndexSpec.AvailabilityLag())
        if inflationIndexSpec.ObservationLag() is not None:
            self.observationLag = PeriodT.InitFromObj(inflationIndexSpec.ObservationLag())
        self.interpolated = inflationIndexSpec.Interpolated()
        self.revised = inflationIndexSpec.Revised()
        self.kind = inflationIndexSpec.Kind()
        self.underlyingZeroIndexId = inflationIndexSpec.UnderlyingZeroIndexId()
        if not inflationIndexSpec.FixingsIsNone():
            self.fixings = []
            for i in range(inflationIndexSpec.FixingsLength()):
                if inflationIndexSpec.Fixings(i) is None:
                    self.fixings.append(None)
                else:
                    fixing_ = FixingT.InitFromObj(inflationIndexSpec.Fixings(i))
                    self.fixings.append(fixing_)

    # InflationIndexSpecT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.familyName is not None:
            familyName = builder.CreateString(self.familyName)
        if self.currency is not None:
            currency = builder.CreateString(self.currency)
        if self.availabilityLag is not None:
            availabilityLag = self.availabilityLag.Pack(builder)
        if self.observationLag is not None:
            observationLag = self.observationLag.Pack(builder)
        if self.underlyingZeroIndexId is not None:
            underlyingZeroIndexId = builder.CreateString(self.underlyingZeroIndexId)
        if self.fixings is not None:
            fixingslist = []
            for i in range(len(self.fixings)):
                fixingslist.append(self.fixings[i].Pack(builder))
            InflationIndexSpecStartFixingsVector(builder, len(self.fixings))
            for i in reversed(range(len(self.fixings))):
                builder.PrependUOffsetTRelative(fixingslist[i])
            fixings = builder.EndVector()
        InflationIndexSpecStart(builder)
        if self.id is not None:
            InflationIndexSpecAddId(builder, id)
        if self.familyName is not None:
            InflationIndexSpecAddFamilyName(builder, familyName)
        if self.currency is not None:
            InflationIndexSpecAddCurrency(builder, currency)
        InflationIndexSpecAddCalendar(builder, self.calendar)
        InflationIndexSpecAddDayCounter(builder, self.dayCounter)
        InflationIndexSpecAddFrequency(builder, self.frequency)
        if self.availabilityLag is not None:
            InflationIndexSpecAddAvailabilityLag(builder, availabilityLag)
        if self.observationLag is not None:
            InflationIndexSpecAddObservationLag(builder, observationLag)
        InflationIndexSpecAddInterpolated(builder, self.interpolated)
        InflationIndexSpecAddRevised(builder, self.revised)
        InflationIndexSpecAddKind(builder, self.kind)
        if self.underlyingZeroIndexId is not None:
            InflationIndexSpecAddUnderlyingZeroIndexId(builder, underlyingZeroIndexId)
        if self.fixings is not None:
            InflationIndexSpecAddFixings(builder, fixings)
        inflationIndexSpec = InflationIndexSpecEnd(builder)
        return inflationIndexSpec
