# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OisFloatingLeg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OisFloatingLeg()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOisFloatingLeg(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OisFloatingLeg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OisFloatingLeg
    def Schedule(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Schedule import Schedule
            obj = Schedule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OisFloatingLeg
    def Notional(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Reference to an overnight IndexDef by id (e.g., "USD_SOFR")
    # OisFloatingLeg
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.IndexRef import IndexRef
            obj = IndexRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OisFloatingLeg
    def Spread(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # OisFloatingLeg
    def DayCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # OisFloatingLeg
    def PaymentConvention(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Payment adjustments
    # OisFloatingLeg
    def PaymentCalendar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 32

    # OisFloatingLeg
    def PaymentLag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Overnight accrual conventions
    # OisFloatingLeg
    def AveragingMethod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # OisFloatingLeg
    def LookbackDays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # OisFloatingLeg
    def LockoutDays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OisFloatingLeg
    def ApplyObservationShift(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OisFloatingLeg
    def TelescopicValueDates(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def OisFloatingLegStart(builder):
    builder.StartObject(13)

def Start(builder):
    OisFloatingLegStart(builder)

def OisFloatingLegAddSchedule(builder, schedule):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schedule), 0)

def AddSchedule(builder, schedule):
    OisFloatingLegAddSchedule(builder, schedule)

def OisFloatingLegAddNotional(builder, notional):
    builder.PrependFloat64Slot(1, notional, 0.0)

def AddNotional(builder, notional):
    OisFloatingLegAddNotional(builder, notional)

def OisFloatingLegAddIndex(builder, index):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(index), 0)

def AddIndex(builder, index):
    OisFloatingLegAddIndex(builder, index)

def OisFloatingLegAddSpread(builder, spread):
    builder.PrependFloat64Slot(3, spread, 0.0)

def AddSpread(builder, spread):
    OisFloatingLegAddSpread(builder, spread)

def OisFloatingLegAddDayCounter(builder, dayCounter):
    builder.PrependInt8Slot(4, dayCounter, 0)

def AddDayCounter(builder, dayCounter):
    OisFloatingLegAddDayCounter(builder, dayCounter)

def OisFloatingLegAddPaymentConvention(builder, paymentConvention):
    builder.PrependInt8Slot(5, paymentConvention, 0)

def AddPaymentConvention(builder, paymentConvention):
    OisFloatingLegAddPaymentConvention(builder, paymentConvention)

def OisFloatingLegAddPaymentCalendar(builder, paymentCalendar):
    builder.PrependInt8Slot(6, paymentCalendar, 32)

def AddPaymentCalendar(builder, paymentCalendar):
    OisFloatingLegAddPaymentCalendar(builder, paymentCalendar)

def OisFloatingLegAddPaymentLag(builder, paymentLag):
    builder.PrependInt32Slot(7, paymentLag, 0)

def AddPaymentLag(builder, paymentLag):
    OisFloatingLegAddPaymentLag(builder, paymentLag)

def OisFloatingLegAddAveragingMethod(builder, averagingMethod):
    builder.PrependInt8Slot(8, averagingMethod, 0)

def AddAveragingMethod(builder, averagingMethod):
    OisFloatingLegAddAveragingMethod(builder, averagingMethod)

def OisFloatingLegAddLookbackDays(builder, lookbackDays):
    builder.PrependInt32Slot(9, lookbackDays, -1)

def AddLookbackDays(builder, lookbackDays):
    OisFloatingLegAddLookbackDays(builder, lookbackDays)

def OisFloatingLegAddLockoutDays(builder, lockoutDays):
    builder.PrependInt32Slot(10, lockoutDays, 0)

def AddLockoutDays(builder, lockoutDays):
    OisFloatingLegAddLockoutDays(builder, lockoutDays)

def OisFloatingLegAddApplyObservationShift(builder, applyObservationShift):
    builder.PrependBoolSlot(11, applyObservationShift, 0)

def AddApplyObservationShift(builder, applyObservationShift):
    OisFloatingLegAddApplyObservationShift(builder, applyObservationShift)

def OisFloatingLegAddTelescopicValueDates(builder, telescopicValueDates):
    builder.PrependBoolSlot(12, telescopicValueDates, 0)

def AddTelescopicValueDates(builder, telescopicValueDates):
    OisFloatingLegAddTelescopicValueDates(builder, telescopicValueDates)

def OisFloatingLegEnd(builder):
    return builder.EndObject()

def End(builder):
    return OisFloatingLegEnd(builder)

try:
    from typing import Optional
except:
    pass

class OisFloatingLegT(object):

    # OisFloatingLegT
    def __init__(self):
        self.schedule = None  # type: Optional[ScheduleT]
        self.notional = 0.0  # type: float
        self.index = None  # type: Optional[IndexRefT]
        self.spread = 0.0  # type: float
        self.dayCounter = 0  # type: int
        self.paymentConvention = 0  # type: int
        self.paymentCalendar = 32  # type: int
        self.paymentLag = 0  # type: int
        self.averagingMethod = 0  # type: int
        self.lookbackDays = -1  # type: int
        self.lockoutDays = 0  # type: int
        self.applyObservationShift = False  # type: bool
        self.telescopicValueDates = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        oisFloatingLeg = OisFloatingLeg()
        oisFloatingLeg.Init(buf, pos)
        return cls.InitFromObj(oisFloatingLeg)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, oisFloatingLeg):
        x = OisFloatingLegT()
        x._UnPack(oisFloatingLeg)
        return x

    # OisFloatingLegT
    def _UnPack(self, oisFloatingLeg):
        if oisFloatingLeg is None:
            return
        if oisFloatingLeg.Schedule() is not None:
            self.schedule = ScheduleT.InitFromObj(oisFloatingLeg.Schedule())
        self.notional = oisFloatingLeg.Notional()
        if oisFloatingLeg.Index() is not None:
            self.index = IndexRefT.InitFromObj(oisFloatingLeg.Index())
        self.spread = oisFloatingLeg.Spread()
        self.dayCounter = oisFloatingLeg.DayCounter()
        self.paymentConvention = oisFloatingLeg.PaymentConvention()
        self.paymentCalendar = oisFloatingLeg.PaymentCalendar()
        self.paymentLag = oisFloatingLeg.PaymentLag()
        self.averagingMethod = oisFloatingLeg.AveragingMethod()
        self.lookbackDays = oisFloatingLeg.LookbackDays()
        self.lockoutDays = oisFloatingLeg.LockoutDays()
        self.applyObservationShift = oisFloatingLeg.ApplyObservationShift()
        self.telescopicValueDates = oisFloatingLeg.TelescopicValueDates()

    # OisFloatingLegT
    def Pack(self, builder):
        if self.schedule is not None:
            schedule = self.schedule.Pack(builder)
        if self.index is not None:
            index = self.index.Pack(builder)
        OisFloatingLegStart(builder)
        if self.schedule is not None:
            OisFloatingLegAddSchedule(builder, schedule)
        OisFloatingLegAddNotional(builder, self.notional)
        if self.index is not None:
            OisFloatingLegAddIndex(builder, index)
        OisFloatingLegAddSpread(builder, self.spread)
        OisFloatingLegAddDayCounter(builder, self.dayCounter)
        OisFloatingLegAddPaymentConvention(builder, self.paymentConvention)
        OisFloatingLegAddPaymentCalendar(builder, self.paymentCalendar)
        OisFloatingLegAddPaymentLag(builder, self.paymentLag)
        OisFloatingLegAddAveragingMethod(builder, self.averagingMethod)
        OisFloatingLegAddLookbackDays(builder, self.lookbackDays)
        OisFloatingLegAddLockoutDays(builder, self.lockoutDays)
        OisFloatingLegAddApplyObservationShift(builder, self.applyObservationShift)
        OisFloatingLegAddTelescopicValueDates(builder, self.telescopicValueDates)
        oisFloatingLeg = OisFloatingLegEnd(builder)
        return oisFloatingLeg
