# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PeriodSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PeriodSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPeriodSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PeriodSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PeriodSpec
    def TenorNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PeriodSpec
    def TenorTimeUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def PeriodSpecStart(builder):
    builder.StartObject(2)

def Start(builder):
    PeriodSpecStart(builder)

def PeriodSpecAddTenorNumber(builder, tenorNumber):
    builder.PrependInt32Slot(0, tenorNumber, 0)

def AddTenorNumber(builder, tenorNumber):
    PeriodSpecAddTenorNumber(builder, tenorNumber)

def PeriodSpecAddTenorTimeUnit(builder, tenorTimeUnit):
    builder.PrependInt8Slot(1, tenorTimeUnit, 0)

def AddTenorTimeUnit(builder, tenorTimeUnit):
    PeriodSpecAddTenorTimeUnit(builder, tenorTimeUnit)

def PeriodSpecEnd(builder):
    return builder.EndObject()

def End(builder):
    return PeriodSpecEnd(builder)


class PeriodSpecT(object):

    # PeriodSpecT
    def __init__(self):
        self.tenorNumber = 0  # type: int
        self.tenorTimeUnit = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        periodSpec = PeriodSpec()
        periodSpec.Init(buf, pos)
        return cls.InitFromObj(periodSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, periodSpec):
        x = PeriodSpecT()
        x._UnPack(periodSpec)
        return x

    # PeriodSpecT
    def _UnPack(self, periodSpec):
        if periodSpec is None:
            return
        self.tenorNumber = periodSpec.TenorNumber()
        self.tenorTimeUnit = periodSpec.TenorTimeUnit()

    # PeriodSpecT
    def Pack(self, builder):
        PeriodSpecStart(builder)
        PeriodSpecAddTenorNumber(builder, self.tenorNumber)
        PeriodSpecAddTenorTimeUnit(builder, self.tenorTimeUnit)
        periodSpec = PeriodSpecEnd(builder)
        return periodSpec
