# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PriceCDSRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PriceCDSRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPriceCDSRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PriceCDSRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PriceCDSRequest
    def Pricing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Pricing import Pricing
            obj = Pricing()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PriceCDSRequest
    def CdsList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.PriceCDS import PriceCDS
            obj = PriceCDS()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PriceCDSRequest
    def CdsListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PriceCDSRequest
    def CdsListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PriceCDSRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    PriceCDSRequestStart(builder)

def PriceCDSRequestAddPricing(builder, pricing):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pricing), 0)

def AddPricing(builder, pricing):
    PriceCDSRequestAddPricing(builder, pricing)

def PriceCDSRequestAddCdsList(builder, cdsList):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cdsList), 0)

def AddCdsList(builder, cdsList):
    PriceCDSRequestAddCdsList(builder, cdsList)

def PriceCDSRequestStartCdsListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCdsListVector(builder, numElems):
    return PriceCDSRequestStartCdsListVector(builder, numElems)

def PriceCDSRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return PriceCDSRequestEnd(builder)

try:
    from typing import List, Optional
except:
    pass

class PriceCDSRequestT(object):

    # PriceCDSRequestT
    def __init__(self):
        self.pricing = None  # type: Optional[PricingT]
        self.cdsList = None  # type: List[PriceCDST]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        priceCdsrequest = PriceCDSRequest()
        priceCdsrequest.Init(buf, pos)
        return cls.InitFromObj(priceCdsrequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, priceCdsrequest):
        x = PriceCDSRequestT()
        x._UnPack(priceCdsrequest)
        return x

    # PriceCDSRequestT
    def _UnPack(self, priceCdsrequest):
        if priceCdsrequest is None:
            return
        if priceCdsrequest.Pricing() is not None:
            self.pricing = PricingT.InitFromObj(priceCdsrequest.Pricing())
        if not priceCdsrequest.CdsListIsNone():
            self.cdsList = []
            for i in range(priceCdsrequest.CdsListLength()):
                if priceCdsrequest.CdsList(i) is None:
                    self.cdsList.append(None)
                else:
                    priceCDS_ = PriceCDST.InitFromObj(priceCdsrequest.CdsList(i))
                    self.cdsList.append(priceCDS_)

    # PriceCDSRequestT
    def Pack(self, builder):
        if self.pricing is not None:
            pricing = self.pricing.Pack(builder)
        if self.cdsList is not None:
            cdsListlist = []
            for i in range(len(self.cdsList)):
                cdsListlist.append(self.cdsList[i].Pack(builder))
            PriceCDSRequestStartCdsListVector(builder, len(self.cdsList))
            for i in reversed(range(len(self.cdsList))):
                builder.PrependUOffsetTRelative(cdsListlist[i])
            cdsList = builder.EndVector()
        PriceCDSRequestStart(builder)
        if self.pricing is not None:
            PriceCDSRequestAddPricing(builder, pricing)
        if self.cdsList is not None:
            PriceCDSRequestAddCdsList(builder, cdsList)
        priceCdsrequest = PriceCDSRequestEnd(builder)
        return priceCdsrequest
