# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Response wrapper for multiple ZCIIS trades.
class PriceZeroCouponInflationSwapResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PriceZeroCouponInflationSwapResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPriceZeroCouponInflationSwapResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PriceZeroCouponInflationSwapResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PriceZeroCouponInflationSwapResponse
    def Swaps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.ZeroCouponInflationSwapResponse import ZeroCouponInflationSwapResponse
            obj = ZeroCouponInflationSwapResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PriceZeroCouponInflationSwapResponse
    def SwapsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PriceZeroCouponInflationSwapResponse
    def SwapsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PriceZeroCouponInflationSwapResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    PriceZeroCouponInflationSwapResponseStart(builder)

def PriceZeroCouponInflationSwapResponseAddSwaps(builder, swaps):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(swaps), 0)

def AddSwaps(builder, swaps):
    PriceZeroCouponInflationSwapResponseAddSwaps(builder, swaps)

def PriceZeroCouponInflationSwapResponseStartSwapsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSwapsVector(builder, numElems):
    return PriceZeroCouponInflationSwapResponseStartSwapsVector(builder, numElems)

def PriceZeroCouponInflationSwapResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return PriceZeroCouponInflationSwapResponseEnd(builder)

try:
    from typing import List
except:
    pass

class PriceZeroCouponInflationSwapResponseT(object):

    # PriceZeroCouponInflationSwapResponseT
    def __init__(self):
        self.swaps = None  # type: List[ZeroCouponInflationSwapResponseT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        priceZeroCouponInflationSwapResponse = PriceZeroCouponInflationSwapResponse()
        priceZeroCouponInflationSwapResponse.Init(buf, pos)
        return cls.InitFromObj(priceZeroCouponInflationSwapResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, priceZeroCouponInflationSwapResponse):
        x = PriceZeroCouponInflationSwapResponseT()
        x._UnPack(priceZeroCouponInflationSwapResponse)
        return x

    # PriceZeroCouponInflationSwapResponseT
    def _UnPack(self, priceZeroCouponInflationSwapResponse):
        if priceZeroCouponInflationSwapResponse is None:
            return
        if not priceZeroCouponInflationSwapResponse.SwapsIsNone():
            self.swaps = []
            for i in range(priceZeroCouponInflationSwapResponse.SwapsLength()):
                if priceZeroCouponInflationSwapResponse.Swaps(i) is None:
                    self.swaps.append(None)
                else:
                    zeroCouponInflationSwapResponse_ = ZeroCouponInflationSwapResponseT.InitFromObj(priceZeroCouponInflationSwapResponse.Swaps(i))
                    self.swaps.append(zeroCouponInflationSwapResponse_)

    # PriceZeroCouponInflationSwapResponseT
    def Pack(self, builder):
        if self.swaps is not None:
            swapslist = []
            for i in range(len(self.swaps)):
                swapslist.append(self.swaps[i].Pack(builder))
            PriceZeroCouponInflationSwapResponseStartSwapsVector(builder, len(self.swaps))
            for i in reversed(range(len(self.swaps))):
                builder.PrependUOffsetTRelative(swapslist[i])
            swaps = builder.EndVector()
        PriceZeroCouponInflationSwapResponseStart(builder)
        if self.swaps is not None:
            PriceZeroCouponInflationSwapResponseAddSwaps(builder, swaps)
        priceZeroCouponInflationSwapResponse = PriceZeroCouponInflationSwapResponseEnd(builder)
        return priceZeroCouponInflationSwapResponse
