# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PriceFRAResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PriceFRAResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPriceFRAResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PriceFRAResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PriceFRAResponse
    def Fras(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FRAResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PriceFRAResponse
    def FrasLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PriceFRAResponse
    def FrasIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PriceFRAResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    PriceFRAResponseStart(builder)

def PriceFRAResponseAddFras(builder, fras):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(fras), 0)

def AddFras(builder, fras):
    PriceFRAResponseAddFras(builder, fras)

def PriceFRAResponseStartFrasVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFrasVector(builder, numElems):
    return PriceFRAResponseStartFrasVector(builder, numElems)

def PriceFRAResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return PriceFRAResponseEnd(builder)

try:
    from typing import List
except:
    pass

class PriceFRAResponseT(object):

    # PriceFRAResponseT
    def __init__(self):
        self.fras = None  # type: List[FRAResponseT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        priceFraresponse = PriceFRAResponse()
        priceFraresponse.Init(buf, pos)
        return cls.InitFromObj(priceFraresponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, priceFraresponse):
        x = PriceFRAResponseT()
        x._UnPack(priceFraresponse)
        return x

    # PriceFRAResponseT
    def _UnPack(self, priceFraresponse):
        if priceFraresponse is None:
            return
        if not priceFraresponse.FrasIsNone():
            self.fras = []
            for i in range(priceFraresponse.FrasLength()):
                if priceFraresponse.Fras(i) is None:
                    self.fras.append(None)
                else:
                    fRAResponse_ = FRAResponseT.InitFromObj(priceFraresponse.Fras(i))
                    self.fras.append(fRAResponse_)

    # PriceFRAResponseT
    def Pack(self, builder):
        if self.fras is not None:
            fraslist = []
            for i in range(len(self.fras)):
                fraslist.append(self.fras[i].Pack(builder))
            PriceFRAResponseStartFrasVector(builder, len(self.fras))
            for i in reversed(range(len(self.fras))):
                builder.PrependUOffsetTRelative(fraslist[i])
            fras = builder.EndVector()
        PriceFRAResponseStart(builder)
        if self.fras is not None:
            PriceFRAResponseAddFras(builder, fras)
        priceFraresponse = PriceFRAResponseEnd(builder)
        return priceFraresponse
