# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PriceCapFloorResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PriceCapFloorResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPriceCapFloorResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PriceCapFloorResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PriceCapFloorResponse
    def CapFloors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.CapFloorResponse import CapFloorResponse
            obj = CapFloorResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PriceCapFloorResponse
    def CapFloorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PriceCapFloorResponse
    def CapFloorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PriceCapFloorResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    PriceCapFloorResponseStart(builder)

def PriceCapFloorResponseAddCapFloors(builder, capFloors):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(capFloors), 0)

def AddCapFloors(builder, capFloors):
    PriceCapFloorResponseAddCapFloors(builder, capFloors)

def PriceCapFloorResponseStartCapFloorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCapFloorsVector(builder, numElems):
    return PriceCapFloorResponseStartCapFloorsVector(builder, numElems)

def PriceCapFloorResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return PriceCapFloorResponseEnd(builder)

try:
    from typing import List
except:
    pass

class PriceCapFloorResponseT(object):

    # PriceCapFloorResponseT
    def __init__(self):
        self.capFloors = None  # type: List[CapFloorResponseT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        priceCapFloorResponse = PriceCapFloorResponse()
        priceCapFloorResponse.Init(buf, pos)
        return cls.InitFromObj(priceCapFloorResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, priceCapFloorResponse):
        x = PriceCapFloorResponseT()
        x._UnPack(priceCapFloorResponse)
        return x

    # PriceCapFloorResponseT
    def _UnPack(self, priceCapFloorResponse):
        if priceCapFloorResponse is None:
            return
        if not priceCapFloorResponse.CapFloorsIsNone():
            self.capFloors = []
            for i in range(priceCapFloorResponse.CapFloorsLength()):
                if priceCapFloorResponse.CapFloors(i) is None:
                    self.capFloors.append(None)
                else:
                    capFloorResponse_ = CapFloorResponseT.InitFromObj(priceCapFloorResponse.CapFloors(i))
                    self.capFloors.append(capFloorResponse_)

    # PriceCapFloorResponseT
    def Pack(self, builder):
        if self.capFloors is not None:
            capFloorslist = []
            for i in range(len(self.capFloors)):
                capFloorslist.append(self.capFloors[i].Pack(builder))
            PriceCapFloorResponseStartCapFloorsVector(builder, len(self.capFloors))
            for i in reversed(range(len(self.capFloors))):
                builder.PrependUOffsetTRelative(capFloorslist[i])
            capFloors = builder.EndVector()
        PriceCapFloorResponseStart(builder)
        if self.capFloors is not None:
            PriceCapFloorResponseAddCapFloors(builder, capFloors)
        priceCapFloorResponse = PriceCapFloorResponseEnd(builder)
        return priceCapFloorResponse
