# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PriceOisSwap(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PriceOisSwap()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPriceOisSwap(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PriceOisSwap
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PriceOisSwap
    def OisSwap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.OisSwap import OisSwap
            obj = OisSwap()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PriceOisSwap
    def DiscountingCurve(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PriceOisSwap
    def ForwardingCurve(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PriceOisSwapStart(builder):
    builder.StartObject(3)

def Start(builder):
    PriceOisSwapStart(builder)

def PriceOisSwapAddOisSwap(builder, oisSwap):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(oisSwap), 0)

def AddOisSwap(builder, oisSwap):
    PriceOisSwapAddOisSwap(builder, oisSwap)

def PriceOisSwapAddDiscountingCurve(builder, discountingCurve):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(discountingCurve), 0)

def AddDiscountingCurve(builder, discountingCurve):
    PriceOisSwapAddDiscountingCurve(builder, discountingCurve)

def PriceOisSwapAddForwardingCurve(builder, forwardingCurve):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(forwardingCurve), 0)

def AddForwardingCurve(builder, forwardingCurve):
    PriceOisSwapAddForwardingCurve(builder, forwardingCurve)

def PriceOisSwapEnd(builder):
    return builder.EndObject()

def End(builder):
    return PriceOisSwapEnd(builder)

try:
    from typing import Optional
except:
    pass

class PriceOisSwapT(object):

    # PriceOisSwapT
    def __init__(self):
        self.oisSwap = None  # type: Optional[OisSwapT]
        self.discountingCurve = None  # type: str
        self.forwardingCurve = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        priceOisSwap = PriceOisSwap()
        priceOisSwap.Init(buf, pos)
        return cls.InitFromObj(priceOisSwap)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, priceOisSwap):
        x = PriceOisSwapT()
        x._UnPack(priceOisSwap)
        return x

    # PriceOisSwapT
    def _UnPack(self, priceOisSwap):
        if priceOisSwap is None:
            return
        if priceOisSwap.OisSwap() is not None:
            self.oisSwap = OisSwapT.InitFromObj(priceOisSwap.OisSwap())
        self.discountingCurve = priceOisSwap.DiscountingCurve()
        self.forwardingCurve = priceOisSwap.ForwardingCurve()

    # PriceOisSwapT
    def Pack(self, builder):
        if self.oisSwap is not None:
            oisSwap = self.oisSwap.Pack(builder)
        if self.discountingCurve is not None:
            discountingCurve = builder.CreateString(self.discountingCurve)
        if self.forwardingCurve is not None:
            forwardingCurve = builder.CreateString(self.forwardingCurve)
        PriceOisSwapStart(builder)
        if self.oisSwap is not None:
            PriceOisSwapAddOisSwap(builder, oisSwap)
        if self.discountingCurve is not None:
            PriceOisSwapAddDiscountingCurve(builder, discountingCurve)
        if self.forwardingCurve is not None:
            PriceOisSwapAddForwardingCurve(builder, forwardingCurve)
        priceOisSwap = PriceOisSwapEnd(builder)
        return priceOisSwap
