# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Market quote (spot price, FX rate, etc.)
# Used by: EquityOption (future)
class QuoteSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuoteSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuoteSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuoteSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuoteSpec
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # QuoteSpec
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def QuoteSpecStart(builder):
    builder.StartObject(2)

def Start(builder):
    QuoteSpecStart(builder)

def QuoteSpecAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    QuoteSpecAddId(builder, id)

def QuoteSpecAddValue(builder, value):
    builder.PrependFloat64Slot(1, value, 0.0)

def AddValue(builder, value):
    QuoteSpecAddValue(builder, value)

def QuoteSpecEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuoteSpecEnd(builder)


class QuoteSpecT(object):

    # QuoteSpecT
    def __init__(self):
        self.id = None  # type: str
        self.value = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        quoteSpec = QuoteSpec()
        quoteSpec.Init(buf, pos)
        return cls.InitFromObj(quoteSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, quoteSpec):
        x = QuoteSpecT()
        x._UnPack(quoteSpec)
        return x

    # QuoteSpecT
    def _UnPack(self, quoteSpec):
        if quoteSpec is None:
            return
        self.id = quoteSpec.Id()
        self.value = quoteSpec.Value()

    # QuoteSpecT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        QuoteSpecStart(builder)
        if self.id is not None:
            QuoteSpecAddId(builder, id)
        QuoteSpecAddValue(builder, self.value)
        quoteSpec = QuoteSpecEnd(builder)
        return quoteSpec
