# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Rates market data shared across interest-rate products.
class RatesMarketData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RatesMarketData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRatesMarketData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RatesMarketData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Index definitions used by floating-rate instruments and curve helpers.
    # RatesMarketData
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.IndexDef import IndexDef
            obj = IndexDef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RatesMarketData
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RatesMarketData
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Swap index definitions for convention-stable swaption smile ATM computation.
    # RatesMarketData
    def SwapIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.SwapIndexDef import SwapIndexDef
            obj = SwapIndexDef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RatesMarketData
    def SwapIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RatesMarketData
    def SwapIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Yield curves for discounting/forwarding.
    # RatesMarketData
    def Curves(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.TermStructure import TermStructure
            obj = TermStructure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RatesMarketData
    def CurvesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RatesMarketData
    def CurvesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Coupon pricers for floating legs.
    # RatesMarketData
    def CouponPricers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.CouponPricer import CouponPricer
            obj = CouponPricer()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RatesMarketData
    def CouponPricersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RatesMarketData
    def CouponPricersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def RatesMarketDataStart(builder):
    builder.StartObject(4)

def Start(builder):
    RatesMarketDataStart(builder)

def RatesMarketDataAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def AddIndices(builder, indices):
    RatesMarketDataAddIndices(builder, indices)

def RatesMarketDataStartIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIndicesVector(builder, numElems):
    return RatesMarketDataStartIndicesVector(builder, numElems)

def RatesMarketDataAddSwapIndices(builder, swapIndices):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(swapIndices), 0)

def AddSwapIndices(builder, swapIndices):
    RatesMarketDataAddSwapIndices(builder, swapIndices)

def RatesMarketDataStartSwapIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSwapIndicesVector(builder, numElems):
    return RatesMarketDataStartSwapIndicesVector(builder, numElems)

def RatesMarketDataAddCurves(builder, curves):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(curves), 0)

def AddCurves(builder, curves):
    RatesMarketDataAddCurves(builder, curves)

def RatesMarketDataStartCurvesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCurvesVector(builder, numElems):
    return RatesMarketDataStartCurvesVector(builder, numElems)

def RatesMarketDataAddCouponPricers(builder, couponPricers):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(couponPricers), 0)

def AddCouponPricers(builder, couponPricers):
    RatesMarketDataAddCouponPricers(builder, couponPricers)

def RatesMarketDataStartCouponPricersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCouponPricersVector(builder, numElems):
    return RatesMarketDataStartCouponPricersVector(builder, numElems)

def RatesMarketDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RatesMarketDataEnd(builder)

try:
    from typing import List
except:
    pass

class RatesMarketDataT(object):

    # RatesMarketDataT
    def __init__(self):
        self.indices = None  # type: List[IndexDefT]
        self.swapIndices = None  # type: List[SwapIndexDefT]
        self.curves = None  # type: List[TermStructureT]
        self.couponPricers = None  # type: List[CouponPricerT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        ratesMarketData = RatesMarketData()
        ratesMarketData.Init(buf, pos)
        return cls.InitFromObj(ratesMarketData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, ratesMarketData):
        x = RatesMarketDataT()
        x._UnPack(ratesMarketData)
        return x

    # RatesMarketDataT
    def _UnPack(self, ratesMarketData):
        if ratesMarketData is None:
            return
        if not ratesMarketData.IndicesIsNone():
            self.indices = []
            for i in range(ratesMarketData.IndicesLength()):
                if ratesMarketData.Indices(i) is None:
                    self.indices.append(None)
                else:
                    indexDef_ = IndexDefT.InitFromObj(ratesMarketData.Indices(i))
                    self.indices.append(indexDef_)
        if not ratesMarketData.SwapIndicesIsNone():
            self.swapIndices = []
            for i in range(ratesMarketData.SwapIndicesLength()):
                if ratesMarketData.SwapIndices(i) is None:
                    self.swapIndices.append(None)
                else:
                    swapIndexDef_ = SwapIndexDefT.InitFromObj(ratesMarketData.SwapIndices(i))
                    self.swapIndices.append(swapIndexDef_)
        if not ratesMarketData.CurvesIsNone():
            self.curves = []
            for i in range(ratesMarketData.CurvesLength()):
                if ratesMarketData.Curves(i) is None:
                    self.curves.append(None)
                else:
                    termStructure_ = TermStructureT.InitFromObj(ratesMarketData.Curves(i))
                    self.curves.append(termStructure_)
        if not ratesMarketData.CouponPricersIsNone():
            self.couponPricers = []
            for i in range(ratesMarketData.CouponPricersLength()):
                if ratesMarketData.CouponPricers(i) is None:
                    self.couponPricers.append(None)
                else:
                    couponPricer_ = CouponPricerT.InitFromObj(ratesMarketData.CouponPricers(i))
                    self.couponPricers.append(couponPricer_)

    # RatesMarketDataT
    def Pack(self, builder):
        if self.indices is not None:
            indiceslist = []
            for i in range(len(self.indices)):
                indiceslist.append(self.indices[i].Pack(builder))
            RatesMarketDataStartIndicesVector(builder, len(self.indices))
            for i in reversed(range(len(self.indices))):
                builder.PrependUOffsetTRelative(indiceslist[i])
            indices = builder.EndVector()
        if self.swapIndices is not None:
            swapIndiceslist = []
            for i in range(len(self.swapIndices)):
                swapIndiceslist.append(self.swapIndices[i].Pack(builder))
            RatesMarketDataStartSwapIndicesVector(builder, len(self.swapIndices))
            for i in reversed(range(len(self.swapIndices))):
                builder.PrependUOffsetTRelative(swapIndiceslist[i])
            swapIndices = builder.EndVector()
        if self.curves is not None:
            curveslist = []
            for i in range(len(self.curves)):
                curveslist.append(self.curves[i].Pack(builder))
            RatesMarketDataStartCurvesVector(builder, len(self.curves))
            for i in reversed(range(len(self.curves))):
                builder.PrependUOffsetTRelative(curveslist[i])
            curves = builder.EndVector()
        if self.couponPricers is not None:
            couponPricerslist = []
            for i in range(len(self.couponPricers)):
                couponPricerslist.append(self.couponPricers[i].Pack(builder))
            RatesMarketDataStartCouponPricersVector(builder, len(self.couponPricers))
            for i in reversed(range(len(self.couponPricers))):
                builder.PrependUOffsetTRelative(couponPricerslist[i])
            couponPricers = builder.EndVector()
        RatesMarketDataStart(builder)
        if self.indices is not None:
            RatesMarketDataAddIndices(builder, indices)
        if self.swapIndices is not None:
            RatesMarketDataAddSwapIndices(builder, swapIndices)
        if self.curves is not None:
            RatesMarketDataAddCurves(builder, curves)
        if self.couponPricers is not None:
            RatesMarketDataAddCouponPricers(builder, couponPricers)
        ratesMarketData = RatesMarketDataEnd(builder)
        return ratesMarketData
