# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Response from volatility surface sampling request.
class SampleVolSurfacesResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SampleVolSurfacesResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSampleVolSurfacesResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SampleVolSurfacesResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SampleVolSurfacesResponse
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.VolSurfaceSample import VolSurfaceSample
            obj = VolSurfaceSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SampleVolSurfacesResponse
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SampleVolSurfacesResponse
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Per-surface diagnostics, one entry per unique SABR-kind vol surface
    # referenced by the request. Populated only when the request sets
    # `include_diagnostics=true`. Empty/absent otherwise.
    # SampleVolSurfacesResponse
    def Diagnostics(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.SwaptionVolDiagnostics import SwaptionVolDiagnostics
            obj = SwaptionVolDiagnostics()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SampleVolSurfacesResponse
    def DiagnosticsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SampleVolSurfacesResponse
    def DiagnosticsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SampleVolSurfacesResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    SampleVolSurfacesResponseStart(builder)

def SampleVolSurfacesResponseAddResults(builder, results):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)

def AddResults(builder, results):
    SampleVolSurfacesResponseAddResults(builder, results)

def SampleVolSurfacesResponseStartResultsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartResultsVector(builder, numElems):
    return SampleVolSurfacesResponseStartResultsVector(builder, numElems)

def SampleVolSurfacesResponseAddDiagnostics(builder, diagnostics):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(diagnostics), 0)

def AddDiagnostics(builder, diagnostics):
    SampleVolSurfacesResponseAddDiagnostics(builder, diagnostics)

def SampleVolSurfacesResponseStartDiagnosticsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDiagnosticsVector(builder, numElems):
    return SampleVolSurfacesResponseStartDiagnosticsVector(builder, numElems)

def SampleVolSurfacesResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return SampleVolSurfacesResponseEnd(builder)

try:
    from typing import List
except:
    pass

class SampleVolSurfacesResponseT(object):

    # SampleVolSurfacesResponseT
    def __init__(self):
        self.results = None  # type: List[VolSurfaceSampleT]
        self.diagnostics = None  # type: List[SwaptionVolDiagnosticsT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sampleVolSurfacesResponse = SampleVolSurfacesResponse()
        sampleVolSurfacesResponse.Init(buf, pos)
        return cls.InitFromObj(sampleVolSurfacesResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sampleVolSurfacesResponse):
        x = SampleVolSurfacesResponseT()
        x._UnPack(sampleVolSurfacesResponse)
        return x

    # SampleVolSurfacesResponseT
    def _UnPack(self, sampleVolSurfacesResponse):
        if sampleVolSurfacesResponse is None:
            return
        if not sampleVolSurfacesResponse.ResultsIsNone():
            self.results = []
            for i in range(sampleVolSurfacesResponse.ResultsLength()):
                if sampleVolSurfacesResponse.Results(i) is None:
                    self.results.append(None)
                else:
                    volSurfaceSample_ = VolSurfaceSampleT.InitFromObj(sampleVolSurfacesResponse.Results(i))
                    self.results.append(volSurfaceSample_)
        if not sampleVolSurfacesResponse.DiagnosticsIsNone():
            self.diagnostics = []
            for i in range(sampleVolSurfacesResponse.DiagnosticsLength()):
                if sampleVolSurfacesResponse.Diagnostics(i) is None:
                    self.diagnostics.append(None)
                else:
                    swaptionVolDiagnostics_ = SwaptionVolDiagnosticsT.InitFromObj(sampleVolSurfacesResponse.Diagnostics(i))
                    self.diagnostics.append(swaptionVolDiagnostics_)

    # SampleVolSurfacesResponseT
    def Pack(self, builder):
        if self.results is not None:
            resultslist = []
            for i in range(len(self.results)):
                resultslist.append(self.results[i].Pack(builder))
            SampleVolSurfacesResponseStartResultsVector(builder, len(self.results))
            for i in reversed(range(len(self.results))):
                builder.PrependUOffsetTRelative(resultslist[i])
            results = builder.EndVector()
        if self.diagnostics is not None:
            diagnosticslist = []
            for i in range(len(self.diagnostics)):
                diagnosticslist.append(self.diagnostics[i].Pack(builder))
            SampleVolSurfacesResponseStartDiagnosticsVector(builder, len(self.diagnostics))
            for i in reversed(range(len(self.diagnostics))):
                builder.PrependUOffsetTRelative(diagnosticslist[i])
            diagnostics = builder.EndVector()
        SampleVolSurfacesResponseStart(builder)
        if self.results is not None:
            SampleVolSurfacesResponseAddResults(builder, results)
        if self.diagnostics is not None:
            SampleVolSurfacesResponseAddDiagnostics(builder, diagnostics)
        sampleVolSurfacesResponse = SampleVolSurfacesResponseEnd(builder)
        return sampleVolSurfacesResponse
