# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SwaptionSabrParamsSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SwaptionSabrParamsSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSwaptionSabrParamsSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SwaptionSabrParamsSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SwaptionSabrParamsSpec
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.IrVolBaseSpec import IrVolBaseSpec
            obj = IrVolBaseSpec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwaptionSabrParamsSpec
    def Expiries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from quantra.Period import Period
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwaptionSabrParamsSpec
    def ExpiriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SwaptionSabrParamsSpec
    def ExpiriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SwaptionSabrParamsSpec
    def Tenors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwaptionSabrParamsSpec
    def TenorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SwaptionSabrParamsSpec
    def TenorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SwaptionSabrParamsSpec
    def Alpha(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.QuoteMatrix2D import QuoteMatrix2D
            obj = QuoteMatrix2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwaptionSabrParamsSpec
    def Beta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = QuoteMatrix2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwaptionSabrParamsSpec
    def Rho(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = QuoteMatrix2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwaptionSabrParamsSpec
    def Nu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = QuoteMatrix2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SwaptionSabrParamsSpecStart(builder):
    builder.StartObject(7)

def Start(builder):
    SwaptionSabrParamsSpecStart(builder)

def SwaptionSabrParamsSpecAddBase(builder, base):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(base), 0)

def AddBase(builder, base):
    SwaptionSabrParamsSpecAddBase(builder, base)

def SwaptionSabrParamsSpecAddExpiries(builder, expiries):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(expiries), 0)

def AddExpiries(builder, expiries):
    SwaptionSabrParamsSpecAddExpiries(builder, expiries)

def SwaptionSabrParamsSpecStartExpiriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExpiriesVector(builder, numElems):
    return SwaptionSabrParamsSpecStartExpiriesVector(builder, numElems)

def SwaptionSabrParamsSpecAddTenors(builder, tenors):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tenors), 0)

def AddTenors(builder, tenors):
    SwaptionSabrParamsSpecAddTenors(builder, tenors)

def SwaptionSabrParamsSpecStartTenorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTenorsVector(builder, numElems):
    return SwaptionSabrParamsSpecStartTenorsVector(builder, numElems)

def SwaptionSabrParamsSpecAddAlpha(builder, alpha):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(alpha), 0)

def AddAlpha(builder, alpha):
    SwaptionSabrParamsSpecAddAlpha(builder, alpha)

def SwaptionSabrParamsSpecAddBeta(builder, beta):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(beta), 0)

def AddBeta(builder, beta):
    SwaptionSabrParamsSpecAddBeta(builder, beta)

def SwaptionSabrParamsSpecAddRho(builder, rho):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rho), 0)

def AddRho(builder, rho):
    SwaptionSabrParamsSpecAddRho(builder, rho)

def SwaptionSabrParamsSpecAddNu(builder, nu):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(nu), 0)

def AddNu(builder, nu):
    SwaptionSabrParamsSpecAddNu(builder, nu)

def SwaptionSabrParamsSpecEnd(builder):
    return builder.EndObject()

def End(builder):
    return SwaptionSabrParamsSpecEnd(builder)

try:
    from typing import List, Optional
except:
    pass

class SwaptionSabrParamsSpecT(object):

    # SwaptionSabrParamsSpecT
    def __init__(self):
        self.base = None  # type: Optional[IrVolBaseSpecT]
        self.expiries = None  # type: List[PeriodT]
        self.tenors = None  # type: List[PeriodT]
        self.alpha = None  # type: Optional[QuoteMatrix2DT]
        self.beta = None  # type: Optional[QuoteMatrix2DT]
        self.rho = None  # type: Optional[QuoteMatrix2DT]
        self.nu = None  # type: Optional[QuoteMatrix2DT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        swaptionSabrParamsSpec = SwaptionSabrParamsSpec()
        swaptionSabrParamsSpec.Init(buf, pos)
        return cls.InitFromObj(swaptionSabrParamsSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, swaptionSabrParamsSpec):
        x = SwaptionSabrParamsSpecT()
        x._UnPack(swaptionSabrParamsSpec)
        return x

    # SwaptionSabrParamsSpecT
    def _UnPack(self, swaptionSabrParamsSpec):
        if swaptionSabrParamsSpec is None:
            return
        if swaptionSabrParamsSpec.Base() is not None:
            self.base = IrVolBaseSpecT.InitFromObj(swaptionSabrParamsSpec.Base())
        if not swaptionSabrParamsSpec.ExpiriesIsNone():
            self.expiries = []
            for i in range(swaptionSabrParamsSpec.ExpiriesLength()):
                if swaptionSabrParamsSpec.Expiries(i) is None:
                    self.expiries.append(None)
                else:
                    period_ = PeriodT.InitFromObj(swaptionSabrParamsSpec.Expiries(i))
                    self.expiries.append(period_)
        if not swaptionSabrParamsSpec.TenorsIsNone():
            self.tenors = []
            for i in range(swaptionSabrParamsSpec.TenorsLength()):
                if swaptionSabrParamsSpec.Tenors(i) is None:
                    self.tenors.append(None)
                else:
                    period_ = PeriodT.InitFromObj(swaptionSabrParamsSpec.Tenors(i))
                    self.tenors.append(period_)
        if swaptionSabrParamsSpec.Alpha() is not None:
            self.alpha = QuoteMatrix2DT.InitFromObj(swaptionSabrParamsSpec.Alpha())
        if swaptionSabrParamsSpec.Beta() is not None:
            self.beta = QuoteMatrix2DT.InitFromObj(swaptionSabrParamsSpec.Beta())
        if swaptionSabrParamsSpec.Rho() is not None:
            self.rho = QuoteMatrix2DT.InitFromObj(swaptionSabrParamsSpec.Rho())
        if swaptionSabrParamsSpec.Nu() is not None:
            self.nu = QuoteMatrix2DT.InitFromObj(swaptionSabrParamsSpec.Nu())

    # SwaptionSabrParamsSpecT
    def Pack(self, builder):
        if self.base is not None:
            base = self.base.Pack(builder)
        if self.expiries is not None:
            expirieslist = []
            for i in range(len(self.expiries)):
                expirieslist.append(self.expiries[i].Pack(builder))
            SwaptionSabrParamsSpecStartExpiriesVector(builder, len(self.expiries))
            for i in reversed(range(len(self.expiries))):
                builder.PrependUOffsetTRelative(expirieslist[i])
            expiries = builder.EndVector()
        if self.tenors is not None:
            tenorslist = []
            for i in range(len(self.tenors)):
                tenorslist.append(self.tenors[i].Pack(builder))
            SwaptionSabrParamsSpecStartTenorsVector(builder, len(self.tenors))
            for i in reversed(range(len(self.tenors))):
                builder.PrependUOffsetTRelative(tenorslist[i])
            tenors = builder.EndVector()
        if self.alpha is not None:
            alpha = self.alpha.Pack(builder)
        if self.beta is not None:
            beta = self.beta.Pack(builder)
        if self.rho is not None:
            rho = self.rho.Pack(builder)
        if self.nu is not None:
            nu = self.nu.Pack(builder)
        SwaptionSabrParamsSpecStart(builder)
        if self.base is not None:
            SwaptionSabrParamsSpecAddBase(builder, base)
        if self.expiries is not None:
            SwaptionSabrParamsSpecAddExpiries(builder, expiries)
        if self.tenors is not None:
            SwaptionSabrParamsSpecAddTenors(builder, tenors)
        if self.alpha is not None:
            SwaptionSabrParamsSpecAddAlpha(builder, alpha)
        if self.beta is not None:
            SwaptionSabrParamsSpecAddBeta(builder, beta)
        if self.rho is not None:
            SwaptionSabrParamsSpecAddRho(builder, rho)
        if self.nu is not None:
            SwaptionSabrParamsSpecAddNu(builder, nu)
        swaptionSabrParamsSpec = SwaptionSabrParamsSpecEnd(builder)
        return swaptionSabrParamsSpec
