# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SwapIndexFloatLegSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SwapIndexFloatLegSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSwapIndexFloatLegSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SwapIndexFloatLegSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SwapIndexFloatLegSpec
    def FloatTenor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Period import Period
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SwapIndexFloatLegSpec
    def FloatCalendar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 32

    # SwapIndexFloatLegSpec
    def FloatBdc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

    # SwapIndexFloatLegSpec
    def FloatTermBdc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

    # SwapIndexFloatLegSpec
    def FloatDateRule(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

    # SwapIndexFloatLegSpec
    def FloatEom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SwapIndexFloatLegSpecStart(builder):
    builder.StartObject(6)

def Start(builder):
    SwapIndexFloatLegSpecStart(builder)

def SwapIndexFloatLegSpecAddFloatTenor(builder, floatTenor):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(floatTenor), 0)

def AddFloatTenor(builder, floatTenor):
    SwapIndexFloatLegSpecAddFloatTenor(builder, floatTenor)

def SwapIndexFloatLegSpecAddFloatCalendar(builder, floatCalendar):
    builder.PrependInt8Slot(1, floatCalendar, 32)

def AddFloatCalendar(builder, floatCalendar):
    SwapIndexFloatLegSpecAddFloatCalendar(builder, floatCalendar)

def SwapIndexFloatLegSpecAddFloatBdc(builder, floatBdc):
    builder.PrependInt8Slot(2, floatBdc, 2)

def AddFloatBdc(builder, floatBdc):
    SwapIndexFloatLegSpecAddFloatBdc(builder, floatBdc)

def SwapIndexFloatLegSpecAddFloatTermBdc(builder, floatTermBdc):
    builder.PrependInt8Slot(3, floatTermBdc, 2)

def AddFloatTermBdc(builder, floatTermBdc):
    SwapIndexFloatLegSpecAddFloatTermBdc(builder, floatTermBdc)

def SwapIndexFloatLegSpecAddFloatDateRule(builder, floatDateRule):
    builder.PrependInt8Slot(4, floatDateRule, 2)

def AddFloatDateRule(builder, floatDateRule):
    SwapIndexFloatLegSpecAddFloatDateRule(builder, floatDateRule)

def SwapIndexFloatLegSpecAddFloatEom(builder, floatEom):
    builder.PrependBoolSlot(5, floatEom, 0)

def AddFloatEom(builder, floatEom):
    SwapIndexFloatLegSpecAddFloatEom(builder, floatEom)

def SwapIndexFloatLegSpecEnd(builder):
    return builder.EndObject()

def End(builder):
    return SwapIndexFloatLegSpecEnd(builder)

try:
    from typing import Optional
except:
    pass

class SwapIndexFloatLegSpecT(object):

    # SwapIndexFloatLegSpecT
    def __init__(self):
        self.floatTenor = None  # type: Optional[PeriodT]
        self.floatCalendar = 32  # type: int
        self.floatBdc = 2  # type: int
        self.floatTermBdc = 2  # type: int
        self.floatDateRule = 2  # type: int
        self.floatEom = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        swapIndexFloatLegSpec = SwapIndexFloatLegSpec()
        swapIndexFloatLegSpec.Init(buf, pos)
        return cls.InitFromObj(swapIndexFloatLegSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, swapIndexFloatLegSpec):
        x = SwapIndexFloatLegSpecT()
        x._UnPack(swapIndexFloatLegSpec)
        return x

    # SwapIndexFloatLegSpecT
    def _UnPack(self, swapIndexFloatLegSpec):
        if swapIndexFloatLegSpec is None:
            return
        if swapIndexFloatLegSpec.FloatTenor() is not None:
            self.floatTenor = PeriodT.InitFromObj(swapIndexFloatLegSpec.FloatTenor())
        self.floatCalendar = swapIndexFloatLegSpec.FloatCalendar()
        self.floatBdc = swapIndexFloatLegSpec.FloatBdc()
        self.floatTermBdc = swapIndexFloatLegSpec.FloatTermBdc()
        self.floatDateRule = swapIndexFloatLegSpec.FloatDateRule()
        self.floatEom = swapIndexFloatLegSpec.FloatEom()

    # SwapIndexFloatLegSpecT
    def Pack(self, builder):
        if self.floatTenor is not None:
            floatTenor = self.floatTenor.Pack(builder)
        SwapIndexFloatLegSpecStart(builder)
        if self.floatTenor is not None:
            SwapIndexFloatLegSpecAddFloatTenor(builder, floatTenor)
        SwapIndexFloatLegSpecAddFloatCalendar(builder, self.floatCalendar)
        SwapIndexFloatLegSpecAddFloatBdc(builder, self.floatBdc)
        SwapIndexFloatLegSpecAddFloatTermBdc(builder, self.floatTermBdc)
        SwapIndexFloatLegSpecAddFloatDateRule(builder, self.floatDateRule)
        SwapIndexFloatLegSpecAddFloatEom(builder, self.floatEom)
        swapIndexFloatLegSpec = SwapIndexFloatLegSpecEnd(builder)
        return swapIndexFloatLegSpec
