# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VolatilityQuote(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VolatilityQuote()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVolatilityQuote(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VolatilityQuote
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VolatilityQuote
    def TenorNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VolatilityQuote
    def TenorTimeUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # VolatilityQuote
    def Strike(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # VolatilityQuote
    def Volatility(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def VolatilityQuoteStart(builder):
    builder.StartObject(4)

def Start(builder):
    VolatilityQuoteStart(builder)

def VolatilityQuoteAddTenorNumber(builder, tenorNumber):
    builder.PrependInt32Slot(0, tenorNumber, 0)

def AddTenorNumber(builder, tenorNumber):
    VolatilityQuoteAddTenorNumber(builder, tenorNumber)

def VolatilityQuoteAddTenorTimeUnit(builder, tenorTimeUnit):
    builder.PrependInt8Slot(1, tenorTimeUnit, 0)

def AddTenorTimeUnit(builder, tenorTimeUnit):
    VolatilityQuoteAddTenorTimeUnit(builder, tenorTimeUnit)

def VolatilityQuoteAddStrike(builder, strike):
    builder.PrependFloat64Slot(2, strike, 0.0)

def AddStrike(builder, strike):
    VolatilityQuoteAddStrike(builder, strike)

def VolatilityQuoteAddVolatility(builder, volatility):
    builder.PrependFloat64Slot(3, volatility, 0.0)

def AddVolatility(builder, volatility):
    VolatilityQuoteAddVolatility(builder, volatility)

def VolatilityQuoteEnd(builder):
    return builder.EndObject()

def End(builder):
    return VolatilityQuoteEnd(builder)


class VolatilityQuoteT(object):

    # VolatilityQuoteT
    def __init__(self):
        self.tenorNumber = 0  # type: int
        self.tenorTimeUnit = 0  # type: int
        self.strike = 0.0  # type: float
        self.volatility = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        volatilityQuote = VolatilityQuote()
        volatilityQuote.Init(buf, pos)
        return cls.InitFromObj(volatilityQuote)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, volatilityQuote):
        x = VolatilityQuoteT()
        x._UnPack(volatilityQuote)
        return x

    # VolatilityQuoteT
    def _UnPack(self, volatilityQuote):
        if volatilityQuote is None:
            return
        self.tenorNumber = volatilityQuote.TenorNumber()
        self.tenorTimeUnit = volatilityQuote.TenorTimeUnit()
        self.strike = volatilityQuote.Strike()
        self.volatility = volatilityQuote.Volatility()

    # VolatilityQuoteT
    def Pack(self, builder):
        VolatilityQuoteStart(builder)
        VolatilityQuoteAddTenorNumber(builder, self.tenorNumber)
        VolatilityQuoteAddTenorTimeUnit(builder, self.tenorTimeUnit)
        VolatilityQuoteAddStrike(builder, self.strike)
        VolatilityQuoteAddVolatility(builder, self.volatility)
        volatilityQuote = VolatilityQuoteEnd(builder)
        return volatilityQuote
