# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Yield(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Yield()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsYield(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Yield
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Yield
    def DayCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Yield
    def Compounding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Yield
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def YieldStart(builder):
    builder.StartObject(3)

def Start(builder):
    YieldStart(builder)

def YieldAddDayCounter(builder, dayCounter):
    builder.PrependInt8Slot(0, dayCounter, 0)

def AddDayCounter(builder, dayCounter):
    YieldAddDayCounter(builder, dayCounter)

def YieldAddCompounding(builder, compounding):
    builder.PrependInt8Slot(1, compounding, 0)

def AddCompounding(builder, compounding):
    YieldAddCompounding(builder, compounding)

def YieldAddFrequency(builder, frequency):
    builder.PrependInt8Slot(2, frequency, 0)

def AddFrequency(builder, frequency):
    YieldAddFrequency(builder, frequency)

def YieldEnd(builder):
    return builder.EndObject()

def End(builder):
    return YieldEnd(builder)


class YieldT(object):

    # YieldT
    def __init__(self):
        self.dayCounter = 0  # type: int
        self.compounding = 0  # type: int
        self.frequency = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        yield_ = Yield()
        yield_.Init(buf, pos)
        return cls.InitFromObj(yield_)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, yield_):
        x = YieldT()
        x._UnPack(yield_)
        return x

    # YieldT
    def _UnPack(self, yield_):
        if yield_ is None:
            return
        self.dayCounter = yield_.DayCounter()
        self.compounding = yield_.Compounding()
        self.frequency = yield_.Frequency()

    # YieldT
    def Pack(self, builder):
        YieldStart(builder)
        YieldAddDayCounter(builder, self.dayCounter)
        YieldAddCompounding(builder, self.compounding)
        YieldAddFrequency(builder, self.frequency)
        yield_ = YieldEnd(builder)
        return yield_
