# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quantra

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ZeroRatePoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ZeroRatePoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsZeroRatePoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ZeroRatePoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Maturity date for the zero rate (YYYY-MM-DD)
    # ZeroRatePoint
    def Date(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Alternative: tenor from reference date
    # ZeroRatePoint
    def Tenor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from quantra.Period import Period
            obj = Period()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ZeroRatePoint
    def Calendar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 32

    # ZeroRatePoint
    def BusinessDayConvention(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

    # Zero rate for this maturity
    # ZeroRatePoint
    def ZeroRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Compounding convention for the zero rate
    # ZeroRatePoint
    def Compounding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

    # Frequency (used when compounding != Continuous)
    # ZeroRatePoint
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ZeroRatePointStart(builder):
    builder.StartObject(7)

def Start(builder):
    ZeroRatePointStart(builder)

def ZeroRatePointAddDate(builder, date):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(date), 0)

def AddDate(builder, date):
    ZeroRatePointAddDate(builder, date)

def ZeroRatePointAddTenor(builder, tenor):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tenor), 0)

def AddTenor(builder, tenor):
    ZeroRatePointAddTenor(builder, tenor)

def ZeroRatePointAddCalendar(builder, calendar):
    builder.PrependInt8Slot(2, calendar, 32)

def AddCalendar(builder, calendar):
    ZeroRatePointAddCalendar(builder, calendar)

def ZeroRatePointAddBusinessDayConvention(builder, businessDayConvention):
    builder.PrependInt8Slot(3, businessDayConvention, 2)

def AddBusinessDayConvention(builder, businessDayConvention):
    ZeroRatePointAddBusinessDayConvention(builder, businessDayConvention)

def ZeroRatePointAddZeroRate(builder, zeroRate):
    builder.PrependFloat64Slot(4, zeroRate, 0.0)

def AddZeroRate(builder, zeroRate):
    ZeroRatePointAddZeroRate(builder, zeroRate)

def ZeroRatePointAddCompounding(builder, compounding):
    builder.PrependInt8Slot(5, compounding, 1)

def AddCompounding(builder, compounding):
    ZeroRatePointAddCompounding(builder, compounding)

def ZeroRatePointAddFrequency(builder, frequency):
    builder.PrependInt8Slot(6, frequency, 0)

def AddFrequency(builder, frequency):
    ZeroRatePointAddFrequency(builder, frequency)

def ZeroRatePointEnd(builder):
    return builder.EndObject()

def End(builder):
    return ZeroRatePointEnd(builder)

try:
    from typing import Optional
except:
    pass

class ZeroRatePointT(object):

    # ZeroRatePointT
    def __init__(self):
        self.date = None  # type: str
        self.tenor = None  # type: Optional[PeriodT]
        self.calendar = 32  # type: int
        self.businessDayConvention = 2  # type: int
        self.zeroRate = 0.0  # type: float
        self.compounding = 1  # type: int
        self.frequency = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        zeroRatePoint = ZeroRatePoint()
        zeroRatePoint.Init(buf, pos)
        return cls.InitFromObj(zeroRatePoint)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, zeroRatePoint):
        x = ZeroRatePointT()
        x._UnPack(zeroRatePoint)
        return x

    # ZeroRatePointT
    def _UnPack(self, zeroRatePoint):
        if zeroRatePoint is None:
            return
        self.date = zeroRatePoint.Date()
        if zeroRatePoint.Tenor() is not None:
            self.tenor = PeriodT.InitFromObj(zeroRatePoint.Tenor())
        self.calendar = zeroRatePoint.Calendar()
        self.businessDayConvention = zeroRatePoint.BusinessDayConvention()
        self.zeroRate = zeroRatePoint.ZeroRate()
        self.compounding = zeroRatePoint.Compounding()
        self.frequency = zeroRatePoint.Frequency()

    # ZeroRatePointT
    def Pack(self, builder):
        if self.date is not None:
            date = builder.CreateString(self.date)
        if self.tenor is not None:
            tenor = self.tenor.Pack(builder)
        ZeroRatePointStart(builder)
        if self.date is not None:
            ZeroRatePointAddDate(builder, date)
        if self.tenor is not None:
            ZeroRatePointAddTenor(builder, tenor)
        ZeroRatePointAddCalendar(builder, self.calendar)
        ZeroRatePointAddBusinessDayConvention(builder, self.businessDayConvention)
        ZeroRatePointAddZeroRate(builder, self.zeroRate)
        ZeroRatePointAddCompounding(builder, self.compounding)
        ZeroRatePointAddFrequency(builder, self.frequency)
        zeroRatePoint = ZeroRatePointEnd(builder)
        return zeroRatePoint
