# automatically generated by the FlatBuffers compiler, do not modify

# namespace: enums

# Cap/Floor instrument type: cap, floor, or collar.
class CapFloorType(object):
    Cap = 0
    Floor = 1
    Collar = 2
