# automatically generated by the FlatBuffers compiler, do not modify

# namespace: enums

# Barrier direction/style for barrier options.
class EquityBarrierType(object):
    DownIn = 0
    UpIn = 1
    DownOut = 2
    UpOut = 3
