# automatically generated by the FlatBuffers compiler, do not modify

# namespace: enums

# Swaption exercise style: European (at expiry only), Bermudan (on specific dates), or American (any time).
class ExerciseType(object):
    European = 0
    Bermudan = 1
    American = 2
