# automatically generated by the FlatBuffers compiler, do not modify

# namespace: enums

class SettlementMethod(object):
    PhysicalOTC = 0
    PhysicalCleared = 1
    CollateralizedCashPrice = 2
    ParYieldCurve = 3
