include "enums.fbs";

namespace quantra;

/// Constant optionlet volatility for coupon pricer.
table ConstantOptionletVolatility {
    settlement_days:int;
    calendar:enums.Calendar = null;
    business_day_convention:enums.BusinessDayConvention = null;
    volatility:double;
    day_counter:enums.DayCounter = null;
}

/// Black Ibor coupon pricer with optionlet volatility.
table BlackIborCouponPricer {
    optionlet_volatility:ConstantOptionletVolatility;
}

/// Coupon pricer specification referenced by id.
table CouponPricer {
    id:string;
    black_ibor_coupon_pricer:BlackIborCouponPricer;
}

root_type CouponPricer;
