include "common.fbs";

namespace quantra;

/// Floating-rate bond pricing response.
table FloatingRateBondResponse {
    npv:double;
    clean_price:double;
    dirty_price:double;
    accrued_amount:double;
    yield:double;
    accrued_days:double;
    macaulay_duration:double;
    modified_duration:double;
    convexity:double;
    bps:double;
    flows:[FlowsWrapper];
}

/// Response wrapper for multiple floating-rate bonds.
table PriceFloatingRateBondResponse {
    bonds:[FloatingRateBondResponse] (required);
}

root_type PriceFloatingRateBondResponse;
