include "common.fbs";
include "pricing.fbs";
include "floating_rate_bond.fbs";
include "term_structure.fbs";

namespace quantra;

/// Single floating-rate bond pricing context.
table PriceFloatingRateBond {
    floating_rate_bond:FloatingRateBond;
    discounting_curve:string;
    forecasting_curve:string;
    coupon_pricer:string;
    yield:Yield;
}

/// Request to price one or more floating-rate bonds.
table PriceFloatingRateBondRequest {
    pricing:Pricing;
    bonds:[PriceFloatingRateBond];
}

root_type PriceFloatingRateBondRequest;
