include "../flatbuffers/fbs/price_fixed_rate_bond_request.fbs";
include "../flatbuffers/fbs/price_floating_rate_bond_request.fbs";
include "../flatbuffers/fbs/fixed_rate_bond_response.fbs";
include "../flatbuffers/fbs/floating_rate_bond_response.fbs";
include "../flatbuffers/fbs/price_vanilla_swap_request.fbs";
include "../flatbuffers/fbs/vanilla_swap_response.fbs";
include "../flatbuffers/fbs/price_zero_coupon_inflation_swap_request.fbs";
include "../flatbuffers/fbs/zero_coupon_inflation_swap_response.fbs";
include "../flatbuffers/fbs/price_year_on_year_inflation_swap_request.fbs";
include "../flatbuffers/fbs/year_on_year_inflation_swap_response.fbs";
include "../flatbuffers/fbs/price_ois_swap_request.fbs";
include "../flatbuffers/fbs/ois_swap_response.fbs";
include "../flatbuffers/fbs/price_basis_swap_request.fbs";
include "../flatbuffers/fbs/basis_swap_response.fbs";
include "../flatbuffers/fbs/price_fra_request.fbs";
include "../flatbuffers/fbs/fra_response.fbs";
include "../flatbuffers/fbs/price_cap_floor_request.fbs";
include "../flatbuffers/fbs/cap_floor_response.fbs";
include "../flatbuffers/fbs/price_swaption_request.fbs";
include "../flatbuffers/fbs/swaption_response.fbs";
include "../flatbuffers/fbs/price_cds_request.fbs";
include "../flatbuffers/fbs/cds_response.fbs";
include "../flatbuffers/fbs/bootstrap_curves_request.fbs";
include "../flatbuffers/fbs/bootstrap_curves_response.fbs";
include "../flatbuffers/fbs/bootstrap_inflation_curves_request.fbs";
include "../flatbuffers/fbs/bootstrap_inflation_curves_response.fbs";
include "../flatbuffers/fbs/sample_vol_surfaces_request.fbs";
include "../flatbuffers/fbs/sample_vol_surfaces_response.fbs";
include "../flatbuffers/fbs/calendar_business_days_request.fbs";
include "../flatbuffers/fbs/calendar_business_days_response.fbs";
include "../flatbuffers/fbs/calendar_holidays_request.fbs";
include "../flatbuffers/fbs/calendar_holidays_response.fbs";
include "../flatbuffers/fbs/calendar_advance_request.fbs";
include "../flatbuffers/fbs/calendar_advance_response.fbs";
include "../flatbuffers/fbs/calibrate_swaption_model_request.fbs";
include "../flatbuffers/fbs/calibrate_swaption_model_response.fbs";
include "../flatbuffers/fbs/calibrate_swaption_vol_request.fbs";
include "../flatbuffers/fbs/calibrate_swaption_vol_response.fbs";
include "../flatbuffers/fbs/price_equity_option_request.fbs";
include "../flatbuffers/fbs/equity_option_response.fbs";
include "../flatbuffers/fbs/price_zero_coupon_bond_request.fbs";
include "../flatbuffers/fbs/zero_coupon_bond_response.fbs";
include "../flatbuffers/fbs/price_zero_coupon_swap_request.fbs";
include "../flatbuffers/fbs/zero_coupon_swap_response.fbs";
include "../flatbuffers/fbs/meta_request.fbs";
include "../flatbuffers/fbs/meta_response.fbs";

namespace quantra;

rpc_service QuantraServer {
  PriceFixedRateBond(PriceFixedRateBondRequest):PriceFixedRateBondResponse;
  PriceFloatingRateBond(PriceFloatingRateBondRequest):PriceFloatingRateBondResponse;
  PriceVanillaSwap(PriceVanillaSwapRequest):PriceVanillaSwapResponse;
  PriceZeroCouponInflationSwap(PriceZeroCouponInflationSwapRequest):PriceZeroCouponInflationSwapResponse;
  PriceYearOnYearInflationSwap(PriceYearOnYearInflationSwapRequest):PriceYearOnYearInflationSwapResponse;
  PriceOisSwap(PriceOisSwapRequest):PriceOisSwapResponse;
  PriceBasisSwap(PriceBasisSwapRequest):PriceBasisSwapResponse;
  PriceFRA(PriceFRARequest):PriceFRAResponse;
  PriceCapFloor(PriceCapFloorRequest):PriceCapFloorResponse;
  PriceSwaption(PriceSwaptionRequest):PriceSwaptionResponse;
  PriceCDS(PriceCDSRequest):PriceCDSResponse;
  BootstrapCurves(BootstrapCurvesRequest):BootstrapCurvesResponse;
  BootstrapInflationCurves(BootstrapInflationCurvesRequest):BootstrapInflationCurvesResponse;
  SampleVolSurfaces(SampleVolSurfacesRequest):SampleVolSurfacesResponse;
  CalendarBusinessDays(CalendarBusinessDaysRequest):CalendarBusinessDaysResponse;
  CalendarHolidays(CalendarHolidaysRequest):CalendarHolidaysResponse;
  CalendarAdvance(CalendarAdvanceRequest):CalendarAdvanceResponse;
  CalibrateSwaptionModel(CalibrateSwaptionModelRequest):CalibrateSwaptionModelResponse;
  CalibrateSwaptionVol(CalibrateSwaptionVolRequest):CalibrateSwaptionVolResponse;
  PriceEquityOption(PriceEquityOptionRequest):PriceEquityOptionResponse;
  PriceZeroCouponBond(PriceZeroCouponBondRequest):PriceZeroCouponBondResponse;
  PriceZeroCouponSwap(PriceZeroCouponSwapRequest):PriceZeroCouponSwapResponse;
  Meta(MetaRequest):MetaResponse;
}