export GRPC_INSTALL_PATH=/root/grpc/install/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${GRPC_INSTALL_PATH}/lib
export QUANTRA_HOME=/root/quantragrpc/
export QUANTRA_PORT=50051
export QUANTRA_SERVER_PORT=50055
