// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BOOTSTRAPINFLATIONCURVESRESPONSE_QUANTRA_H_
#define FLATBUFFERS_GENERATED_BOOTSTRAPINFLATIONCURVESRESPONSE_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"
#include "enums_generated.h"

namespace quantra {

struct InflationCurveSeries;
struct InflationCurveSeriesBuilder;
struct InflationCurveSeriesT;

struct BootstrapInflationCurveResult;
struct BootstrapInflationCurveResultBuilder;
struct BootstrapInflationCurveResultT;

struct BootstrapInflationCurvesResponse;
struct BootstrapInflationCurvesResponseBuilder;
struct BootstrapInflationCurvesResponseT;

struct InflationCurveSeriesT : public ::flatbuffers::NativeTable {
  typedef InflationCurveSeries TableType;
  quantra::enums::InflationCurveMeasure measure = quantra::enums::InflationCurveMeasure_ZeroRate;
  std::vector<double> values{};
};

/// One sampled inflation series aligned to grid_dates.
struct InflationCurveSeries FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InflationCurveSeriesT NativeTableType;
  typedef InflationCurveSeriesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MEASURE = 4,
    VT_VALUES = 6
  };
  quantra::enums::InflationCurveMeasure measure() const {
    return static_cast<quantra::enums::InflationCurveMeasure>(GetField<int8_t>(VT_MEASURE, 0));
  }
  const ::flatbuffers::Vector<double> *values() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_MEASURE, 1) &&
           VerifyOffsetRequired(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
  InflationCurveSeriesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InflationCurveSeriesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InflationCurveSeries> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSeriesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InflationCurveSeriesBuilder {
  typedef InflationCurveSeries Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_measure(quantra::enums::InflationCurveMeasure measure) {
    fbb_.AddElement<int8_t>(InflationCurveSeries::VT_MEASURE, static_cast<int8_t>(measure), 0);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<double>> values) {
    fbb_.AddOffset(InflationCurveSeries::VT_VALUES, values);
  }
  explicit InflationCurveSeriesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InflationCurveSeries> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InflationCurveSeries>(end);
    fbb_.Required(o, InflationCurveSeries::VT_VALUES);
    return o;
  }
};

inline ::flatbuffers::Offset<InflationCurveSeries> CreateInflationCurveSeries(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    quantra::enums::InflationCurveMeasure measure = quantra::enums::InflationCurveMeasure_ZeroRate,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> values = 0) {
  InflationCurveSeriesBuilder builder_(_fbb);
  builder_.add_values(values);
  builder_.add_measure(measure);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<InflationCurveSeries> CreateInflationCurveSeriesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    quantra::enums::InflationCurveMeasure measure = quantra::enums::InflationCurveMeasure_ZeroRate,
    const std::vector<double> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<double>(*values) : 0;
  return quantra::CreateInflationCurveSeries(
      _fbb,
      measure,
      values__);
}

::flatbuffers::Offset<InflationCurveSeries> CreateInflationCurveSeries(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSeriesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BootstrapInflationCurveResultT : public ::flatbuffers::NativeTable {
  typedef BootstrapInflationCurveResult TableType;
  std::string id{};
  std::string reference_date{};
  std::vector<std::string> grid_dates{};
  std::vector<std::unique_ptr<quantra::InflationCurveSeriesT>> series{};
  std::vector<std::string> pillar_dates{};
  std::unique_ptr<quantra::ErrorT> error{};
  BootstrapInflationCurveResultT() = default;
  BootstrapInflationCurveResultT(const BootstrapInflationCurveResultT &o);
  BootstrapInflationCurveResultT(BootstrapInflationCurveResultT&&) FLATBUFFERS_NOEXCEPT = default;
  BootstrapInflationCurveResultT &operator=(BootstrapInflationCurveResultT o) FLATBUFFERS_NOEXCEPT;
};

/// Result for a single requested inflation curve.
struct BootstrapInflationCurveResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BootstrapInflationCurveResultT NativeTableType;
  typedef BootstrapInflationCurveResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_REFERENCE_DATE = 6,
    VT_GRID_DATES = 8,
    VT_SERIES = 10,
    VT_PILLAR_DATES = 12,
    VT_ERROR = 14
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *reference_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REFERENCE_DATE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *grid_dates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_GRID_DATES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveSeries>> *series() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveSeries>> *>(VT_SERIES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *pillar_dates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_PILLAR_DATES);
  }
  const quantra::Error *error() const {
    return GetPointer<const quantra::Error *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_REFERENCE_DATE) &&
           verifier.VerifyString(reference_date()) &&
           VerifyOffset(verifier, VT_GRID_DATES) &&
           verifier.VerifyVector(grid_dates()) &&
           verifier.VerifyVectorOfStrings(grid_dates()) &&
           VerifyOffset(verifier, VT_SERIES) &&
           verifier.VerifyVector(series()) &&
           verifier.VerifyVectorOfTables(series()) &&
           VerifyOffset(verifier, VT_PILLAR_DATES) &&
           verifier.VerifyVector(pillar_dates()) &&
           verifier.VerifyVectorOfStrings(pillar_dates()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyTable(error()) &&
           verifier.EndTable();
  }
  BootstrapInflationCurveResultT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BootstrapInflationCurveResultT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BootstrapInflationCurveResult> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurveResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BootstrapInflationCurveResultBuilder {
  typedef BootstrapInflationCurveResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(BootstrapInflationCurveResult::VT_ID, id);
  }
  void add_reference_date(::flatbuffers::Offset<::flatbuffers::String> reference_date) {
    fbb_.AddOffset(BootstrapInflationCurveResult::VT_REFERENCE_DATE, reference_date);
  }
  void add_grid_dates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> grid_dates) {
    fbb_.AddOffset(BootstrapInflationCurveResult::VT_GRID_DATES, grid_dates);
  }
  void add_series(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveSeries>>> series) {
    fbb_.AddOffset(BootstrapInflationCurveResult::VT_SERIES, series);
  }
  void add_pillar_dates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> pillar_dates) {
    fbb_.AddOffset(BootstrapInflationCurveResult::VT_PILLAR_DATES, pillar_dates);
  }
  void add_error(::flatbuffers::Offset<quantra::Error> error) {
    fbb_.AddOffset(BootstrapInflationCurveResult::VT_ERROR, error);
  }
  explicit BootstrapInflationCurveResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BootstrapInflationCurveResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BootstrapInflationCurveResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BootstrapInflationCurveResult> CreateBootstrapInflationCurveResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> reference_date = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> grid_dates = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveSeries>>> series = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> pillar_dates = 0,
    ::flatbuffers::Offset<quantra::Error> error = 0) {
  BootstrapInflationCurveResultBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_pillar_dates(pillar_dates);
  builder_.add_series(series);
  builder_.add_grid_dates(grid_dates);
  builder_.add_reference_date(reference_date);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BootstrapInflationCurveResult> CreateBootstrapInflationCurveResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *reference_date = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *grid_dates = nullptr,
    const std::vector<::flatbuffers::Offset<quantra::InflationCurveSeries>> *series = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *pillar_dates = nullptr,
    ::flatbuffers::Offset<quantra::Error> error = 0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto reference_date__ = reference_date ? _fbb.CreateString(reference_date) : 0;
  auto grid_dates__ = grid_dates ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*grid_dates) : 0;
  auto series__ = series ? _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationCurveSeries>>(*series) : 0;
  auto pillar_dates__ = pillar_dates ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*pillar_dates) : 0;
  return quantra::CreateBootstrapInflationCurveResult(
      _fbb,
      id__,
      reference_date__,
      grid_dates__,
      series__,
      pillar_dates__,
      error);
}

::flatbuffers::Offset<BootstrapInflationCurveResult> CreateBootstrapInflationCurveResult(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurveResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BootstrapInflationCurvesResponseT : public ::flatbuffers::NativeTable {
  typedef BootstrapInflationCurvesResponse TableType;
  std::vector<std::unique_ptr<quantra::BootstrapInflationCurveResultT>> results{};
  BootstrapInflationCurvesResponseT() = default;
  BootstrapInflationCurvesResponseT(const BootstrapInflationCurvesResponseT &o);
  BootstrapInflationCurvesResponseT(BootstrapInflationCurvesResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  BootstrapInflationCurvesResponseT &operator=(BootstrapInflationCurvesResponseT o) FLATBUFFERS_NOEXCEPT;
};

/// Response for all requested inflation curve queries.
struct BootstrapInflationCurvesResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BootstrapInflationCurvesResponseT NativeTableType;
  typedef BootstrapInflationCurvesResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>> *results() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>> *>(VT_RESULTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RESULTS) &&
           verifier.VerifyVector(results()) &&
           verifier.VerifyVectorOfTables(results()) &&
           verifier.EndTable();
  }
  BootstrapInflationCurvesResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BootstrapInflationCurvesResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BootstrapInflationCurvesResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BootstrapInflationCurvesResponseBuilder {
  typedef BootstrapInflationCurvesResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_results(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>>> results) {
    fbb_.AddOffset(BootstrapInflationCurvesResponse::VT_RESULTS, results);
  }
  explicit BootstrapInflationCurvesResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BootstrapInflationCurvesResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BootstrapInflationCurvesResponse>(end);
    fbb_.Required(o, BootstrapInflationCurvesResponse::VT_RESULTS);
    return o;
  }
};

inline ::flatbuffers::Offset<BootstrapInflationCurvesResponse> CreateBootstrapInflationCurvesResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>>> results = 0) {
  BootstrapInflationCurvesResponseBuilder builder_(_fbb);
  builder_.add_results(results);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BootstrapInflationCurvesResponse> CreateBootstrapInflationCurvesResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>> *results = nullptr) {
  auto results__ = results ? _fbb.CreateVector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>>(*results) : 0;
  return quantra::CreateBootstrapInflationCurvesResponse(
      _fbb,
      results__);
}

::flatbuffers::Offset<BootstrapInflationCurvesResponse> CreateBootstrapInflationCurvesResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline InflationCurveSeriesT *InflationCurveSeries::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InflationCurveSeriesT>(new InflationCurveSeriesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InflationCurveSeries::UnPackTo(InflationCurveSeriesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = measure(); _o->measure = _e; }
  { auto _e = values(); if (_e) { _o->values.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->values[_i] = _e->Get(_i); } } else { _o->values.resize(0); } }
}

inline ::flatbuffers::Offset<InflationCurveSeries> InflationCurveSeries::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSeriesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInflationCurveSeries(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InflationCurveSeries> CreateInflationCurveSeries(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSeriesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InflationCurveSeriesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _measure = _o->measure;
  auto _values = _fbb.CreateVector(_o->values);
  return quantra::CreateInflationCurveSeries(
      _fbb,
      _measure,
      _values);
}

inline BootstrapInflationCurveResultT::BootstrapInflationCurveResultT(const BootstrapInflationCurveResultT &o)
      : id(o.id),
        reference_date(o.reference_date),
        grid_dates(o.grid_dates),
        pillar_dates(o.pillar_dates),
        error((o.error) ? new quantra::ErrorT(*o.error) : nullptr) {
  series.reserve(o.series.size());
  for (const auto &series_ : o.series) { series.emplace_back((series_) ? new quantra::InflationCurveSeriesT(*series_) : nullptr); }
}

inline BootstrapInflationCurveResultT &BootstrapInflationCurveResultT::operator=(BootstrapInflationCurveResultT o) FLATBUFFERS_NOEXCEPT {
  std::swap(id, o.id);
  std::swap(reference_date, o.reference_date);
  std::swap(grid_dates, o.grid_dates);
  std::swap(series, o.series);
  std::swap(pillar_dates, o.pillar_dates);
  std::swap(error, o.error);
  return *this;
}

inline BootstrapInflationCurveResultT *BootstrapInflationCurveResult::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BootstrapInflationCurveResultT>(new BootstrapInflationCurveResultT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BootstrapInflationCurveResult::UnPackTo(BootstrapInflationCurveResultT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = reference_date(); if (_e) _o->reference_date = _e->str(); }
  { auto _e = grid_dates(); if (_e) { _o->grid_dates.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->grid_dates[_i] = _e->Get(_i)->str(); } } else { _o->grid_dates.resize(0); } }
  { auto _e = series(); if (_e) { _o->series.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->series[_i]) { _e->Get(_i)->UnPackTo(_o->series[_i].get(), _resolver); } else { _o->series[_i] = std::unique_ptr<quantra::InflationCurveSeriesT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->series.resize(0); } }
  { auto _e = pillar_dates(); if (_e) { _o->pillar_dates.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->pillar_dates[_i] = _e->Get(_i)->str(); } } else { _o->pillar_dates.resize(0); } }
  { auto _e = error(); if (_e) { if(_o->error) { _e->UnPackTo(_o->error.get(), _resolver); } else { _o->error = std::unique_ptr<quantra::ErrorT>(_e->UnPack(_resolver)); } } else if (_o->error) { _o->error.reset(); } }
}

inline ::flatbuffers::Offset<BootstrapInflationCurveResult> BootstrapInflationCurveResult::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurveResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBootstrapInflationCurveResult(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BootstrapInflationCurveResult> CreateBootstrapInflationCurveResult(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurveResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BootstrapInflationCurveResultT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id.empty() ? 0 : _fbb.CreateString(_o->id);
  auto _reference_date = _o->reference_date.empty() ? 0 : _fbb.CreateString(_o->reference_date);
  auto _grid_dates = _o->grid_dates.size() ? _fbb.CreateVectorOfStrings(_o->grid_dates) : 0;
  auto _series = _o->series.size() ? _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationCurveSeries>> (_o->series.size(), [](size_t i, _VectorArgs *__va) { return CreateInflationCurveSeries(*__va->__fbb, __va->__o->series[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _pillar_dates = _o->pillar_dates.size() ? _fbb.CreateVectorOfStrings(_o->pillar_dates) : 0;
  auto _error = _o->error ? CreateError(_fbb, _o->error.get(), _rehasher) : 0;
  return quantra::CreateBootstrapInflationCurveResult(
      _fbb,
      _id,
      _reference_date,
      _grid_dates,
      _series,
      _pillar_dates,
      _error);
}

inline BootstrapInflationCurvesResponseT::BootstrapInflationCurvesResponseT(const BootstrapInflationCurvesResponseT &o) {
  results.reserve(o.results.size());
  for (const auto &results_ : o.results) { results.emplace_back((results_) ? new quantra::BootstrapInflationCurveResultT(*results_) : nullptr); }
}

inline BootstrapInflationCurvesResponseT &BootstrapInflationCurvesResponseT::operator=(BootstrapInflationCurvesResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(results, o.results);
  return *this;
}

inline BootstrapInflationCurvesResponseT *BootstrapInflationCurvesResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BootstrapInflationCurvesResponseT>(new BootstrapInflationCurvesResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BootstrapInflationCurvesResponse::UnPackTo(BootstrapInflationCurvesResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = results(); if (_e) { _o->results.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->results[_i]) { _e->Get(_i)->UnPackTo(_o->results[_i].get(), _resolver); } else { _o->results[_i] = std::unique_ptr<quantra::BootstrapInflationCurveResultT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->results.resize(0); } }
}

inline ::flatbuffers::Offset<BootstrapInflationCurvesResponse> BootstrapInflationCurvesResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBootstrapInflationCurvesResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BootstrapInflationCurvesResponse> CreateBootstrapInflationCurvesResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BootstrapInflationCurvesResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _results = _fbb.CreateVector<::flatbuffers::Offset<quantra::BootstrapInflationCurveResult>> (_o->results.size(), [](size_t i, _VectorArgs *__va) { return CreateBootstrapInflationCurveResult(*__va->__fbb, __va->__o->results[i].get(), __va->__rehasher); }, &_va );
  return quantra::CreateBootstrapInflationCurvesResponse(
      _fbb,
      _results);
}

inline const quantra::BootstrapInflationCurvesResponse *GetBootstrapInflationCurvesResponse(const void *buf) {
  return ::flatbuffers::GetRoot<quantra::BootstrapInflationCurvesResponse>(buf);
}

inline const quantra::BootstrapInflationCurvesResponse *GetSizePrefixedBootstrapInflationCurvesResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<quantra::BootstrapInflationCurvesResponse>(buf);
}

inline bool VerifyBootstrapInflationCurvesResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<quantra::BootstrapInflationCurvesResponse>(nullptr);
}

inline bool VerifySizePrefixedBootstrapInflationCurvesResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<quantra::BootstrapInflationCurvesResponse>(nullptr);
}

inline void FinishBootstrapInflationCurvesResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::BootstrapInflationCurvesResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBootstrapInflationCurvesResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::BootstrapInflationCurvesResponse> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<quantra::BootstrapInflationCurvesResponseT> UnPackBootstrapInflationCurvesResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::BootstrapInflationCurvesResponseT>(GetBootstrapInflationCurvesResponse(buf)->UnPack(res));
}

inline std::unique_ptr<quantra::BootstrapInflationCurvesResponseT> UnPackSizePrefixedBootstrapInflationCurvesResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::BootstrapInflationCurvesResponseT>(GetSizePrefixedBootstrapInflationCurvesResponse(buf)->UnPack(res));
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_BOOTSTRAPINFLATIONCURVESRESPONSE_QUANTRA_H_
