// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BOOTSTRAPINFLATIONCURVESREQUEST_QUANTRA_H_
#define FLATBUFFERS_GENERATED_BOOTSTRAPINFLATIONCURVESREQUEST_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"
#include "inflation_curve_query_generated.h"
#include "pricing_generated.h"

namespace quantra {

struct BootstrapInflationCurvesRequest;
struct BootstrapInflationCurvesRequestBuilder;
struct BootstrapInflationCurvesRequestT;

struct BootstrapInflationCurvesRequestT : public ::flatbuffers::NativeTable {
  typedef BootstrapInflationCurvesRequest TableType;
  std::unique_ptr<quantra::PricingT> pricing{};
  std::vector<std::unique_ptr<quantra::InflationCurveQuerySpecT>> queries{};
  BootstrapInflationCurvesRequestT() = default;
  BootstrapInflationCurvesRequestT(const BootstrapInflationCurvesRequestT &o);
  BootstrapInflationCurvesRequestT(BootstrapInflationCurvesRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  BootstrapInflationCurvesRequestT &operator=(BootstrapInflationCurvesRequestT o) FLATBUFFERS_NOEXCEPT;
};

/// Request to bootstrap inflation curves from Pricing and sample them by query.
struct BootstrapInflationCurvesRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BootstrapInflationCurvesRequestT NativeTableType;
  typedef BootstrapInflationCurvesRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PRICING = 4,
    VT_QUERIES = 6
  };
  const quantra::Pricing *pricing() const {
    return GetPointer<const quantra::Pricing *>(VT_PRICING);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>> *queries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>> *>(VT_QUERIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PRICING) &&
           verifier.VerifyTable(pricing()) &&
           VerifyOffsetRequired(verifier, VT_QUERIES) &&
           verifier.VerifyVector(queries()) &&
           verifier.VerifyVectorOfTables(queries()) &&
           verifier.EndTable();
  }
  BootstrapInflationCurvesRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BootstrapInflationCurvesRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BootstrapInflationCurvesRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BootstrapInflationCurvesRequestBuilder {
  typedef BootstrapInflationCurvesRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pricing(::flatbuffers::Offset<quantra::Pricing> pricing) {
    fbb_.AddOffset(BootstrapInflationCurvesRequest::VT_PRICING, pricing);
  }
  void add_queries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>>> queries) {
    fbb_.AddOffset(BootstrapInflationCurvesRequest::VT_QUERIES, queries);
  }
  explicit BootstrapInflationCurvesRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BootstrapInflationCurvesRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BootstrapInflationCurvesRequest>(end);
    fbb_.Required(o, BootstrapInflationCurvesRequest::VT_PRICING);
    fbb_.Required(o, BootstrapInflationCurvesRequest::VT_QUERIES);
    return o;
  }
};

inline ::flatbuffers::Offset<BootstrapInflationCurvesRequest> CreateBootstrapInflationCurvesRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::Pricing> pricing = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>>> queries = 0) {
  BootstrapInflationCurvesRequestBuilder builder_(_fbb);
  builder_.add_queries(queries);
  builder_.add_pricing(pricing);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BootstrapInflationCurvesRequest> CreateBootstrapInflationCurvesRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::Pricing> pricing = 0,
    const std::vector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>> *queries = nullptr) {
  auto queries__ = queries ? _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>>(*queries) : 0;
  return quantra::CreateBootstrapInflationCurvesRequest(
      _fbb,
      pricing,
      queries__);
}

::flatbuffers::Offset<BootstrapInflationCurvesRequest> CreateBootstrapInflationCurvesRequest(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BootstrapInflationCurvesRequestT::BootstrapInflationCurvesRequestT(const BootstrapInflationCurvesRequestT &o)
      : pricing((o.pricing) ? new quantra::PricingT(*o.pricing) : nullptr) {
  queries.reserve(o.queries.size());
  for (const auto &queries_ : o.queries) { queries.emplace_back((queries_) ? new quantra::InflationCurveQuerySpecT(*queries_) : nullptr); }
}

inline BootstrapInflationCurvesRequestT &BootstrapInflationCurvesRequestT::operator=(BootstrapInflationCurvesRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(pricing, o.pricing);
  std::swap(queries, o.queries);
  return *this;
}

inline BootstrapInflationCurvesRequestT *BootstrapInflationCurvesRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BootstrapInflationCurvesRequestT>(new BootstrapInflationCurvesRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BootstrapInflationCurvesRequest::UnPackTo(BootstrapInflationCurvesRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pricing(); if (_e) { if(_o->pricing) { _e->UnPackTo(_o->pricing.get(), _resolver); } else { _o->pricing = std::unique_ptr<quantra::PricingT>(_e->UnPack(_resolver)); } } else if (_o->pricing) { _o->pricing.reset(); } }
  { auto _e = queries(); if (_e) { _o->queries.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->queries[_i]) { _e->Get(_i)->UnPackTo(_o->queries[_i].get(), _resolver); } else { _o->queries[_i] = std::unique_ptr<quantra::InflationCurveQuerySpecT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->queries.resize(0); } }
}

inline ::flatbuffers::Offset<BootstrapInflationCurvesRequest> BootstrapInflationCurvesRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBootstrapInflationCurvesRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BootstrapInflationCurvesRequest> CreateBootstrapInflationCurvesRequest(::flatbuffers::FlatBufferBuilder &_fbb, const BootstrapInflationCurvesRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BootstrapInflationCurvesRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pricing = _o->pricing ? CreatePricing(_fbb, _o->pricing.get(), _rehasher) : 0;
  auto _queries = _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationCurveQuerySpec>> (_o->queries.size(), [](size_t i, _VectorArgs *__va) { return CreateInflationCurveQuerySpec(*__va->__fbb, __va->__o->queries[i].get(), __va->__rehasher); }, &_va );
  return quantra::CreateBootstrapInflationCurvesRequest(
      _fbb,
      _pricing,
      _queries);
}

inline const quantra::BootstrapInflationCurvesRequest *GetBootstrapInflationCurvesRequest(const void *buf) {
  return ::flatbuffers::GetRoot<quantra::BootstrapInflationCurvesRequest>(buf);
}

inline const quantra::BootstrapInflationCurvesRequest *GetSizePrefixedBootstrapInflationCurvesRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<quantra::BootstrapInflationCurvesRequest>(buf);
}

inline bool VerifyBootstrapInflationCurvesRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<quantra::BootstrapInflationCurvesRequest>(nullptr);
}

inline bool VerifySizePrefixedBootstrapInflationCurvesRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<quantra::BootstrapInflationCurvesRequest>(nullptr);
}

inline void FinishBootstrapInflationCurvesRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::BootstrapInflationCurvesRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBootstrapInflationCurvesRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::BootstrapInflationCurvesRequest> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<quantra::BootstrapInflationCurvesRequestT> UnPackBootstrapInflationCurvesRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::BootstrapInflationCurvesRequestT>(GetBootstrapInflationCurvesRequest(buf)->UnPack(res));
}

inline std::unique_ptr<quantra::BootstrapInflationCurvesRequestT> UnPackSizePrefixedBootstrapInflationCurvesRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::BootstrapInflationCurvesRequestT>(GetSizePrefixedBootstrapInflationCurvesRequest(buf)->UnPack(res));
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_BOOTSTRAPINFLATIONCURVESREQUEST_QUANTRA_H_
