// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CAPFLOOR_QUANTRA_H_
#define FLATBUFFERS_GENERATED_CAPFLOOR_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "enums_generated.h"
#include "index_generated.h"
#include "schedule_generated.h"

namespace quantra {

struct CapFloor;
struct CapFloorBuilder;
struct CapFloorT;

struct CapFloorT : public ::flatbuffers::NativeTable {
  typedef CapFloor TableType;
  quantra::enums::CapFloorType cap_floor_type = quantra::enums::CapFloorType_Cap;
  double notional = 0.0;
  double strike = 0.0;
  std::unique_ptr<quantra::ScheduleT> schedule{};
  std::unique_ptr<quantra::IndexT> index{};
  quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual360;
  quantra::enums::BusinessDayConvention business_day_convention = quantra::enums::BusinessDayConvention_Following;
  CapFloorT() = default;
  CapFloorT(const CapFloorT &o);
  CapFloorT(CapFloorT&&) FLATBUFFERS_NOEXCEPT = default;
  CapFloorT &operator=(CapFloorT o) FLATBUFFERS_NOEXCEPT;
};

struct CapFloor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CapFloorT NativeTableType;
  typedef CapFloorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAP_FLOOR_TYPE = 4,
    VT_NOTIONAL = 6,
    VT_STRIKE = 8,
    VT_SCHEDULE = 10,
    VT_INDEX = 12,
    VT_DAY_COUNTER = 14,
    VT_BUSINESS_DAY_CONVENTION = 16
  };
  quantra::enums::CapFloorType cap_floor_type() const {
    return static_cast<quantra::enums::CapFloorType>(GetField<int8_t>(VT_CAP_FLOOR_TYPE, 0));
  }
  double notional() const {
    return GetField<double>(VT_NOTIONAL, 0.0);
  }
  double strike() const {
    return GetField<double>(VT_STRIKE, 0.0);
  }
  const quantra::Schedule *schedule() const {
    return GetPointer<const quantra::Schedule *>(VT_SCHEDULE);
  }
  const quantra::Index *index() const {
    return GetPointer<const quantra::Index *>(VT_INDEX);
  }
  quantra::enums::DayCounter day_counter() const {
    return static_cast<quantra::enums::DayCounter>(GetField<int8_t>(VT_DAY_COUNTER, 0));
  }
  quantra::enums::BusinessDayConvention business_day_convention() const {
    return static_cast<quantra::enums::BusinessDayConvention>(GetField<int8_t>(VT_BUSINESS_DAY_CONVENTION, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CAP_FLOOR_TYPE, 1) &&
           VerifyField<double>(verifier, VT_NOTIONAL, 8) &&
           VerifyField<double>(verifier, VT_STRIKE, 8) &&
           VerifyOffset(verifier, VT_SCHEDULE) &&
           verifier.VerifyTable(schedule()) &&
           VerifyOffset(verifier, VT_INDEX) &&
           verifier.VerifyTable(index()) &&
           VerifyField<int8_t>(verifier, VT_DAY_COUNTER, 1) &&
           VerifyField<int8_t>(verifier, VT_BUSINESS_DAY_CONVENTION, 1) &&
           verifier.EndTable();
  }
  CapFloorT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CapFloorT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CapFloor> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CapFloorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CapFloorBuilder {
  typedef CapFloor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cap_floor_type(quantra::enums::CapFloorType cap_floor_type) {
    fbb_.AddElement<int8_t>(CapFloor::VT_CAP_FLOOR_TYPE, static_cast<int8_t>(cap_floor_type), 0);
  }
  void add_notional(double notional) {
    fbb_.AddElement<double>(CapFloor::VT_NOTIONAL, notional, 0.0);
  }
  void add_strike(double strike) {
    fbb_.AddElement<double>(CapFloor::VT_STRIKE, strike, 0.0);
  }
  void add_schedule(::flatbuffers::Offset<quantra::Schedule> schedule) {
    fbb_.AddOffset(CapFloor::VT_SCHEDULE, schedule);
  }
  void add_index(::flatbuffers::Offset<quantra::Index> index) {
    fbb_.AddOffset(CapFloor::VT_INDEX, index);
  }
  void add_day_counter(quantra::enums::DayCounter day_counter) {
    fbb_.AddElement<int8_t>(CapFloor::VT_DAY_COUNTER, static_cast<int8_t>(day_counter), 0);
  }
  void add_business_day_convention(quantra::enums::BusinessDayConvention business_day_convention) {
    fbb_.AddElement<int8_t>(CapFloor::VT_BUSINESS_DAY_CONVENTION, static_cast<int8_t>(business_day_convention), 0);
  }
  explicit CapFloorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CapFloor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CapFloor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CapFloor> CreateCapFloor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    quantra::enums::CapFloorType cap_floor_type = quantra::enums::CapFloorType_Cap,
    double notional = 0.0,
    double strike = 0.0,
    ::flatbuffers::Offset<quantra::Schedule> schedule = 0,
    ::flatbuffers::Offset<quantra::Index> index = 0,
    quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual360,
    quantra::enums::BusinessDayConvention business_day_convention = quantra::enums::BusinessDayConvention_Following) {
  CapFloorBuilder builder_(_fbb);
  builder_.add_strike(strike);
  builder_.add_notional(notional);
  builder_.add_index(index);
  builder_.add_schedule(schedule);
  builder_.add_business_day_convention(business_day_convention);
  builder_.add_day_counter(day_counter);
  builder_.add_cap_floor_type(cap_floor_type);
  return builder_.Finish();
}

::flatbuffers::Offset<CapFloor> CreateCapFloor(::flatbuffers::FlatBufferBuilder &_fbb, const CapFloorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CapFloorT::CapFloorT(const CapFloorT &o)
      : cap_floor_type(o.cap_floor_type),
        notional(o.notional),
        strike(o.strike),
        schedule((o.schedule) ? new quantra::ScheduleT(*o.schedule) : nullptr),
        index((o.index) ? new quantra::IndexT(*o.index) : nullptr),
        day_counter(o.day_counter),
        business_day_convention(o.business_day_convention) {
}

inline CapFloorT &CapFloorT::operator=(CapFloorT o) FLATBUFFERS_NOEXCEPT {
  std::swap(cap_floor_type, o.cap_floor_type);
  std::swap(notional, o.notional);
  std::swap(strike, o.strike);
  std::swap(schedule, o.schedule);
  std::swap(index, o.index);
  std::swap(day_counter, o.day_counter);
  std::swap(business_day_convention, o.business_day_convention);
  return *this;
}

inline CapFloorT *CapFloor::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CapFloorT>(new CapFloorT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CapFloor::UnPackTo(CapFloorT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cap_floor_type(); _o->cap_floor_type = _e; }
  { auto _e = notional(); _o->notional = _e; }
  { auto _e = strike(); _o->strike = _e; }
  { auto _e = schedule(); if (_e) { if(_o->schedule) { _e->UnPackTo(_o->schedule.get(), _resolver); } else { _o->schedule = std::unique_ptr<quantra::ScheduleT>(_e->UnPack(_resolver)); } } else if (_o->schedule) { _o->schedule.reset(); } }
  { auto _e = index(); if (_e) { if(_o->index) { _e->UnPackTo(_o->index.get(), _resolver); } else { _o->index = std::unique_ptr<quantra::IndexT>(_e->UnPack(_resolver)); } } else if (_o->index) { _o->index.reset(); } }
  { auto _e = day_counter(); _o->day_counter = _e; }
  { auto _e = business_day_convention(); _o->business_day_convention = _e; }
}

inline ::flatbuffers::Offset<CapFloor> CapFloor::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CapFloorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCapFloor(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CapFloor> CreateCapFloor(::flatbuffers::FlatBufferBuilder &_fbb, const CapFloorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CapFloorT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cap_floor_type = _o->cap_floor_type;
  auto _notional = _o->notional;
  auto _strike = _o->strike;
  auto _schedule = _o->schedule ? CreateSchedule(_fbb, _o->schedule.get(), _rehasher) : 0;
  auto _index = _o->index ? CreateIndex(_fbb, _o->index.get(), _rehasher) : 0;
  auto _day_counter = _o->day_counter;
  auto _business_day_convention = _o->business_day_convention;
  return quantra::CreateCapFloor(
      _fbb,
      _cap_floor_type,
      _notional,
      _strike,
      _schedule,
      _index,
      _day_counter,
      _business_day_convention);
}

inline const quantra::CapFloor *GetCapFloor(const void *buf) {
  return ::flatbuffers::GetRoot<quantra::CapFloor>(buf);
}

inline const quantra::CapFloor *GetSizePrefixedCapFloor(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<quantra::CapFloor>(buf);
}

inline bool VerifyCapFloorBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<quantra::CapFloor>(nullptr);
}

inline bool VerifySizePrefixedCapFloorBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<quantra::CapFloor>(nullptr);
}

inline void FinishCapFloorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::CapFloor> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCapFloorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::CapFloor> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<quantra::CapFloorT> UnPackCapFloor(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::CapFloorT>(GetCapFloor(buf)->UnPack(res));
}

inline std::unique_ptr<quantra::CapFloorT> UnPackSizePrefixedCapFloor(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::CapFloorT>(GetSizePrefixedCapFloor(buf)->UnPack(res));
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_CAPFLOOR_QUANTRA_H_
