// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INFLATION_QUANTRA_H_
#define FLATBUFFERS_GENERATED_INFLATION_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"
#include "enums_generated.h"

namespace quantra {

struct InflationIndexSpec;
struct InflationIndexSpecBuilder;
struct InflationIndexSpecT;

struct InflationCurveBaseSpec;
struct InflationCurveBaseSpecBuilder;
struct InflationCurveBaseSpecT;

struct InflationSwapPillar;
struct InflationSwapPillarBuilder;
struct InflationSwapPillarT;

struct ZeroInflationCurveFromZcSwapsSpec;
struct ZeroInflationCurveFromZcSwapsSpecBuilder;
struct ZeroInflationCurveFromZcSwapsSpecT;

struct YoYInflationCurveFromYoYSwapsSpec;
struct YoYInflationCurveFromYoYSwapsSpecBuilder;
struct YoYInflationCurveFromYoYSwapsSpecT;

struct InflationCurveSpec;
struct InflationCurveSpecBuilder;
struct InflationCurveSpecT;

enum InflationCurvePayload : uint8_t {
  InflationCurvePayload_NONE = 0,
  InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec = 1,
  InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec = 2,
  InflationCurvePayload_MIN = InflationCurvePayload_NONE,
  InflationCurvePayload_MAX = InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec
};

inline const InflationCurvePayload (&EnumValuesInflationCurvePayload())[3] {
  static const InflationCurvePayload values[] = {
    InflationCurvePayload_NONE,
    InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec,
    InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec
  };
  return values;
}

inline const char * const *EnumNamesInflationCurvePayload() {
  static const char * const names[4] = {
    "NONE",
    "ZeroInflationCurveFromZcSwapsSpec",
    "YoYInflationCurveFromYoYSwapsSpec",
    nullptr
  };
  return names;
}

inline const char *EnumNameInflationCurvePayload(InflationCurvePayload e) {
  if (::flatbuffers::IsOutRange(e, InflationCurvePayload_NONE, InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesInflationCurvePayload()[index];
}

template<typename T> struct InflationCurvePayloadTraits {
  static const InflationCurvePayload enum_value = InflationCurvePayload_NONE;
};

template<> struct InflationCurvePayloadTraits<quantra::ZeroInflationCurveFromZcSwapsSpec> {
  static const InflationCurvePayload enum_value = InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec;
};

template<> struct InflationCurvePayloadTraits<quantra::YoYInflationCurveFromYoYSwapsSpec> {
  static const InflationCurvePayload enum_value = InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec;
};

template<typename T> struct InflationCurvePayloadUnionTraits {
  static const InflationCurvePayload enum_value = InflationCurvePayload_NONE;
};

template<> struct InflationCurvePayloadUnionTraits<quantra::ZeroInflationCurveFromZcSwapsSpecT> {
  static const InflationCurvePayload enum_value = InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec;
};

template<> struct InflationCurvePayloadUnionTraits<quantra::YoYInflationCurveFromYoYSwapsSpecT> {
  static const InflationCurvePayload enum_value = InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec;
};

struct InflationCurvePayloadUnion {
  InflationCurvePayload type;
  void *value;

  InflationCurvePayloadUnion() : type(InflationCurvePayload_NONE), value(nullptr) {}
  InflationCurvePayloadUnion(InflationCurvePayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(InflationCurvePayload_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  InflationCurvePayloadUnion(const InflationCurvePayloadUnion &);
  InflationCurvePayloadUnion &operator=(const InflationCurvePayloadUnion &u)
    { InflationCurvePayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  InflationCurvePayloadUnion &operator=(InflationCurvePayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~InflationCurvePayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = InflationCurvePayloadUnionTraits<RT>::enum_value;
    if (type != InflationCurvePayload_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, InflationCurvePayload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  quantra::ZeroInflationCurveFromZcSwapsSpecT *AsZeroInflationCurveFromZcSwapsSpec() {
    return type == InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec ?
      reinterpret_cast<quantra::ZeroInflationCurveFromZcSwapsSpecT *>(value) : nullptr;
  }
  const quantra::ZeroInflationCurveFromZcSwapsSpecT *AsZeroInflationCurveFromZcSwapsSpec() const {
    return type == InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec ?
      reinterpret_cast<const quantra::ZeroInflationCurveFromZcSwapsSpecT *>(value) : nullptr;
  }
  quantra::YoYInflationCurveFromYoYSwapsSpecT *AsYoYInflationCurveFromYoYSwapsSpec() {
    return type == InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec ?
      reinterpret_cast<quantra::YoYInflationCurveFromYoYSwapsSpecT *>(value) : nullptr;
  }
  const quantra::YoYInflationCurveFromYoYSwapsSpecT *AsYoYInflationCurveFromYoYSwapsSpec() const {
    return type == InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec ?
      reinterpret_cast<const quantra::YoYInflationCurveFromYoYSwapsSpecT *>(value) : nullptr;
  }
};

bool VerifyInflationCurvePayload(::flatbuffers::Verifier &verifier, const void *obj, InflationCurvePayload type);
bool VerifyInflationCurvePayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct InflationIndexSpecT : public ::flatbuffers::NativeTable {
  typedef InflationIndexSpec TableType;
  std::string id{};
  std::string family_name{};
  std::string currency{};
  quantra::enums::Calendar calendar = quantra::enums::Calendar_TARGET;
  quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual365Fixed;
  quantra::enums::Frequency frequency = quantra::enums::Frequency_Monthly;
  std::unique_ptr<quantra::PeriodT> availability_lag{};
  std::unique_ptr<quantra::PeriodT> observation_lag{};
  bool interpolated = true;
  bool revised = false;
  quantra::enums::InflationCurveKind kind = quantra::enums::InflationCurveKind_ZeroInflation;
  InflationIndexSpecT() = default;
  InflationIndexSpecT(const InflationIndexSpecT &o);
  InflationIndexSpecT(InflationIndexSpecT&&) FLATBUFFERS_NOEXCEPT = default;
  InflationIndexSpecT &operator=(InflationIndexSpecT o) FLATBUFFERS_NOEXCEPT;
};

/// Inflation index specification. Registered once per request, referenced by id.
struct InflationIndexSpec FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InflationIndexSpecT NativeTableType;
  typedef InflationIndexSpecBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_FAMILY_NAME = 6,
    VT_CURRENCY = 8,
    VT_CALENDAR = 10,
    VT_DAY_COUNTER = 12,
    VT_FREQUENCY = 14,
    VT_AVAILABILITY_LAG = 16,
    VT_OBSERVATION_LAG = 18,
    VT_INTERPOLATED = 20,
    VT_REVISED = 22,
    VT_KIND = 24
  };
  /// Unique identifier (e.g., "UKRPI", "EUHICP", "USCPI").
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  /// Human-readable family name.
  const ::flatbuffers::String *family_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FAMILY_NAME);
  }
  /// ISO currency code (e.g., "GBP", "EUR", "USD").
  const ::flatbuffers::String *currency() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CURRENCY);
  }
  quantra::enums::Calendar calendar() const {
    return static_cast<quantra::enums::Calendar>(GetField<int8_t>(VT_CALENDAR, 32));
  }
  quantra::enums::DayCounter day_counter() const {
    return static_cast<quantra::enums::DayCounter>(GetField<int8_t>(VT_DAY_COUNTER, 1));
  }
  quantra::enums::Frequency frequency() const {
    return static_cast<quantra::enums::Frequency>(GetField<int8_t>(VT_FREQUENCY, 6));
  }
  /// Publication availability lag (e.g., 2 Months).
  const quantra::Period *availability_lag() const {
    return GetPointer<const quantra::Period *>(VT_AVAILABILITY_LAG);
  }
  /// Observation lag used for swaps (e.g., 3 Months).
  const quantra::Period *observation_lag() const {
    return GetPointer<const quantra::Period *>(VT_OBSERVATION_LAG);
  }
  /// Whether the index is interpolated between fixings.
  bool interpolated() const {
    return GetField<uint8_t>(VT_INTERPOLATED, 1) != 0;
  }
  /// Whether index values can be revised (rare; defaults to false).
  bool revised() const {
    return GetField<uint8_t>(VT_REVISED, 0) != 0;
  }
  quantra::enums::InflationCurveKind kind() const {
    return static_cast<quantra::enums::InflationCurveKind>(GetField<int8_t>(VT_KIND, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_FAMILY_NAME) &&
           verifier.VerifyString(family_name()) &&
           VerifyOffset(verifier, VT_CURRENCY) &&
           verifier.VerifyString(currency()) &&
           VerifyField<int8_t>(verifier, VT_CALENDAR, 1) &&
           VerifyField<int8_t>(verifier, VT_DAY_COUNTER, 1) &&
           VerifyField<int8_t>(verifier, VT_FREQUENCY, 1) &&
           VerifyOffset(verifier, VT_AVAILABILITY_LAG) &&
           verifier.VerifyTable(availability_lag()) &&
           VerifyOffset(verifier, VT_OBSERVATION_LAG) &&
           verifier.VerifyTable(observation_lag()) &&
           VerifyField<uint8_t>(verifier, VT_INTERPOLATED, 1) &&
           VerifyField<uint8_t>(verifier, VT_REVISED, 1) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           verifier.EndTable();
  }
  InflationIndexSpecT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InflationIndexSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InflationIndexSpec> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationIndexSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InflationIndexSpecBuilder {
  typedef InflationIndexSpec Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(InflationIndexSpec::VT_ID, id);
  }
  void add_family_name(::flatbuffers::Offset<::flatbuffers::String> family_name) {
    fbb_.AddOffset(InflationIndexSpec::VT_FAMILY_NAME, family_name);
  }
  void add_currency(::flatbuffers::Offset<::flatbuffers::String> currency) {
    fbb_.AddOffset(InflationIndexSpec::VT_CURRENCY, currency);
  }
  void add_calendar(quantra::enums::Calendar calendar) {
    fbb_.AddElement<int8_t>(InflationIndexSpec::VT_CALENDAR, static_cast<int8_t>(calendar), 32);
  }
  void add_day_counter(quantra::enums::DayCounter day_counter) {
    fbb_.AddElement<int8_t>(InflationIndexSpec::VT_DAY_COUNTER, static_cast<int8_t>(day_counter), 1);
  }
  void add_frequency(quantra::enums::Frequency frequency) {
    fbb_.AddElement<int8_t>(InflationIndexSpec::VT_FREQUENCY, static_cast<int8_t>(frequency), 6);
  }
  void add_availability_lag(::flatbuffers::Offset<quantra::Period> availability_lag) {
    fbb_.AddOffset(InflationIndexSpec::VT_AVAILABILITY_LAG, availability_lag);
  }
  void add_observation_lag(::flatbuffers::Offset<quantra::Period> observation_lag) {
    fbb_.AddOffset(InflationIndexSpec::VT_OBSERVATION_LAG, observation_lag);
  }
  void add_interpolated(bool interpolated) {
    fbb_.AddElement<uint8_t>(InflationIndexSpec::VT_INTERPOLATED, static_cast<uint8_t>(interpolated), 1);
  }
  void add_revised(bool revised) {
    fbb_.AddElement<uint8_t>(InflationIndexSpec::VT_REVISED, static_cast<uint8_t>(revised), 0);
  }
  void add_kind(quantra::enums::InflationCurveKind kind) {
    fbb_.AddElement<int8_t>(InflationIndexSpec::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  explicit InflationIndexSpecBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InflationIndexSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InflationIndexSpec>(end);
    fbb_.Required(o, InflationIndexSpec::VT_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<InflationIndexSpec> CreateInflationIndexSpec(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> family_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> currency = 0,
    quantra::enums::Calendar calendar = quantra::enums::Calendar_TARGET,
    quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual365Fixed,
    quantra::enums::Frequency frequency = quantra::enums::Frequency_Monthly,
    ::flatbuffers::Offset<quantra::Period> availability_lag = 0,
    ::flatbuffers::Offset<quantra::Period> observation_lag = 0,
    bool interpolated = true,
    bool revised = false,
    quantra::enums::InflationCurveKind kind = quantra::enums::InflationCurveKind_ZeroInflation) {
  InflationIndexSpecBuilder builder_(_fbb);
  builder_.add_observation_lag(observation_lag);
  builder_.add_availability_lag(availability_lag);
  builder_.add_currency(currency);
  builder_.add_family_name(family_name);
  builder_.add_id(id);
  builder_.add_kind(kind);
  builder_.add_revised(revised);
  builder_.add_interpolated(interpolated);
  builder_.add_frequency(frequency);
  builder_.add_day_counter(day_counter);
  builder_.add_calendar(calendar);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<InflationIndexSpec> CreateInflationIndexSpecDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *family_name = nullptr,
    const char *currency = nullptr,
    quantra::enums::Calendar calendar = quantra::enums::Calendar_TARGET,
    quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual365Fixed,
    quantra::enums::Frequency frequency = quantra::enums::Frequency_Monthly,
    ::flatbuffers::Offset<quantra::Period> availability_lag = 0,
    ::flatbuffers::Offset<quantra::Period> observation_lag = 0,
    bool interpolated = true,
    bool revised = false,
    quantra::enums::InflationCurveKind kind = quantra::enums::InflationCurveKind_ZeroInflation) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto family_name__ = family_name ? _fbb.CreateString(family_name) : 0;
  auto currency__ = currency ? _fbb.CreateString(currency) : 0;
  return quantra::CreateInflationIndexSpec(
      _fbb,
      id__,
      family_name__,
      currency__,
      calendar,
      day_counter,
      frequency,
      availability_lag,
      observation_lag,
      interpolated,
      revised,
      kind);
}

::flatbuffers::Offset<InflationIndexSpec> CreateInflationIndexSpec(::flatbuffers::FlatBufferBuilder &_fbb, const InflationIndexSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct InflationCurveBaseSpecT : public ::flatbuffers::NativeTable {
  typedef InflationCurveBaseSpec TableType;
  std::string id{};
  std::string reference_date{};
  quantra::enums::Calendar calendar = quantra::enums::Calendar_TARGET;
  quantra::enums::BusinessDayConvention business_day_convention = quantra::enums::BusinessDayConvention_ModifiedFollowing;
  quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual365Fixed;
  quantra::enums::InflationCurveKind kind = quantra::enums::InflationCurveKind_ZeroInflation;
  std::string index_id{};
  std::string discount_curve_id{};
  bool allow_extrapolation = true;
};

/// Inflation curve base specification.
struct InflationCurveBaseSpec FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InflationCurveBaseSpecT NativeTableType;
  typedef InflationCurveBaseSpecBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_REFERENCE_DATE = 6,
    VT_CALENDAR = 8,
    VT_BUSINESS_DAY_CONVENTION = 10,
    VT_DAY_COUNTER = 12,
    VT_KIND = 14,
    VT_INDEX_ID = 16,
    VT_DISCOUNT_CURVE_ID = 18,
    VT_ALLOW_EXTRAPOLATION = 20
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *reference_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REFERENCE_DATE);
  }
  quantra::enums::Calendar calendar() const {
    return static_cast<quantra::enums::Calendar>(GetField<int8_t>(VT_CALENDAR, 32));
  }
  quantra::enums::BusinessDayConvention business_day_convention() const {
    return static_cast<quantra::enums::BusinessDayConvention>(GetField<int8_t>(VT_BUSINESS_DAY_CONVENTION, 2));
  }
  quantra::enums::DayCounter day_counter() const {
    return static_cast<quantra::enums::DayCounter>(GetField<int8_t>(VT_DAY_COUNTER, 1));
  }
  quantra::enums::InflationCurveKind kind() const {
    return static_cast<quantra::enums::InflationCurveKind>(GetField<int8_t>(VT_KIND, 0));
  }
  /// Link to InflationIndexSpec.id.
  const ::flatbuffers::String *index_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INDEX_ID);
  }
  /// Optional nominal discount curve id reserved for future inflation-leg projection/discounting models.
  const ::flatbuffers::String *discount_curve_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISCOUNT_CURVE_ID);
  }
  bool allow_extrapolation() const {
    return GetField<uint8_t>(VT_ALLOW_EXTRAPOLATION, 1) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffsetRequired(verifier, VT_REFERENCE_DATE) &&
           verifier.VerifyString(reference_date()) &&
           VerifyField<int8_t>(verifier, VT_CALENDAR, 1) &&
           VerifyField<int8_t>(verifier, VT_BUSINESS_DAY_CONVENTION, 1) &&
           VerifyField<int8_t>(verifier, VT_DAY_COUNTER, 1) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyOffsetRequired(verifier, VT_INDEX_ID) &&
           verifier.VerifyString(index_id()) &&
           VerifyOffset(verifier, VT_DISCOUNT_CURVE_ID) &&
           verifier.VerifyString(discount_curve_id()) &&
           VerifyField<uint8_t>(verifier, VT_ALLOW_EXTRAPOLATION, 1) &&
           verifier.EndTable();
  }
  InflationCurveBaseSpecT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InflationCurveBaseSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InflationCurveBaseSpec> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveBaseSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InflationCurveBaseSpecBuilder {
  typedef InflationCurveBaseSpec Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(InflationCurveBaseSpec::VT_ID, id);
  }
  void add_reference_date(::flatbuffers::Offset<::flatbuffers::String> reference_date) {
    fbb_.AddOffset(InflationCurveBaseSpec::VT_REFERENCE_DATE, reference_date);
  }
  void add_calendar(quantra::enums::Calendar calendar) {
    fbb_.AddElement<int8_t>(InflationCurveBaseSpec::VT_CALENDAR, static_cast<int8_t>(calendar), 32);
  }
  void add_business_day_convention(quantra::enums::BusinessDayConvention business_day_convention) {
    fbb_.AddElement<int8_t>(InflationCurveBaseSpec::VT_BUSINESS_DAY_CONVENTION, static_cast<int8_t>(business_day_convention), 2);
  }
  void add_day_counter(quantra::enums::DayCounter day_counter) {
    fbb_.AddElement<int8_t>(InflationCurveBaseSpec::VT_DAY_COUNTER, static_cast<int8_t>(day_counter), 1);
  }
  void add_kind(quantra::enums::InflationCurveKind kind) {
    fbb_.AddElement<int8_t>(InflationCurveBaseSpec::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_index_id(::flatbuffers::Offset<::flatbuffers::String> index_id) {
    fbb_.AddOffset(InflationCurveBaseSpec::VT_INDEX_ID, index_id);
  }
  void add_discount_curve_id(::flatbuffers::Offset<::flatbuffers::String> discount_curve_id) {
    fbb_.AddOffset(InflationCurveBaseSpec::VT_DISCOUNT_CURVE_ID, discount_curve_id);
  }
  void add_allow_extrapolation(bool allow_extrapolation) {
    fbb_.AddElement<uint8_t>(InflationCurveBaseSpec::VT_ALLOW_EXTRAPOLATION, static_cast<uint8_t>(allow_extrapolation), 1);
  }
  explicit InflationCurveBaseSpecBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InflationCurveBaseSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InflationCurveBaseSpec>(end);
    fbb_.Required(o, InflationCurveBaseSpec::VT_ID);
    fbb_.Required(o, InflationCurveBaseSpec::VT_REFERENCE_DATE);
    fbb_.Required(o, InflationCurveBaseSpec::VT_INDEX_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<InflationCurveBaseSpec> CreateInflationCurveBaseSpec(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> reference_date = 0,
    quantra::enums::Calendar calendar = quantra::enums::Calendar_TARGET,
    quantra::enums::BusinessDayConvention business_day_convention = quantra::enums::BusinessDayConvention_ModifiedFollowing,
    quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual365Fixed,
    quantra::enums::InflationCurveKind kind = quantra::enums::InflationCurveKind_ZeroInflation,
    ::flatbuffers::Offset<::flatbuffers::String> index_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> discount_curve_id = 0,
    bool allow_extrapolation = true) {
  InflationCurveBaseSpecBuilder builder_(_fbb);
  builder_.add_discount_curve_id(discount_curve_id);
  builder_.add_index_id(index_id);
  builder_.add_reference_date(reference_date);
  builder_.add_id(id);
  builder_.add_allow_extrapolation(allow_extrapolation);
  builder_.add_kind(kind);
  builder_.add_day_counter(day_counter);
  builder_.add_business_day_convention(business_day_convention);
  builder_.add_calendar(calendar);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<InflationCurveBaseSpec> CreateInflationCurveBaseSpecDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *reference_date = nullptr,
    quantra::enums::Calendar calendar = quantra::enums::Calendar_TARGET,
    quantra::enums::BusinessDayConvention business_day_convention = quantra::enums::BusinessDayConvention_ModifiedFollowing,
    quantra::enums::DayCounter day_counter = quantra::enums::DayCounter_Actual365Fixed,
    quantra::enums::InflationCurveKind kind = quantra::enums::InflationCurveKind_ZeroInflation,
    const char *index_id = nullptr,
    const char *discount_curve_id = nullptr,
    bool allow_extrapolation = true) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto reference_date__ = reference_date ? _fbb.CreateString(reference_date) : 0;
  auto index_id__ = index_id ? _fbb.CreateString(index_id) : 0;
  auto discount_curve_id__ = discount_curve_id ? _fbb.CreateString(discount_curve_id) : 0;
  return quantra::CreateInflationCurveBaseSpec(
      _fbb,
      id__,
      reference_date__,
      calendar,
      business_day_convention,
      day_counter,
      kind,
      index_id__,
      discount_curve_id__,
      allow_extrapolation);
}

::flatbuffers::Offset<InflationCurveBaseSpec> CreateInflationCurveBaseSpec(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveBaseSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct InflationSwapPillarT : public ::flatbuffers::NativeTable {
  typedef InflationSwapPillar TableType;
  std::unique_ptr<quantra::PeriodT> maturity{};
  std::string quote_id{};
  double quote_value = 0.0;
  InflationSwapPillarT() = default;
  InflationSwapPillarT(const InflationSwapPillarT &o);
  InflationSwapPillarT(InflationSwapPillarT&&) FLATBUFFERS_NOEXCEPT = default;
  InflationSwapPillarT &operator=(InflationSwapPillarT o) FLATBUFFERS_NOEXCEPT;
};

/// Pillar quote for inflation curve construction.
struct InflationSwapPillar FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InflationSwapPillarT NativeTableType;
  typedef InflationSwapPillarBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MATURITY = 4,
    VT_QUOTE_ID = 6,
    VT_QUOTE_VALUE = 8
  };
  const quantra::Period *maturity() const {
    return GetPointer<const quantra::Period *>(VT_MATURITY);
  }
  /// Optional: resolve quote from pricing.quotes (QuoteType=Curve).
  const ::flatbuffers::String *quote_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_QUOTE_ID);
  }
  /// Inline quote value used when quote_id is empty.
  double quote_value() const {
    return GetField<double>(VT_QUOTE_VALUE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_MATURITY) &&
           verifier.VerifyTable(maturity()) &&
           VerifyOffset(verifier, VT_QUOTE_ID) &&
           verifier.VerifyString(quote_id()) &&
           VerifyField<double>(verifier, VT_QUOTE_VALUE, 8) &&
           verifier.EndTable();
  }
  InflationSwapPillarT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InflationSwapPillarT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InflationSwapPillar> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationSwapPillarT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InflationSwapPillarBuilder {
  typedef InflationSwapPillar Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_maturity(::flatbuffers::Offset<quantra::Period> maturity) {
    fbb_.AddOffset(InflationSwapPillar::VT_MATURITY, maturity);
  }
  void add_quote_id(::flatbuffers::Offset<::flatbuffers::String> quote_id) {
    fbb_.AddOffset(InflationSwapPillar::VT_QUOTE_ID, quote_id);
  }
  void add_quote_value(double quote_value) {
    fbb_.AddElement<double>(InflationSwapPillar::VT_QUOTE_VALUE, quote_value, 0.0);
  }
  explicit InflationSwapPillarBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InflationSwapPillar> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InflationSwapPillar>(end);
    fbb_.Required(o, InflationSwapPillar::VT_MATURITY);
    return o;
  }
};

inline ::flatbuffers::Offset<InflationSwapPillar> CreateInflationSwapPillar(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::Period> maturity = 0,
    ::flatbuffers::Offset<::flatbuffers::String> quote_id = 0,
    double quote_value = 0.0) {
  InflationSwapPillarBuilder builder_(_fbb);
  builder_.add_quote_value(quote_value);
  builder_.add_quote_id(quote_id);
  builder_.add_maturity(maturity);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<InflationSwapPillar> CreateInflationSwapPillarDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::Period> maturity = 0,
    const char *quote_id = nullptr,
    double quote_value = 0.0) {
  auto quote_id__ = quote_id ? _fbb.CreateString(quote_id) : 0;
  return quantra::CreateInflationSwapPillar(
      _fbb,
      maturity,
      quote_id__,
      quote_value);
}

::flatbuffers::Offset<InflationSwapPillar> CreateInflationSwapPillar(::flatbuffers::FlatBufferBuilder &_fbb, const InflationSwapPillarT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ZeroInflationCurveFromZcSwapsSpecT : public ::flatbuffers::NativeTable {
  typedef ZeroInflationCurveFromZcSwapsSpec TableType;
  std::vector<std::unique_ptr<quantra::InflationSwapPillarT>> pillars{};
  quantra::enums::Interpolator interpolator = quantra::enums::Interpolator_Linear;
  ZeroInflationCurveFromZcSwapsSpecT() = default;
  ZeroInflationCurveFromZcSwapsSpecT(const ZeroInflationCurveFromZcSwapsSpecT &o);
  ZeroInflationCurveFromZcSwapsSpecT(ZeroInflationCurveFromZcSwapsSpecT&&) FLATBUFFERS_NOEXCEPT = default;
  ZeroInflationCurveFromZcSwapsSpecT &operator=(ZeroInflationCurveFromZcSwapsSpecT o) FLATBUFFERS_NOEXCEPT;
};

/// Zero inflation curve built from pillar rates.
/// Note: MVP treats pillar quotes as zero inflation rates at each maturity.
struct ZeroInflationCurveFromZcSwapsSpec FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ZeroInflationCurveFromZcSwapsSpecT NativeTableType;
  typedef ZeroInflationCurveFromZcSwapsSpecBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PILLARS = 4,
    VT_INTERPOLATOR = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>> *pillars() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>> *>(VT_PILLARS);
  }
  quantra::enums::Interpolator interpolator() const {
    return static_cast<quantra::enums::Interpolator>(GetField<int8_t>(VT_INTERPOLATOR, 2));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PILLARS) &&
           verifier.VerifyVector(pillars()) &&
           verifier.VerifyVectorOfTables(pillars()) &&
           VerifyField<int8_t>(verifier, VT_INTERPOLATOR, 1) &&
           verifier.EndTable();
  }
  ZeroInflationCurveFromZcSwapsSpecT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ZeroInflationCurveFromZcSwapsSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ZeroInflationCurveFromZcSwapsSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ZeroInflationCurveFromZcSwapsSpecBuilder {
  typedef ZeroInflationCurveFromZcSwapsSpec Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pillars(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>>> pillars) {
    fbb_.AddOffset(ZeroInflationCurveFromZcSwapsSpec::VT_PILLARS, pillars);
  }
  void add_interpolator(quantra::enums::Interpolator interpolator) {
    fbb_.AddElement<int8_t>(ZeroInflationCurveFromZcSwapsSpec::VT_INTERPOLATOR, static_cast<int8_t>(interpolator), 2);
  }
  explicit ZeroInflationCurveFromZcSwapsSpecBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec>(end);
    fbb_.Required(o, ZeroInflationCurveFromZcSwapsSpec::VT_PILLARS);
    return o;
  }
};

inline ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> CreateZeroInflationCurveFromZcSwapsSpec(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>>> pillars = 0,
    quantra::enums::Interpolator interpolator = quantra::enums::Interpolator_Linear) {
  ZeroInflationCurveFromZcSwapsSpecBuilder builder_(_fbb);
  builder_.add_pillars(pillars);
  builder_.add_interpolator(interpolator);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> CreateZeroInflationCurveFromZcSwapsSpecDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<quantra::InflationSwapPillar>> *pillars = nullptr,
    quantra::enums::Interpolator interpolator = quantra::enums::Interpolator_Linear) {
  auto pillars__ = pillars ? _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationSwapPillar>>(*pillars) : 0;
  return quantra::CreateZeroInflationCurveFromZcSwapsSpec(
      _fbb,
      pillars__,
      interpolator);
}

::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> CreateZeroInflationCurveFromZcSwapsSpec(::flatbuffers::FlatBufferBuilder &_fbb, const ZeroInflationCurveFromZcSwapsSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct YoYInflationCurveFromYoYSwapsSpecT : public ::flatbuffers::NativeTable {
  typedef YoYInflationCurveFromYoYSwapsSpec TableType;
  std::vector<std::unique_ptr<quantra::InflationSwapPillarT>> pillars{};
  quantra::enums::Interpolator interpolator = quantra::enums::Interpolator_Linear;
  YoYInflationCurveFromYoYSwapsSpecT() = default;
  YoYInflationCurveFromYoYSwapsSpecT(const YoYInflationCurveFromYoYSwapsSpecT &o);
  YoYInflationCurveFromYoYSwapsSpecT(YoYInflationCurveFromYoYSwapsSpecT&&) FLATBUFFERS_NOEXCEPT = default;
  YoYInflationCurveFromYoYSwapsSpecT &operator=(YoYInflationCurveFromYoYSwapsSpecT o) FLATBUFFERS_NOEXCEPT;
};

/// YoY inflation curve built from pillar rates.
/// Note: MVP treats pillar quotes as YoY rates at each maturity.
struct YoYInflationCurveFromYoYSwapsSpec FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef YoYInflationCurveFromYoYSwapsSpecT NativeTableType;
  typedef YoYInflationCurveFromYoYSwapsSpecBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PILLARS = 4,
    VT_INTERPOLATOR = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>> *pillars() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>> *>(VT_PILLARS);
  }
  quantra::enums::Interpolator interpolator() const {
    return static_cast<quantra::enums::Interpolator>(GetField<int8_t>(VT_INTERPOLATOR, 2));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PILLARS) &&
           verifier.VerifyVector(pillars()) &&
           verifier.VerifyVectorOfTables(pillars()) &&
           VerifyField<int8_t>(verifier, VT_INTERPOLATOR, 1) &&
           verifier.EndTable();
  }
  YoYInflationCurveFromYoYSwapsSpecT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(YoYInflationCurveFromYoYSwapsSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCurveFromYoYSwapsSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct YoYInflationCurveFromYoYSwapsSpecBuilder {
  typedef YoYInflationCurveFromYoYSwapsSpec Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pillars(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>>> pillars) {
    fbb_.AddOffset(YoYInflationCurveFromYoYSwapsSpec::VT_PILLARS, pillars);
  }
  void add_interpolator(quantra::enums::Interpolator interpolator) {
    fbb_.AddElement<int8_t>(YoYInflationCurveFromYoYSwapsSpec::VT_INTERPOLATOR, static_cast<int8_t>(interpolator), 2);
  }
  explicit YoYInflationCurveFromYoYSwapsSpecBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec>(end);
    fbb_.Required(o, YoYInflationCurveFromYoYSwapsSpec::VT_PILLARS);
    return o;
  }
};

inline ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> CreateYoYInflationCurveFromYoYSwapsSpec(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::InflationSwapPillar>>> pillars = 0,
    quantra::enums::Interpolator interpolator = quantra::enums::Interpolator_Linear) {
  YoYInflationCurveFromYoYSwapsSpecBuilder builder_(_fbb);
  builder_.add_pillars(pillars);
  builder_.add_interpolator(interpolator);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> CreateYoYInflationCurveFromYoYSwapsSpecDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<quantra::InflationSwapPillar>> *pillars = nullptr,
    quantra::enums::Interpolator interpolator = quantra::enums::Interpolator_Linear) {
  auto pillars__ = pillars ? _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationSwapPillar>>(*pillars) : 0;
  return quantra::CreateYoYInflationCurveFromYoYSwapsSpec(
      _fbb,
      pillars__,
      interpolator);
}

::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> CreateYoYInflationCurveFromYoYSwapsSpec(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCurveFromYoYSwapsSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct InflationCurveSpecT : public ::flatbuffers::NativeTable {
  typedef InflationCurveSpec TableType;
  std::unique_ptr<quantra::InflationCurveBaseSpecT> base{};
  quantra::InflationCurvePayloadUnion payload{};
  InflationCurveSpecT() = default;
  InflationCurveSpecT(const InflationCurveSpecT &o);
  InflationCurveSpecT(InflationCurveSpecT&&) FLATBUFFERS_NOEXCEPT = default;
  InflationCurveSpecT &operator=(InflationCurveSpecT o) FLATBUFFERS_NOEXCEPT;
};

/// Inflation curve specification.
struct InflationCurveSpec FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InflationCurveSpecT NativeTableType;
  typedef InflationCurveSpecBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  const quantra::InflationCurveBaseSpec *base() const {
    return GetPointer<const quantra::InflationCurveBaseSpec *>(VT_BASE);
  }
  quantra::InflationCurvePayload payload_type() const {
    return static_cast<quantra::InflationCurvePayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const quantra::ZeroInflationCurveFromZcSwapsSpec *payload_as_ZeroInflationCurveFromZcSwapsSpec() const {
    return payload_type() == quantra::InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec ? static_cast<const quantra::ZeroInflationCurveFromZcSwapsSpec *>(payload()) : nullptr;
  }
  const quantra::YoYInflationCurveFromYoYSwapsSpec *payload_as_YoYInflationCurveFromYoYSwapsSpec() const {
    return payload_type() == quantra::InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec ? static_cast<const quantra::YoYInflationCurveFromYoYSwapsSpec *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           VerifyInflationCurvePayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  InflationCurveSpecT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InflationCurveSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InflationCurveSpec> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const quantra::ZeroInflationCurveFromZcSwapsSpec *InflationCurveSpec::payload_as<quantra::ZeroInflationCurveFromZcSwapsSpec>() const {
  return payload_as_ZeroInflationCurveFromZcSwapsSpec();
}

template<> inline const quantra::YoYInflationCurveFromYoYSwapsSpec *InflationCurveSpec::payload_as<quantra::YoYInflationCurveFromYoYSwapsSpec>() const {
  return payload_as_YoYInflationCurveFromYoYSwapsSpec();
}

struct InflationCurveSpecBuilder {
  typedef InflationCurveSpec Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<quantra::InflationCurveBaseSpec> base) {
    fbb_.AddOffset(InflationCurveSpec::VT_BASE, base);
  }
  void add_payload_type(quantra::InflationCurvePayload payload_type) {
    fbb_.AddElement<uint8_t>(InflationCurveSpec::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(InflationCurveSpec::VT_PAYLOAD, payload);
  }
  explicit InflationCurveSpecBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InflationCurveSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InflationCurveSpec>(end);
    fbb_.Required(o, InflationCurveSpec::VT_BASE);
    fbb_.Required(o, InflationCurveSpec::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<InflationCurveSpec> CreateInflationCurveSpec(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::InflationCurveBaseSpec> base = 0,
    quantra::InflationCurvePayload payload_type = quantra::InflationCurvePayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  InflationCurveSpecBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_base(base);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<InflationCurveSpec> CreateInflationCurveSpec(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline InflationIndexSpecT::InflationIndexSpecT(const InflationIndexSpecT &o)
      : id(o.id),
        family_name(o.family_name),
        currency(o.currency),
        calendar(o.calendar),
        day_counter(o.day_counter),
        frequency(o.frequency),
        availability_lag((o.availability_lag) ? new quantra::PeriodT(*o.availability_lag) : nullptr),
        observation_lag((o.observation_lag) ? new quantra::PeriodT(*o.observation_lag) : nullptr),
        interpolated(o.interpolated),
        revised(o.revised),
        kind(o.kind) {
}

inline InflationIndexSpecT &InflationIndexSpecT::operator=(InflationIndexSpecT o) FLATBUFFERS_NOEXCEPT {
  std::swap(id, o.id);
  std::swap(family_name, o.family_name);
  std::swap(currency, o.currency);
  std::swap(calendar, o.calendar);
  std::swap(day_counter, o.day_counter);
  std::swap(frequency, o.frequency);
  std::swap(availability_lag, o.availability_lag);
  std::swap(observation_lag, o.observation_lag);
  std::swap(interpolated, o.interpolated);
  std::swap(revised, o.revised);
  std::swap(kind, o.kind);
  return *this;
}

inline InflationIndexSpecT *InflationIndexSpec::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InflationIndexSpecT>(new InflationIndexSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InflationIndexSpec::UnPackTo(InflationIndexSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = family_name(); if (_e) _o->family_name = _e->str(); }
  { auto _e = currency(); if (_e) _o->currency = _e->str(); }
  { auto _e = calendar(); _o->calendar = _e; }
  { auto _e = day_counter(); _o->day_counter = _e; }
  { auto _e = frequency(); _o->frequency = _e; }
  { auto _e = availability_lag(); if (_e) { if(_o->availability_lag) { _e->UnPackTo(_o->availability_lag.get(), _resolver); } else { _o->availability_lag = std::unique_ptr<quantra::PeriodT>(_e->UnPack(_resolver)); } } else if (_o->availability_lag) { _o->availability_lag.reset(); } }
  { auto _e = observation_lag(); if (_e) { if(_o->observation_lag) { _e->UnPackTo(_o->observation_lag.get(), _resolver); } else { _o->observation_lag = std::unique_ptr<quantra::PeriodT>(_e->UnPack(_resolver)); } } else if (_o->observation_lag) { _o->observation_lag.reset(); } }
  { auto _e = interpolated(); _o->interpolated = _e; }
  { auto _e = revised(); _o->revised = _e; }
  { auto _e = kind(); _o->kind = _e; }
}

inline ::flatbuffers::Offset<InflationIndexSpec> InflationIndexSpec::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationIndexSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInflationIndexSpec(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InflationIndexSpec> CreateInflationIndexSpec(::flatbuffers::FlatBufferBuilder &_fbb, const InflationIndexSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InflationIndexSpecT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _fbb.CreateString(_o->id);
  auto _family_name = _o->family_name.empty() ? 0 : _fbb.CreateString(_o->family_name);
  auto _currency = _o->currency.empty() ? 0 : _fbb.CreateString(_o->currency);
  auto _calendar = _o->calendar;
  auto _day_counter = _o->day_counter;
  auto _frequency = _o->frequency;
  auto _availability_lag = _o->availability_lag ? CreatePeriod(_fbb, _o->availability_lag.get(), _rehasher) : 0;
  auto _observation_lag = _o->observation_lag ? CreatePeriod(_fbb, _o->observation_lag.get(), _rehasher) : 0;
  auto _interpolated = _o->interpolated;
  auto _revised = _o->revised;
  auto _kind = _o->kind;
  return quantra::CreateInflationIndexSpec(
      _fbb,
      _id,
      _family_name,
      _currency,
      _calendar,
      _day_counter,
      _frequency,
      _availability_lag,
      _observation_lag,
      _interpolated,
      _revised,
      _kind);
}

inline InflationCurveBaseSpecT *InflationCurveBaseSpec::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InflationCurveBaseSpecT>(new InflationCurveBaseSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InflationCurveBaseSpec::UnPackTo(InflationCurveBaseSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = reference_date(); if (_e) _o->reference_date = _e->str(); }
  { auto _e = calendar(); _o->calendar = _e; }
  { auto _e = business_day_convention(); _o->business_day_convention = _e; }
  { auto _e = day_counter(); _o->day_counter = _e; }
  { auto _e = kind(); _o->kind = _e; }
  { auto _e = index_id(); if (_e) _o->index_id = _e->str(); }
  { auto _e = discount_curve_id(); if (_e) _o->discount_curve_id = _e->str(); }
  { auto _e = allow_extrapolation(); _o->allow_extrapolation = _e; }
}

inline ::flatbuffers::Offset<InflationCurveBaseSpec> InflationCurveBaseSpec::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveBaseSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInflationCurveBaseSpec(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InflationCurveBaseSpec> CreateInflationCurveBaseSpec(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveBaseSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InflationCurveBaseSpecT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _fbb.CreateString(_o->id);
  auto _reference_date = _fbb.CreateString(_o->reference_date);
  auto _calendar = _o->calendar;
  auto _business_day_convention = _o->business_day_convention;
  auto _day_counter = _o->day_counter;
  auto _kind = _o->kind;
  auto _index_id = _fbb.CreateString(_o->index_id);
  auto _discount_curve_id = _o->discount_curve_id.empty() ? 0 : _fbb.CreateString(_o->discount_curve_id);
  auto _allow_extrapolation = _o->allow_extrapolation;
  return quantra::CreateInflationCurveBaseSpec(
      _fbb,
      _id,
      _reference_date,
      _calendar,
      _business_day_convention,
      _day_counter,
      _kind,
      _index_id,
      _discount_curve_id,
      _allow_extrapolation);
}

inline InflationSwapPillarT::InflationSwapPillarT(const InflationSwapPillarT &o)
      : maturity((o.maturity) ? new quantra::PeriodT(*o.maturity) : nullptr),
        quote_id(o.quote_id),
        quote_value(o.quote_value) {
}

inline InflationSwapPillarT &InflationSwapPillarT::operator=(InflationSwapPillarT o) FLATBUFFERS_NOEXCEPT {
  std::swap(maturity, o.maturity);
  std::swap(quote_id, o.quote_id);
  std::swap(quote_value, o.quote_value);
  return *this;
}

inline InflationSwapPillarT *InflationSwapPillar::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InflationSwapPillarT>(new InflationSwapPillarT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InflationSwapPillar::UnPackTo(InflationSwapPillarT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = maturity(); if (_e) { if(_o->maturity) { _e->UnPackTo(_o->maturity.get(), _resolver); } else { _o->maturity = std::unique_ptr<quantra::PeriodT>(_e->UnPack(_resolver)); } } else if (_o->maturity) { _o->maturity.reset(); } }
  { auto _e = quote_id(); if (_e) _o->quote_id = _e->str(); }
  { auto _e = quote_value(); _o->quote_value = _e; }
}

inline ::flatbuffers::Offset<InflationSwapPillar> InflationSwapPillar::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationSwapPillarT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInflationSwapPillar(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InflationSwapPillar> CreateInflationSwapPillar(::flatbuffers::FlatBufferBuilder &_fbb, const InflationSwapPillarT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InflationSwapPillarT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _maturity = _o->maturity ? CreatePeriod(_fbb, _o->maturity.get(), _rehasher) : 0;
  auto _quote_id = _o->quote_id.empty() ? 0 : _fbb.CreateString(_o->quote_id);
  auto _quote_value = _o->quote_value;
  return quantra::CreateInflationSwapPillar(
      _fbb,
      _maturity,
      _quote_id,
      _quote_value);
}

inline ZeroInflationCurveFromZcSwapsSpecT::ZeroInflationCurveFromZcSwapsSpecT(const ZeroInflationCurveFromZcSwapsSpecT &o)
      : interpolator(o.interpolator) {
  pillars.reserve(o.pillars.size());
  for (const auto &pillars_ : o.pillars) { pillars.emplace_back((pillars_) ? new quantra::InflationSwapPillarT(*pillars_) : nullptr); }
}

inline ZeroInflationCurveFromZcSwapsSpecT &ZeroInflationCurveFromZcSwapsSpecT::operator=(ZeroInflationCurveFromZcSwapsSpecT o) FLATBUFFERS_NOEXCEPT {
  std::swap(pillars, o.pillars);
  std::swap(interpolator, o.interpolator);
  return *this;
}

inline ZeroInflationCurveFromZcSwapsSpecT *ZeroInflationCurveFromZcSwapsSpec::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ZeroInflationCurveFromZcSwapsSpecT>(new ZeroInflationCurveFromZcSwapsSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ZeroInflationCurveFromZcSwapsSpec::UnPackTo(ZeroInflationCurveFromZcSwapsSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pillars(); if (_e) { _o->pillars.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->pillars[_i]) { _e->Get(_i)->UnPackTo(_o->pillars[_i].get(), _resolver); } else { _o->pillars[_i] = std::unique_ptr<quantra::InflationSwapPillarT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->pillars.resize(0); } }
  { auto _e = interpolator(); _o->interpolator = _e; }
}

inline ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> ZeroInflationCurveFromZcSwapsSpec::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ZeroInflationCurveFromZcSwapsSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateZeroInflationCurveFromZcSwapsSpec(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ZeroInflationCurveFromZcSwapsSpec> CreateZeroInflationCurveFromZcSwapsSpec(::flatbuffers::FlatBufferBuilder &_fbb, const ZeroInflationCurveFromZcSwapsSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ZeroInflationCurveFromZcSwapsSpecT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pillars = _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationSwapPillar>> (_o->pillars.size(), [](size_t i, _VectorArgs *__va) { return CreateInflationSwapPillar(*__va->__fbb, __va->__o->pillars[i].get(), __va->__rehasher); }, &_va );
  auto _interpolator = _o->interpolator;
  return quantra::CreateZeroInflationCurveFromZcSwapsSpec(
      _fbb,
      _pillars,
      _interpolator);
}

inline YoYInflationCurveFromYoYSwapsSpecT::YoYInflationCurveFromYoYSwapsSpecT(const YoYInflationCurveFromYoYSwapsSpecT &o)
      : interpolator(o.interpolator) {
  pillars.reserve(o.pillars.size());
  for (const auto &pillars_ : o.pillars) { pillars.emplace_back((pillars_) ? new quantra::InflationSwapPillarT(*pillars_) : nullptr); }
}

inline YoYInflationCurveFromYoYSwapsSpecT &YoYInflationCurveFromYoYSwapsSpecT::operator=(YoYInflationCurveFromYoYSwapsSpecT o) FLATBUFFERS_NOEXCEPT {
  std::swap(pillars, o.pillars);
  std::swap(interpolator, o.interpolator);
  return *this;
}

inline YoYInflationCurveFromYoYSwapsSpecT *YoYInflationCurveFromYoYSwapsSpec::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<YoYInflationCurveFromYoYSwapsSpecT>(new YoYInflationCurveFromYoYSwapsSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void YoYInflationCurveFromYoYSwapsSpec::UnPackTo(YoYInflationCurveFromYoYSwapsSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pillars(); if (_e) { _o->pillars.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->pillars[_i]) { _e->Get(_i)->UnPackTo(_o->pillars[_i].get(), _resolver); } else { _o->pillars[_i] = std::unique_ptr<quantra::InflationSwapPillarT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->pillars.resize(0); } }
  { auto _e = interpolator(); _o->interpolator = _e; }
}

inline ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> YoYInflationCurveFromYoYSwapsSpec::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCurveFromYoYSwapsSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateYoYInflationCurveFromYoYSwapsSpec(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<YoYInflationCurveFromYoYSwapsSpec> CreateYoYInflationCurveFromYoYSwapsSpec(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCurveFromYoYSwapsSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const YoYInflationCurveFromYoYSwapsSpecT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pillars = _fbb.CreateVector<::flatbuffers::Offset<quantra::InflationSwapPillar>> (_o->pillars.size(), [](size_t i, _VectorArgs *__va) { return CreateInflationSwapPillar(*__va->__fbb, __va->__o->pillars[i].get(), __va->__rehasher); }, &_va );
  auto _interpolator = _o->interpolator;
  return quantra::CreateYoYInflationCurveFromYoYSwapsSpec(
      _fbb,
      _pillars,
      _interpolator);
}

inline InflationCurveSpecT::InflationCurveSpecT(const InflationCurveSpecT &o)
      : base((o.base) ? new quantra::InflationCurveBaseSpecT(*o.base) : nullptr),
        payload(o.payload) {
}

inline InflationCurveSpecT &InflationCurveSpecT::operator=(InflationCurveSpecT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  std::swap(payload, o.payload);
  return *this;
}

inline InflationCurveSpecT *InflationCurveSpec::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InflationCurveSpecT>(new InflationCurveSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InflationCurveSpec::UnPackTo(InflationCurveSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<quantra::InflationCurveBaseSpecT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = quantra::InflationCurvePayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<InflationCurveSpec> InflationCurveSpec::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateInflationCurveSpec(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InflationCurveSpec> CreateInflationCurveSpec(::flatbuffers::FlatBufferBuilder &_fbb, const InflationCurveSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InflationCurveSpecT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateInflationCurveBaseSpec(_fbb, _o->base.get(), _rehasher) : 0;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return quantra::CreateInflationCurveSpec(
      _fbb,
      _base,
      _payload_type,
      _payload);
}

inline bool VerifyInflationCurvePayload(::flatbuffers::Verifier &verifier, const void *obj, InflationCurvePayload type) {
  switch (type) {
    case InflationCurvePayload_NONE: {
      return true;
    }
    case InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec: {
      auto ptr = reinterpret_cast<const quantra::ZeroInflationCurveFromZcSwapsSpec *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec: {
      auto ptr = reinterpret_cast<const quantra::YoYInflationCurveFromYoYSwapsSpec *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyInflationCurvePayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyInflationCurvePayload(
        verifier,  values->Get(i), types->GetEnum<InflationCurvePayload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *InflationCurvePayloadUnion::UnPack(const void *obj, InflationCurvePayload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec: {
      auto ptr = reinterpret_cast<const quantra::ZeroInflationCurveFromZcSwapsSpec *>(obj);
      return ptr->UnPack(resolver);
    }
    case InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec: {
      auto ptr = reinterpret_cast<const quantra::YoYInflationCurveFromYoYSwapsSpec *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> InflationCurvePayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec: {
      auto ptr = reinterpret_cast<const quantra::ZeroInflationCurveFromZcSwapsSpecT *>(value);
      return CreateZeroInflationCurveFromZcSwapsSpec(_fbb, ptr, _rehasher).Union();
    }
    case InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec: {
      auto ptr = reinterpret_cast<const quantra::YoYInflationCurveFromYoYSwapsSpecT *>(value);
      return CreateYoYInflationCurveFromYoYSwapsSpec(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline InflationCurvePayloadUnion::InflationCurvePayloadUnion(const InflationCurvePayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec: {
      value = new quantra::ZeroInflationCurveFromZcSwapsSpecT(*reinterpret_cast<quantra::ZeroInflationCurveFromZcSwapsSpecT *>(u.value));
      break;
    }
    case InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec: {
      value = new quantra::YoYInflationCurveFromYoYSwapsSpecT(*reinterpret_cast<quantra::YoYInflationCurveFromYoYSwapsSpecT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void InflationCurvePayloadUnion::Reset() {
  switch (type) {
    case InflationCurvePayload_ZeroInflationCurveFromZcSwapsSpec: {
      auto ptr = reinterpret_cast<quantra::ZeroInflationCurveFromZcSwapsSpecT *>(value);
      delete ptr;
      break;
    }
    case InflationCurvePayload_YoYInflationCurveFromYoYSwapsSpec: {
      auto ptr = reinterpret_cast<quantra::YoYInflationCurveFromYoYSwapsSpecT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = InflationCurvePayload_NONE;
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_INFLATION_QUANTRA_H_
