// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PRICEOISSWAPREQUEST_QUANTRA_H_
#define FLATBUFFERS_GENERATED_PRICEOISSWAPREQUEST_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "ois_swap_generated.h"
#include "pricing_generated.h"

namespace quantra {

struct PriceOisSwap;
struct PriceOisSwapBuilder;
struct PriceOisSwapT;

struct PriceOisSwapRequest;
struct PriceOisSwapRequestBuilder;
struct PriceOisSwapRequestT;

struct PriceOisSwapT : public ::flatbuffers::NativeTable {
  typedef PriceOisSwap TableType;
  std::unique_ptr<quantra::OisSwapT> ois_swap{};
  std::string discounting_curve{};
  std::string forwarding_curve{};
  PriceOisSwapT() = default;
  PriceOisSwapT(const PriceOisSwapT &o);
  PriceOisSwapT(PriceOisSwapT&&) FLATBUFFERS_NOEXCEPT = default;
  PriceOisSwapT &operator=(PriceOisSwapT o) FLATBUFFERS_NOEXCEPT;
};

/// Single OIS swap pricing context with curve references.
struct PriceOisSwap FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PriceOisSwapT NativeTableType;
  typedef PriceOisSwapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OIS_SWAP = 4,
    VT_DISCOUNTING_CURVE = 6,
    VT_FORWARDING_CURVE = 8
  };
  const quantra::OisSwap *ois_swap() const {
    return GetPointer<const quantra::OisSwap *>(VT_OIS_SWAP);
  }
  const ::flatbuffers::String *discounting_curve() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISCOUNTING_CURVE);
  }
  const ::flatbuffers::String *forwarding_curve() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FORWARDING_CURVE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OIS_SWAP) &&
           verifier.VerifyTable(ois_swap()) &&
           VerifyOffset(verifier, VT_DISCOUNTING_CURVE) &&
           verifier.VerifyString(discounting_curve()) &&
           VerifyOffset(verifier, VT_FORWARDING_CURVE) &&
           verifier.VerifyString(forwarding_curve()) &&
           verifier.EndTable();
  }
  PriceOisSwapT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PriceOisSwapT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PriceOisSwap> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PriceOisSwapBuilder {
  typedef PriceOisSwap Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ois_swap(::flatbuffers::Offset<quantra::OisSwap> ois_swap) {
    fbb_.AddOffset(PriceOisSwap::VT_OIS_SWAP, ois_swap);
  }
  void add_discounting_curve(::flatbuffers::Offset<::flatbuffers::String> discounting_curve) {
    fbb_.AddOffset(PriceOisSwap::VT_DISCOUNTING_CURVE, discounting_curve);
  }
  void add_forwarding_curve(::flatbuffers::Offset<::flatbuffers::String> forwarding_curve) {
    fbb_.AddOffset(PriceOisSwap::VT_FORWARDING_CURVE, forwarding_curve);
  }
  explicit PriceOisSwapBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PriceOisSwap> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PriceOisSwap>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PriceOisSwap> CreatePriceOisSwap(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::OisSwap> ois_swap = 0,
    ::flatbuffers::Offset<::flatbuffers::String> discounting_curve = 0,
    ::flatbuffers::Offset<::flatbuffers::String> forwarding_curve = 0) {
  PriceOisSwapBuilder builder_(_fbb);
  builder_.add_forwarding_curve(forwarding_curve);
  builder_.add_discounting_curve(discounting_curve);
  builder_.add_ois_swap(ois_swap);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PriceOisSwap> CreatePriceOisSwapDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::OisSwap> ois_swap = 0,
    const char *discounting_curve = nullptr,
    const char *forwarding_curve = nullptr) {
  auto discounting_curve__ = discounting_curve ? _fbb.CreateString(discounting_curve) : 0;
  auto forwarding_curve__ = forwarding_curve ? _fbb.CreateString(forwarding_curve) : 0;
  return quantra::CreatePriceOisSwap(
      _fbb,
      ois_swap,
      discounting_curve__,
      forwarding_curve__);
}

::flatbuffers::Offset<PriceOisSwap> CreatePriceOisSwap(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PriceOisSwapRequestT : public ::flatbuffers::NativeTable {
  typedef PriceOisSwapRequest TableType;
  std::unique_ptr<quantra::PricingT> pricing{};
  std::vector<std::unique_ptr<quantra::PriceOisSwapT>> swaps{};
  bool include_flows = false;
  PriceOisSwapRequestT() = default;
  PriceOisSwapRequestT(const PriceOisSwapRequestT &o);
  PriceOisSwapRequestT(PriceOisSwapRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  PriceOisSwapRequestT &operator=(PriceOisSwapRequestT o) FLATBUFFERS_NOEXCEPT;
};

/// Request to price one or more OIS swaps.
struct PriceOisSwapRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PriceOisSwapRequestT NativeTableType;
  typedef PriceOisSwapRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PRICING = 4,
    VT_SWAPS = 6,
    VT_INCLUDE_FLOWS = 8
  };
  const quantra::Pricing *pricing() const {
    return GetPointer<const quantra::Pricing *>(VT_PRICING);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::PriceOisSwap>> *swaps() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<quantra::PriceOisSwap>> *>(VT_SWAPS);
  }
  bool include_flows() const {
    return GetField<uint8_t>(VT_INCLUDE_FLOWS, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PRICING) &&
           verifier.VerifyTable(pricing()) &&
           VerifyOffset(verifier, VT_SWAPS) &&
           verifier.VerifyVector(swaps()) &&
           verifier.VerifyVectorOfTables(swaps()) &&
           VerifyField<uint8_t>(verifier, VT_INCLUDE_FLOWS, 1) &&
           verifier.EndTable();
  }
  PriceOisSwapRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PriceOisSwapRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PriceOisSwapRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PriceOisSwapRequestBuilder {
  typedef PriceOisSwapRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pricing(::flatbuffers::Offset<quantra::Pricing> pricing) {
    fbb_.AddOffset(PriceOisSwapRequest::VT_PRICING, pricing);
  }
  void add_swaps(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::PriceOisSwap>>> swaps) {
    fbb_.AddOffset(PriceOisSwapRequest::VT_SWAPS, swaps);
  }
  void add_include_flows(bool include_flows) {
    fbb_.AddElement<uint8_t>(PriceOisSwapRequest::VT_INCLUDE_FLOWS, static_cast<uint8_t>(include_flows), 0);
  }
  explicit PriceOisSwapRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PriceOisSwapRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PriceOisSwapRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PriceOisSwapRequest> CreatePriceOisSwapRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::Pricing> pricing = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<quantra::PriceOisSwap>>> swaps = 0,
    bool include_flows = false) {
  PriceOisSwapRequestBuilder builder_(_fbb);
  builder_.add_swaps(swaps);
  builder_.add_pricing(pricing);
  builder_.add_include_flows(include_flows);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PriceOisSwapRequest> CreatePriceOisSwapRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<quantra::Pricing> pricing = 0,
    const std::vector<::flatbuffers::Offset<quantra::PriceOisSwap>> *swaps = nullptr,
    bool include_flows = false) {
  auto swaps__ = swaps ? _fbb.CreateVector<::flatbuffers::Offset<quantra::PriceOisSwap>>(*swaps) : 0;
  return quantra::CreatePriceOisSwapRequest(
      _fbb,
      pricing,
      swaps__,
      include_flows);
}

::flatbuffers::Offset<PriceOisSwapRequest> CreatePriceOisSwapRequest(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PriceOisSwapT::PriceOisSwapT(const PriceOisSwapT &o)
      : ois_swap((o.ois_swap) ? new quantra::OisSwapT(*o.ois_swap) : nullptr),
        discounting_curve(o.discounting_curve),
        forwarding_curve(o.forwarding_curve) {
}

inline PriceOisSwapT &PriceOisSwapT::operator=(PriceOisSwapT o) FLATBUFFERS_NOEXCEPT {
  std::swap(ois_swap, o.ois_swap);
  std::swap(discounting_curve, o.discounting_curve);
  std::swap(forwarding_curve, o.forwarding_curve);
  return *this;
}

inline PriceOisSwapT *PriceOisSwap::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PriceOisSwapT>(new PriceOisSwapT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PriceOisSwap::UnPackTo(PriceOisSwapT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ois_swap(); if (_e) { if(_o->ois_swap) { _e->UnPackTo(_o->ois_swap.get(), _resolver); } else { _o->ois_swap = std::unique_ptr<quantra::OisSwapT>(_e->UnPack(_resolver)); } } else if (_o->ois_swap) { _o->ois_swap.reset(); } }
  { auto _e = discounting_curve(); if (_e) _o->discounting_curve = _e->str(); }
  { auto _e = forwarding_curve(); if (_e) _o->forwarding_curve = _e->str(); }
}

inline ::flatbuffers::Offset<PriceOisSwap> PriceOisSwap::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePriceOisSwap(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PriceOisSwap> CreatePriceOisSwap(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PriceOisSwapT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ois_swap = _o->ois_swap ? CreateOisSwap(_fbb, _o->ois_swap.get(), _rehasher) : 0;
  auto _discounting_curve = _o->discounting_curve.empty() ? 0 : _fbb.CreateString(_o->discounting_curve);
  auto _forwarding_curve = _o->forwarding_curve.empty() ? 0 : _fbb.CreateString(_o->forwarding_curve);
  return quantra::CreatePriceOisSwap(
      _fbb,
      _ois_swap,
      _discounting_curve,
      _forwarding_curve);
}

inline PriceOisSwapRequestT::PriceOisSwapRequestT(const PriceOisSwapRequestT &o)
      : pricing((o.pricing) ? new quantra::PricingT(*o.pricing) : nullptr),
        include_flows(o.include_flows) {
  swaps.reserve(o.swaps.size());
  for (const auto &swaps_ : o.swaps) { swaps.emplace_back((swaps_) ? new quantra::PriceOisSwapT(*swaps_) : nullptr); }
}

inline PriceOisSwapRequestT &PriceOisSwapRequestT::operator=(PriceOisSwapRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(pricing, o.pricing);
  std::swap(swaps, o.swaps);
  std::swap(include_flows, o.include_flows);
  return *this;
}

inline PriceOisSwapRequestT *PriceOisSwapRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PriceOisSwapRequestT>(new PriceOisSwapRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PriceOisSwapRequest::UnPackTo(PriceOisSwapRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pricing(); if (_e) { if(_o->pricing) { _e->UnPackTo(_o->pricing.get(), _resolver); } else { _o->pricing = std::unique_ptr<quantra::PricingT>(_e->UnPack(_resolver)); } } else if (_o->pricing) { _o->pricing.reset(); } }
  { auto _e = swaps(); if (_e) { _o->swaps.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->swaps[_i]) { _e->Get(_i)->UnPackTo(_o->swaps[_i].get(), _resolver); } else { _o->swaps[_i] = std::unique_ptr<quantra::PriceOisSwapT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->swaps.resize(0); } }
  { auto _e = include_flows(); _o->include_flows = _e; }
}

inline ::flatbuffers::Offset<PriceOisSwapRequest> PriceOisSwapRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePriceOisSwapRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PriceOisSwapRequest> CreatePriceOisSwapRequest(::flatbuffers::FlatBufferBuilder &_fbb, const PriceOisSwapRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PriceOisSwapRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pricing = _o->pricing ? CreatePricing(_fbb, _o->pricing.get(), _rehasher) : 0;
  auto _swaps = _o->swaps.size() ? _fbb.CreateVector<::flatbuffers::Offset<quantra::PriceOisSwap>> (_o->swaps.size(), [](size_t i, _VectorArgs *__va) { return CreatePriceOisSwap(*__va->__fbb, __va->__o->swaps[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _include_flows = _o->include_flows;
  return quantra::CreatePriceOisSwapRequest(
      _fbb,
      _pricing,
      _swaps,
      _include_flows);
}

inline const quantra::PriceOisSwapRequest *GetPriceOisSwapRequest(const void *buf) {
  return ::flatbuffers::GetRoot<quantra::PriceOisSwapRequest>(buf);
}

inline const quantra::PriceOisSwapRequest *GetSizePrefixedPriceOisSwapRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<quantra::PriceOisSwapRequest>(buf);
}

inline bool VerifyPriceOisSwapRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<quantra::PriceOisSwapRequest>(nullptr);
}

inline bool VerifySizePrefixedPriceOisSwapRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<quantra::PriceOisSwapRequest>(nullptr);
}

inline void FinishPriceOisSwapRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::PriceOisSwapRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPriceOisSwapRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::PriceOisSwapRequest> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<quantra::PriceOisSwapRequestT> UnPackPriceOisSwapRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::PriceOisSwapRequestT>(GetPriceOisSwapRequest(buf)->UnPack(res));
}

inline std::unique_ptr<quantra::PriceOisSwapRequestT> UnPackSizePrefixedPriceOisSwapRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::PriceOisSwapRequestT>(GetSizePrefixedPriceOisSwapRequest(buf)->UnPack(res));
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_PRICEOISSWAPREQUEST_QUANTRA_H_
