// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_QUOTES_QUANTRA_H_
#define FLATBUFFERS_GENERATED_QUOTES_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "enums_generated.h"

namespace quantra {

struct QuoteSpec;
struct QuoteSpecBuilder;
struct QuoteSpecT;

struct QuoteSpecT : public ::flatbuffers::NativeTable {
  typedef QuoteSpec TableType;
  std::string id{};
  double value = 0.0;
};

/// Market quote (spot price, FX rate, etc.)
/// Used by: EquityOption (future)
struct QuoteSpec FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuoteSpecT NativeTableType;
  typedef QuoteSpecBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
  QuoteSpecT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QuoteSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<QuoteSpec> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuoteSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QuoteSpecBuilder {
  typedef QuoteSpec Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(QuoteSpec::VT_ID, id);
  }
  void add_value(double value) {
    fbb_.AddElement<double>(QuoteSpec::VT_VALUE, value, 0.0);
  }
  explicit QuoteSpecBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<QuoteSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<QuoteSpec>(end);
    fbb_.Required(o, QuoteSpec::VT_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<QuoteSpec> CreateQuoteSpec(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    double value = 0.0) {
  QuoteSpecBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<QuoteSpec> CreateQuoteSpecDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    double value = 0.0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  return quantra::CreateQuoteSpec(
      _fbb,
      id__,
      value);
}

::flatbuffers::Offset<QuoteSpec> CreateQuoteSpec(::flatbuffers::FlatBufferBuilder &_fbb, const QuoteSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline QuoteSpecT *QuoteSpec::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<QuoteSpecT>(new QuoteSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void QuoteSpec::UnPackTo(QuoteSpecT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = value(); _o->value = _e; }
}

inline ::flatbuffers::Offset<QuoteSpec> QuoteSpec::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuoteSpecT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateQuoteSpec(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<QuoteSpec> CreateQuoteSpec(::flatbuffers::FlatBufferBuilder &_fbb, const QuoteSpecT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const QuoteSpecT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _fbb.CreateString(_o->id);
  auto _value = _o->value;
  return quantra::CreateQuoteSpec(
      _fbb,
      _id,
      _value);
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_QUOTES_QUANTRA_H_
