// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_YEARONYEARINFLATIONCAPFLOOR_QUANTRA_H_
#define FLATBUFFERS_GENERATED_YEARONYEARINFLATIONCAPFLOOR_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"
#include "enums_generated.h"
#include "schedule_generated.h"

namespace quantra {

struct YoYInflationCapFloor;
struct YoYInflationCapFloorBuilder;
struct YoYInflationCapFloorT;

struct YoYInflationCapFloorT : public ::flatbuffers::NativeTable {
  typedef YoYInflationCapFloor TableType;
  ::flatbuffers::Optional<quantra::enums::CapFloorType> cap_floor_type = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<double> notional = ::flatbuffers::nullopt;
  std::unique_ptr<quantra::ScheduleT> schedule{};
  std::string inflation_index_id{};
  std::unique_ptr<quantra::PeriodT> observation_lag{};
  ::flatbuffers::Optional<quantra::enums::DayCounter> day_counter = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<quantra::enums::BusinessDayConvention> payment_convention = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<double> cap_rate = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<double> floor_rate = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<double> gearing = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<double> spread = ::flatbuffers::nullopt;
  YoYInflationCapFloorT() = default;
  YoYInflationCapFloorT(const YoYInflationCapFloorT &o);
  YoYInflationCapFloorT(YoYInflationCapFloorT&&) FLATBUFFERS_NOEXCEPT = default;
  YoYInflationCapFloorT &operator=(YoYInflationCapFloorT o) FLATBUFFERS_NOEXCEPT;
};

/// Year-on-year inflation cap / floor / collar (QuantLib::YoYInflationCapFloor).
/// A strip of year-on-year inflation optionlets built over `schedule` off the
/// same YoY inflation index/curve the year-on-year inflation swap path uses.
///
/// The pricing formula is selected by the referenced YoYOptionletVolSpec's
/// vol_type (Black / UnitDisplacedBlack / Bachelier); the vol surface and this
/// instrument reference the SAME year-on-year inflation index by id.
struct YoYInflationCapFloor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef YoYInflationCapFloorT NativeTableType;
  typedef YoYInflationCapFloorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAP_FLOOR_TYPE = 4,
    VT_NOTIONAL = 6,
    VT_SCHEDULE = 8,
    VT_INFLATION_INDEX_ID = 10,
    VT_OBSERVATION_LAG = 12,
    VT_DAY_COUNTER = 14,
    VT_PAYMENT_CONVENTION = 16,
    VT_CAP_RATE = 18,
    VT_FLOOR_RATE = 20,
    VT_GEARING = 22,
    VT_SPREAD = 24
  };
  /// Cap, Floor, or Collar. Presence-required: an omitted type is a 400,
  /// never the alphabetical-0 default (Cap). Reuses the shared CapFloorType
  /// enum (Cap/Floor/Collar).
  ::flatbuffers::Optional<quantra::enums::CapFloorType> cap_floor_type() const {
    return GetOptional<int8_t, quantra::enums::CapFloorType>(VT_CAP_FLOOR_TYPE);
  }
  /// Notional per optionlet. Presence-required and must be > 0.
  ::flatbuffers::Optional<double> notional() const {
    return GetOptional<double, double>(VT_NOTIONAL);
  }
  /// Coupon schedule for the year-on-year optionlet strip.
  const quantra::Schedule *schedule() const {
    return GetPointer<const quantra::Schedule *>(VT_SCHEDULE);
  }
  /// Link to InflationIndexSpec.id — the YoY inflation index (must resolve to
  /// a QuantLib YoYInflationIndex, same as the year-on-year inflation swap).
  const ::flatbuffers::String *inflation_index_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INFLATION_INDEX_ID);
  }
  /// Observation lag used when the year-on-year rate is observed (e.g. 3
  /// Months).
  const quantra::Period *observation_lag() const {
    return GetPointer<const quantra::Period *>(VT_OBSERVATION_LAG);
  }
  /// Day counter for the optionlet accrual. Presence-required.
  ::flatbuffers::Optional<quantra::enums::DayCounter> day_counter() const {
    return GetOptional<int8_t, quantra::enums::DayCounter>(VT_DAY_COUNTER);
  }
  /// Business-day convention for the payment dates. Presence-required.
  ::flatbuffers::Optional<quantra::enums::BusinessDayConvention> payment_convention() const {
    return GetOptional<int8_t, quantra::enums::BusinessDayConvention>(VT_PAYMENT_CONVENTION);
  }
  /// Cap strike (year-on-year rate). Required when, and only when, the type
  /// is Cap or Collar; must be absent for a Floor.
  ::flatbuffers::Optional<double> cap_rate() const {
    return GetOptional<double, double>(VT_CAP_RATE);
  }
  /// Floor strike (year-on-year rate). Required when, and only when, the type
  /// is Floor or Collar; must be absent for a Cap. For a Collar,
  /// cap_rate >= floor_rate is enforced.
  ::flatbuffers::Optional<double> floor_rate() const {
    return GetOptional<double, double>(VT_FLOOR_RATE);
  }
  /// Optional per-optionlet gearing on the year-on-year rate (absent => 1.0).
  ::flatbuffers::Optional<double> gearing() const {
    return GetOptional<double, double>(VT_GEARING);
  }
  /// Optional per-optionlet spread added to the year-on-year rate
  /// (absent => 0.0).
  ::flatbuffers::Optional<double> spread() const {
    return GetOptional<double, double>(VT_SPREAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CAP_FLOOR_TYPE, 1) &&
           VerifyField<double>(verifier, VT_NOTIONAL, 8) &&
           VerifyOffsetRequired(verifier, VT_SCHEDULE) &&
           verifier.VerifyTable(schedule()) &&
           VerifyOffset(verifier, VT_INFLATION_INDEX_ID) &&
           verifier.VerifyString(inflation_index_id()) &&
           VerifyOffsetRequired(verifier, VT_OBSERVATION_LAG) &&
           verifier.VerifyTable(observation_lag()) &&
           VerifyField<int8_t>(verifier, VT_DAY_COUNTER, 1) &&
           VerifyField<int8_t>(verifier, VT_PAYMENT_CONVENTION, 1) &&
           VerifyField<double>(verifier, VT_CAP_RATE, 8) &&
           VerifyField<double>(verifier, VT_FLOOR_RATE, 8) &&
           VerifyField<double>(verifier, VT_GEARING, 8) &&
           VerifyField<double>(verifier, VT_SPREAD, 8) &&
           verifier.EndTable();
  }
  YoYInflationCapFloorT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(YoYInflationCapFloorT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<YoYInflationCapFloor> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCapFloorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct YoYInflationCapFloorBuilder {
  typedef YoYInflationCapFloor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cap_floor_type(quantra::enums::CapFloorType cap_floor_type) {
    fbb_.AddElement<int8_t>(YoYInflationCapFloor::VT_CAP_FLOOR_TYPE, static_cast<int8_t>(cap_floor_type));
  }
  void add_notional(double notional) {
    fbb_.AddElement<double>(YoYInflationCapFloor::VT_NOTIONAL, notional);
  }
  void add_schedule(::flatbuffers::Offset<quantra::Schedule> schedule) {
    fbb_.AddOffset(YoYInflationCapFloor::VT_SCHEDULE, schedule);
  }
  void add_inflation_index_id(::flatbuffers::Offset<::flatbuffers::String> inflation_index_id) {
    fbb_.AddOffset(YoYInflationCapFloor::VT_INFLATION_INDEX_ID, inflation_index_id);
  }
  void add_observation_lag(::flatbuffers::Offset<quantra::Period> observation_lag) {
    fbb_.AddOffset(YoYInflationCapFloor::VT_OBSERVATION_LAG, observation_lag);
  }
  void add_day_counter(quantra::enums::DayCounter day_counter) {
    fbb_.AddElement<int8_t>(YoYInflationCapFloor::VT_DAY_COUNTER, static_cast<int8_t>(day_counter));
  }
  void add_payment_convention(quantra::enums::BusinessDayConvention payment_convention) {
    fbb_.AddElement<int8_t>(YoYInflationCapFloor::VT_PAYMENT_CONVENTION, static_cast<int8_t>(payment_convention));
  }
  void add_cap_rate(double cap_rate) {
    fbb_.AddElement<double>(YoYInflationCapFloor::VT_CAP_RATE, cap_rate);
  }
  void add_floor_rate(double floor_rate) {
    fbb_.AddElement<double>(YoYInflationCapFloor::VT_FLOOR_RATE, floor_rate);
  }
  void add_gearing(double gearing) {
    fbb_.AddElement<double>(YoYInflationCapFloor::VT_GEARING, gearing);
  }
  void add_spread(double spread) {
    fbb_.AddElement<double>(YoYInflationCapFloor::VT_SPREAD, spread);
  }
  explicit YoYInflationCapFloorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<YoYInflationCapFloor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<YoYInflationCapFloor>(end);
    fbb_.Required(o, YoYInflationCapFloor::VT_SCHEDULE);
    fbb_.Required(o, YoYInflationCapFloor::VT_OBSERVATION_LAG);
    return o;
  }
};

inline ::flatbuffers::Offset<YoYInflationCapFloor> CreateYoYInflationCapFloor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Optional<quantra::enums::CapFloorType> cap_floor_type = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> notional = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<quantra::Schedule> schedule = 0,
    ::flatbuffers::Offset<::flatbuffers::String> inflation_index_id = 0,
    ::flatbuffers::Offset<quantra::Period> observation_lag = 0,
    ::flatbuffers::Optional<quantra::enums::DayCounter> day_counter = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<quantra::enums::BusinessDayConvention> payment_convention = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> cap_rate = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> floor_rate = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> gearing = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> spread = ::flatbuffers::nullopt) {
  YoYInflationCapFloorBuilder builder_(_fbb);
  if(spread) { builder_.add_spread(*spread); }
  if(gearing) { builder_.add_gearing(*gearing); }
  if(floor_rate) { builder_.add_floor_rate(*floor_rate); }
  if(cap_rate) { builder_.add_cap_rate(*cap_rate); }
  if(notional) { builder_.add_notional(*notional); }
  builder_.add_observation_lag(observation_lag);
  builder_.add_inflation_index_id(inflation_index_id);
  builder_.add_schedule(schedule);
  if(payment_convention) { builder_.add_payment_convention(*payment_convention); }
  if(day_counter) { builder_.add_day_counter(*day_counter); }
  if(cap_floor_type) { builder_.add_cap_floor_type(*cap_floor_type); }
  return builder_.Finish();
}

inline ::flatbuffers::Offset<YoYInflationCapFloor> CreateYoYInflationCapFloorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Optional<quantra::enums::CapFloorType> cap_floor_type = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> notional = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<quantra::Schedule> schedule = 0,
    const char *inflation_index_id = nullptr,
    ::flatbuffers::Offset<quantra::Period> observation_lag = 0,
    ::flatbuffers::Optional<quantra::enums::DayCounter> day_counter = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<quantra::enums::BusinessDayConvention> payment_convention = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> cap_rate = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> floor_rate = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> gearing = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> spread = ::flatbuffers::nullopt) {
  auto inflation_index_id__ = inflation_index_id ? _fbb.CreateString(inflation_index_id) : 0;
  return quantra::CreateYoYInflationCapFloor(
      _fbb,
      cap_floor_type,
      notional,
      schedule,
      inflation_index_id__,
      observation_lag,
      day_counter,
      payment_convention,
      cap_rate,
      floor_rate,
      gearing,
      spread);
}

::flatbuffers::Offset<YoYInflationCapFloor> CreateYoYInflationCapFloor(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCapFloorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline YoYInflationCapFloorT::YoYInflationCapFloorT(const YoYInflationCapFloorT &o)
      : cap_floor_type(o.cap_floor_type),
        notional(o.notional),
        schedule((o.schedule) ? new quantra::ScheduleT(*o.schedule) : nullptr),
        inflation_index_id(o.inflation_index_id),
        observation_lag((o.observation_lag) ? new quantra::PeriodT(*o.observation_lag) : nullptr),
        day_counter(o.day_counter),
        payment_convention(o.payment_convention),
        cap_rate(o.cap_rate),
        floor_rate(o.floor_rate),
        gearing(o.gearing),
        spread(o.spread) {
}

inline YoYInflationCapFloorT &YoYInflationCapFloorT::operator=(YoYInflationCapFloorT o) FLATBUFFERS_NOEXCEPT {
  std::swap(cap_floor_type, o.cap_floor_type);
  std::swap(notional, o.notional);
  std::swap(schedule, o.schedule);
  std::swap(inflation_index_id, o.inflation_index_id);
  std::swap(observation_lag, o.observation_lag);
  std::swap(day_counter, o.day_counter);
  std::swap(payment_convention, o.payment_convention);
  std::swap(cap_rate, o.cap_rate);
  std::swap(floor_rate, o.floor_rate);
  std::swap(gearing, o.gearing);
  std::swap(spread, o.spread);
  return *this;
}

inline YoYInflationCapFloorT *YoYInflationCapFloor::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<YoYInflationCapFloorT>(new YoYInflationCapFloorT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void YoYInflationCapFloor::UnPackTo(YoYInflationCapFloorT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cap_floor_type(); _o->cap_floor_type = _e; }
  { auto _e = notional(); _o->notional = _e; }
  { auto _e = schedule(); if (_e) { if(_o->schedule) { _e->UnPackTo(_o->schedule.get(), _resolver); } else { _o->schedule = std::unique_ptr<quantra::ScheduleT>(_e->UnPack(_resolver)); } } else if (_o->schedule) { _o->schedule.reset(); } }
  { auto _e = inflation_index_id(); if (_e) _o->inflation_index_id = _e->str(); }
  { auto _e = observation_lag(); if (_e) { if(_o->observation_lag) { _e->UnPackTo(_o->observation_lag.get(), _resolver); } else { _o->observation_lag = std::unique_ptr<quantra::PeriodT>(_e->UnPack(_resolver)); } } else if (_o->observation_lag) { _o->observation_lag.reset(); } }
  { auto _e = day_counter(); _o->day_counter = _e; }
  { auto _e = payment_convention(); _o->payment_convention = _e; }
  { auto _e = cap_rate(); _o->cap_rate = _e; }
  { auto _e = floor_rate(); _o->floor_rate = _e; }
  { auto _e = gearing(); _o->gearing = _e; }
  { auto _e = spread(); _o->spread = _e; }
}

inline ::flatbuffers::Offset<YoYInflationCapFloor> YoYInflationCapFloor::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCapFloorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateYoYInflationCapFloor(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<YoYInflationCapFloor> CreateYoYInflationCapFloor(::flatbuffers::FlatBufferBuilder &_fbb, const YoYInflationCapFloorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const YoYInflationCapFloorT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cap_floor_type = _o->cap_floor_type;
  auto _notional = _o->notional;
  auto _schedule = _o->schedule ? CreateSchedule(_fbb, _o->schedule.get(), _rehasher) : 0;
  auto _inflation_index_id = _o->inflation_index_id.empty() ? 0 : _fbb.CreateString(_o->inflation_index_id);
  auto _observation_lag = _o->observation_lag ? CreatePeriod(_fbb, _o->observation_lag.get(), _rehasher) : 0;
  auto _day_counter = _o->day_counter;
  auto _payment_convention = _o->payment_convention;
  auto _cap_rate = _o->cap_rate;
  auto _floor_rate = _o->floor_rate;
  auto _gearing = _o->gearing;
  auto _spread = _o->spread;
  return quantra::CreateYoYInflationCapFloor(
      _fbb,
      _cap_floor_type,
      _notional,
      _schedule,
      _inflation_index_id,
      _observation_lag,
      _day_counter,
      _payment_convention,
      _cap_rate,
      _floor_rate,
      _gearing,
      _spread);
}

inline const quantra::YoYInflationCapFloor *GetYoYInflationCapFloor(const void *buf) {
  return ::flatbuffers::GetRoot<quantra::YoYInflationCapFloor>(buf);
}

inline const quantra::YoYInflationCapFloor *GetSizePrefixedYoYInflationCapFloor(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<quantra::YoYInflationCapFloor>(buf);
}

inline bool VerifyYoYInflationCapFloorBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<quantra::YoYInflationCapFloor>(nullptr);
}

inline bool VerifySizePrefixedYoYInflationCapFloorBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<quantra::YoYInflationCapFloor>(nullptr);
}

inline void FinishYoYInflationCapFloorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::YoYInflationCapFloor> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedYoYInflationCapFloorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<quantra::YoYInflationCapFloor> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<quantra::YoYInflationCapFloorT> UnPackYoYInflationCapFloor(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::YoYInflationCapFloorT>(GetYoYInflationCapFloor(buf)->UnPack(res));
}

inline std::unique_ptr<quantra::YoYInflationCapFloorT> UnPackSizePrefixedYoYInflationCapFloor(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<quantra::YoYInflationCapFloorT>(GetSizePrefixedYoYInflationCapFloor(buf)->UnPack(res));
}

}  // namespace quantra

#endif  // FLATBUFFERS_GENERATED_YEARONYEARINFLATIONCAPFLOOR_QUANTRA_H_
